### ISSUE TITLE
CoreData: warning: Unable to load class named 'MQTTFlow' for entity 'MQTTFlow'

### ISSUE THREAD

**Issue by crsantos** [ckrey/MQTT-Client-Framework#102]
I'm seeing this error logged:

```
CoreData: warning: Unable to load class named 'MQTTFlow' for entity 'MQTTFlow'.  Class not found, using default NSManagedObject instead.
```

If a `.xcdatamodel` file was used to generate de CoreData models, I guess filling the name correctly would just be enough but just using code I don't know how to fix this.
Any ideas?

**Comment by ckrey** [comment]
MQTTFlow is just a protocol now, was an actual class before. 
The message is just a warning. Will fix

**Comment by crsantos** [comment]
:tada:
