### ISSUE TITLE
mosquitto, how to send PINGREQ to broker?

### ISSUE THREAD

**Issue by johnathanz** [ckrey/MQTT-Client-Framework#106]
I've set my keepalive setting on connection at 5 minutes on connection with a python powered mosquitto broker.

**Is there a way to send a PINGREQ Packet as indicated here to keep the connection alive?**
http://www.hivemq.com/blog/mqtt-essentials-part-10-alive-client-take-over

OR is this not possible, and we're expected to we **always** test MQTTSessionManager.state for an open before using the connection?

**Comment by ckrey** [comment]
The library sends PINGREQ after keepalive if there were no other messages during that time.

Still, the connection might have gone away for other reasons obviously.

BTW: what is a `python powered mosquitto broker` ? Is it mosquitto?

**Comment by johnathanz** [comment]
`python powered mosquitto broker` is just mosquitto :P

The error messages I'm getting are:
2016-02-10 19:03:45.063 <App ID> MQTTSession eventCode: connection closed (2) (null)
2016-02-10 19:03:45.065 <App ID> MQTTSession eventCode: connection error (3) Error Domain=NSPOSIXErrorDomain Code=54 "Connection reset by peer"
2016-02-10 19:03:46.091 <App ID> MQTTSession eventCode: connected (0) (null)

**Comment by ckrey** [comment]
So you keep a strong reference to the MQTTsession in your Code?
Do you try to run MQTTClient in the background?
Can you establish a connection at all?

**Comment by johnathanz** [comment]
The error seem to be related to `keepalive` setting on `MQTTSessionManager | connectTo`. Setting a larger value (e.g. 3000) will **delay** the error, but not prevent it.

I declare the mqttClientManager as a local ivar, with strong ref:
    @property (nonatomic, strong) MQTTSessionManager *mqttClient;

I do have code that runs in the background (downloading files for example), but it doesn't involve MQTT. To isolate the issue, I've set `keepalive` to 10, start the app & connect to Broker. And wait. After about 30 seconds, I get the error.

**Comment by ckrey** [comment]
Please make sure that the RunLoop you start the MQTTSessionManager in is actually active and not blocked by other activity. MQTTSessionManager starts a timer to issue Ping commands. If they are not received by the broker, the broker closes the session after 1.5 * keepalive

**Comment by johnathanz** [comment]
Thanks for the info. What does "blocked by other activity" mean?
