### ISSUE TITLE
Logs and CocoaLumberjack dependency

### ISSUE THREAD

**Issue by ogres** [ckrey/MQTT-Client-Framework#107]
Hello,

since last update, MQTT client now logs everything, 
for some reasons I do not want to use CocoaLumberjack and I have no control over logs,

almost all the headers include following 

```
#ifdef LUMBERJACK
#define LOG_LEVEL_DEF ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>
#ifdef DEBUG
static const DDLogLevel ddLogLevel = DDLogLevelWarning;
#else
static const DDLogLevel ddLogLevel = DDLogLevelWarning;
#endif
#else
#define DDLogVerbose NSLog
#define DDLogWarn NSLog
#define DDLogInfo NSLog
#define DDLogError NSLog
#endif
```

I think it would be better to create another file for this kind of definitions and then import it into other files,
it would be easier to maintain one file instead of go through the files and check where are logs,

also I`d prefer if **DEBUG** is not defined and there is no **CocoaLumberjack** available, just to ignore logs and not to output anything, 

something like this

```
#ifdef LUMBERJACK
#define LOG_LEVEL_DEF ddLogLevel
#import <CocoaLumberjack/CocoaLumberjack.h>
#ifdef DEBUG
static const DDLogLevel ddLogLevel = DDLogLevelWarning;
#else
static const DDLogLevel ddLogLevel = DDLogLevelWarning;
#endif
#else
#ifdef DEBUG
#define DDLogVerbose NSLog
#define DDLogWarn NSLog
#define DDLogInfo NSLog
#define DDLogError NSLog
#else
#define DDLogVerbose(...)
#define DDLogWarn(...)
#define DDLogInfo(...)
#define DDLogError(...)
#endif
#endif
```

**Comment by ckrey** [comment]
thanks Sergo, I will make the proposed changes

**Comment by ckrey** [comment]
Changed:

All `.m`files now import "MQTTLog.h".
If you want to override the `static const ddLogLevel` on a file based level,
define `myLogLevel`before the import

```
#define myLogLevel DDLogLevelVerbose

#import "MQTTLog.h"
```

**Comment by ogres** [comment]
Thank you very much!
