### ISSUE TITLE
Re-connect with a timer if MQTT broker goes offline

### ISSUE THREAD

**Issue by crsantos** [ckrey/MQTT-Client-Framework#108]
This could be mostly a doubt, not sure if this is supposed to work like this, or maybe this is working and I'm doing something wrong here.

I've found a scenario that if for some reason the broker disconnects me (maybe a reboot?), I cannot reconnect again unless I send a new message and the reconnect starts working again.

I've caught that disconnect case on `MQTTSessionDelegate` method  that is used on `MQTTSessionManager`: 

```obj-c
- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error
```

on the following `case:` clause:

```obj-c
	case MQTTSessionEventConnectionClosed:
	        case MQTTSessionEventConnectionClosedByBroker:
	            self.state = MQTTSessionManagerStateClosed;
	#if TARGET_OS_IPHONE == 1
	            if (self.backgroundTask) {
	                [[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];
	                self.backgroundTask = UIBackgroundTaskInvalid;
	            }
	#endif
	            self.state = MQTTSessionManagerStateStarting;
	            break;
``` 
That is ok, but I don't get any `NSError` here, and maybe it's supposed to be that way, anyway it's a disconnect, not a connection refused...

The problem is that the manager only reconnects on an error on the following `case:` clause (due to the following events):

```obj-c
    case MQTTSessionEventProtocolError:
            case MQTTSessionEventConnectionRefused:
            case MQTTSessionEventConnectionError:
            {
                self.reconnectTimer = [NSTimer timerWithTimeInterval:self.reconnectTime
                                                              target:self
                                                            selector:@selector(reconnect)
                                                            userInfo:Nil repeats:FALSE];
                NSRunLoop *runLoop = [NSRunLoop currentRunLoop];
                [runLoop addTimer:self.reconnectTimer
                          forMode:NSDefaultRunLoopMode];

                self.state = MQTTSessionManagerStateError;
                self.lastErrorCode = error;
                break;
            }
```
So even if I would to set a timer on an `MQTTSessionEventConnectionClosedByBroker` clause I couldn't differ that case from any other one, because I don't have an error to compare.

Have anyone else managed to replicate this?

Not sure If I made myself clear, if not, please reply me, so I can try to explain myself better :smile: 
Thanks in advance.

**Comment by Rift-Walker** [comment]
I've had the exact same issue, and that's the same section of code that I came to.

**Comment by Rift-Walker** [comment]
I've done a bit more digging, and it seems that MQTTSessionEventConnectionClosedByBroker is only raised in two places. 
One is here, and seems to never be called:
https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSession.m#L476 
The other is here, in mqttTransportDidClose: https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSession.m#L476

mqttTransportDidClose is only called from MQTTCFSocketTransport decoderdidClose, which is only called when the decoder receives NSStreamEventEndEncountered:
https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTCFSocketDecoder.m#L80

I can reproduce the issue reliably by restarting my broker (mosca) while the client is connected. It would be nice if we could start reconnecting when this happens.

I wonder, should we still call endBackgroundTask in this case?

Also, in the block crsantos posted above, there are two calls to set self.state. I may be missing something, but this seems unnecessary.
