### ISSUE TITLE
Can not receive msg when App go into background

### ISSUE THREAD

**Issue by richardzhaoxb** [ckrey/MQTT-Client-Framework#112]
Can not receive msg when App go into background in real device.  But it works in simulator

When the app is active, it receive msg soon. Press home let app go to background or lock the screen, no msg receive, open it to active then receive the offline msg.

I don't sure it is a bug or not, as it works fine in simulator.  

How can I receive the msg when App in background in real device ?

Thanks.

**Comment by crsantos** [comment]
Are you sure that the device didn't close your connection earlier?
Here it works fine..

**Comment by ckrey** [comment]
Simple answer:
you can not receive messages in the background.

If you want to keep the connection open, you need to trick iOS to keep the app running (see iOS background modes).

If you do not use background modes, the app is stopped in the background by iOS. In simulator, timing differs to a real device

**Comment by crsantos** [comment]
@ckrey Yes, forgot about that :) Thanks

**Comment by richardzhaoxb** [comment]
@ckrey Thank for quickly answer. 

@crsantos How can you do that, could you tell me some detail let real device keep connection in background?

**Comment by crsantos** [comment]
Because I have a custom `MQTTSessionManager`. 
The current session manager provided with this lib is disconnected when `appWillResignActive` is called and only reconnects on `appDidBecomeActive`.

**Comment by Balaprabustar** [comment]
@crsantos : Even im using my custom MQTTSessionManager, and i'm not disconnecting the connection.
App is still capable of receiving the BLE, I can able to do http request to the backend.

But, i receive connectionClosed callback from MQTTSession within 20-30 min once the app sent to background.

**Comment by Hephze** [comment]
Did you get push notification after the app is killed using MQTT?

**Comment by Harikrishna1993** [comment]
@ckrey  I enabled the background modes like Audio & Air Play and  Background fetch, but not receiving the messages in the background state. receiving all messages after entering foreground. 
Please suggest which background mode need to enable or work around for getting messages from MQTT in background state.
