### ISSUE TITLE
TLS support issue

### ISSUE THREAD

**Issue by 999studios** [ckrey/MQTT-Client-Framework#120]
I'm trying to implement TLS in my app. I have root-CA.crt, certificate.pem.crt and private.pem.key files. Do i need to convert these files to some other format because i'm getting SSL Handshake failed error when trying to connect to MQTT Server.

**Comment by ckrey** [comment]
I assume you are not trying to implement Client Certificates, but just want to check the server certificate.

I further assume you are using a self signed certificate. If not, you do not need to pass the root-CA.crt, but let iOS do the validation against it's keychain.

Your server should be setup using the certificate.pem.crt  and private.pem.key files. Can you please check that the server can be connected to from the command line via e.g. `mosquitto_sub ... --cafile root-CA.crt`.

If so, you need to have the certificate(s) in DER/CER file format and load the certificates similar to this example code:

```
        NSString *fileNames = @"cert1.der cert2.der";
        NSMutableArray *certs = nil;
        NSArray *components = [fileNames componentsSeparatedByString:@" "];
        for (NSString *fileName in components) {
            if (fileName && fileName.length) {
                NSString *serverCERpath = [directoryURL.path stringByAppendingPathComponent:fileName];;
                NSData *certificateData = [NSData dataWithContentsOfFile:serverCERpath];
                if (certificateData) {
                    if (!certs) {
                        certs = [[NSMutableArray alloc] init];
                    }
                    [certs addObject:certificateData];
                } else {
                    [AlertView alert:NSLocalizedString(@"TLS Security Policy",
                                                       @"Heading for security policy error message")
                             message:NSLocalizedString(@"invalid certificate file",
                                                       @"certificate file error message")
                     ];
                }
            }
        }
        securityPolicy.pinnedCertificates = certs;
        securityPolicy.allowInvalidCertificates = TRUE;
        securityPolicy.validatesCertificateChain = NO;
        securityPolicy.validatesDomainName = NO;
```

Set the boolean values allowInvalidCertificates,validatesCertificateChain, validatesDomainName according to your certificate creation process.

**Comment by 999studios** [comment]
Thank you for the help. I have converted root-CA.crt and certificate.pem.crt into DER fromat and assigned them to MQTTSSLSecurityPloicy.  This is what i'm doing

_session = [[MQTTSession alloc] init];
_session.delegate=self;
_session.transport = transport;
_session.securityPolicy = securityPolicy;
 if([_session connectAndWaitToHost:kMQTTServerHost port:kPort usingSSL:YES timeout:10.0])
{
}

Still gives SLL handshake failed.

**Comment by ckrey** [comment]
you don't need the certificate in the DER file, only the root-CA.
are you sure you set the
```
securityPolicy.allowInvalidCertificates = TRUE;
securityPolicy.validatesCertificateChain = NO;
securityPolicy.validatesDomainName = NO;```

**Comment by BharathChandrashekarFluke** [comment]
I have a similar issue trying to connect to Amazon AWS IoT.  I initially had rootCA.pem, certificate.pem.crt and private.pem.key files. As suggested in the earlier post, I converted rootCA.pem to rootCA.der. But I end up getting handshake failed error. This is my code:

 NSString* certificate1 = [[NSBundle mainBundle] pathForResource:@"private.pem" ofType:@"key"];
 NSString* certificate2 = [[NSBundle mainBundle] pathForResource:@"certificate.pem" ofType:@"crt"];
 NSString* certificate3 = [[NSBundle mainBundle] pathForResource:@"rootCA" ofType:@"der"];

MQTTSession *session = [[MQTTSession alloc] init];

session.securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeCertificate];

session.securityPolicy.pinnedCertificates = @[ [NSData dataWithContentsOfFile:certificate1], [NSData dataWithContentsOfFile:certificate2], [NSData dataWithContentsOfFile:certificate3] ];

  session.securityPolicy.allowInvalidCertificates = YES;
  session.securityPolicy.validatesCertificateChain = NO;
  session.securityPolicy.validatesDomainName = NO;

 [session connectToHost:@"........iot.us-west-2.amazonaws.com" port:8883 usingSSL:YES connectHandler:^(NSError *error) {
        if (error) {
            NSLog(@"ERROR: %@", error.localizedDescription);
        }
        else {
            NSLog(@"We are good");
        }
    }];

This is the error I get --- The operation couldn’t be completed. (OSStatus error -9825.)

Could you please help

**Comment by ckrey** [comment]
For AWS you need to pass your client certificate which you have created on AWS.

You don't need to use pinned certificates for the server cert or key or the ca.

And you need to keep the restrictions of AWS in mind:
http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

**Comment by BharathChandrashekarFluke** [comment]
Thanks for that. Keep up the good work.

**Comment by ckrey** [comment]
Did you solve your problem?

**Comment by imton** [comment]
Interested in how you solved this.

In our ruby lib we connect to Aws OiT like this

```ruby
AWS_IoT_MQTT = MQTT::Client.new.tap do |c|
  c.host = AWS_IoT.describe_endpoint.endpoint_address
  c.port = 8883
  c.ssl = true
  c.cert_file = Rails.root.join("config").join("aws").join("iot").join("certificate.pem.crt").to_s
  c.key_file  = Rails.root.join("config").join("aws").join("iot").join("private.pem.key").to_s
  c.ca_file   = Rails.root.join("config").join("aws").join("iot").join("rootCA.pem").to_s
end
```

**Comment by ckrey** [comment]
MQTTClient uses Apple's native CFNetwork framework. This means TLS including certificate checking use the iOS keychain to access trusted CAs. Symantec/Verisign are included. This is why you do not need to provide the root CA's certificate.

MQTTClient can alternatively use an explicit SSLSecurityPolicy for self signed certificates etc. But this is not necessary for AWS iot.

With regards to the client certificate you need to provide to the aws  this is what you need to do:

I assume you have used `aws iot describe-certificate` to create your client cert as `cert.pem` and the corresponding key as `thing-private-key.pem`.

Then you build an `aws.p12` file using `openssl pkcs12 -in cert.pem -inkey thing-private-key.pem -out aws.p12 -export` and assign an export password.

The you bring this file and the export password to the client and use it as follows (see https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/MQTTTestHelpers.m):
```
...
+ (NSArray *)clientCerts:(NSDictionary *)parameters {
    NSArray *clientCerts = nil;
    if (parameters[@"clientp12"] && parameters[@"clientp12pass"]) {
        
        NSString *path = [[NSBundle bundleForClass:[MQTTTestHelpers class]] pathForResource:parameters[@"aws"]
                                                                                     ofType:@"p12"];
        
        clientCerts = [MQTTCFSocketTransport clientCertsFromP12:path passphrase:parameters[@"exportpassword"]];
        if (!clientCerts) {
            DDLogVerbose(@"[MQTTTestHelpers] invalid p12 file");
        }
    }
    return clientCerts;
}
...

+ (id<MQTTTransport>)transport:(NSDictionary *)parameters {
    id<MQTTTransport> transport;
...    
            MQTTCFSocketTransport *cfSocketTransport = [[MQTTCFSocketTransport alloc] init];
            cfSocketTransport.host = parameters[@"host"];
            cfSocketTransport.port = [parameters[@"port"] intValue];
            cfSocketTransport.tls = [parameters[@"tls"] boolValue];
            cfSocketTransport.certificates = [MQTTTestHelpers clientCerts:parameters];
            transport = cfSocketTransport;
        }
    }
    return transport;
}

+ (MQTTSession *)session:(NSDictionary *)parameters {
    MQTTSession *session = [[MQTTSession alloc] init];
    session.transport = [MQTTTestHelpers transport:parameters];
...
    return session;
}


```

**Comment by imton** [comment]
@ckrey Thank you

```session.transport ``` was the key piece I was missing.

**Comment by drewantonich** [comment]
@imton Would you mind sharing the code you ended up using to connect to AWS IoT? I can't seem to get a MQTT publish to work.

**Comment by mataspetrikas** [comment]
@ckrey do you know if there's a way to use the private key signing without Open-SSL dependency?
I was wondering if I could put the private key into the DER file e.g. https://developer.apple.com/documentation/security/certificate_key_and_trust_services/certificates/storing_a_der_encoded_x.509_certificate
