### ISSUE TITLE
Synchronous API timeout

### ISSUE THREAD

**Issue by zlbe** [ckrey/MQTT-Client-Framework#121]
publishAndWaitData with qos 1 and a non zero timeout returns TRUE when the timeout is reached with no answer from the server, is it the normal behavior? If yes, is there any callback indicating the timeout was reached ?

**Comment by ckrey** [comment]
Thanks for spotting this.

I applied a fix for all ...AndWait methods

**Comment by zlbe** [comment]
Thank you Christoph, that was very quick!
I’ll test the fix today.

Best regards,

Laurent
