### ISSUE TITLE
Application crashes if RabbitMQ server is unavailable.

### ISSUE THREAD

**Issue by DipenPanchasara** [ckrey/MQTT-Client-Framework#122]
Application crashes when initialising connection to RabbitMQ server using MQTT client and server is not running/unavailable.

- Application is functioning  properly without any problem if RabbitMQ server is up and running.
- Application crashes without invoking any of the MQTTSession delegate method, even no trace of what happened only Websocket queue in debug session of  #xcode.

**Comment by ckrey** [comment]
Can you show me some low level logs?

Or can you try with `MQTTInspector`, which uses MQTTClient internally?

**Comment by DipenPanchasara** [comment]
I don't have any logs as application crash with SIG_BIT, so no trace of any log. Though i found solution of it.

Previously i was using `connect` method on `MQTTSession`, i replace that with following block method
`[self.mySession connectToHost:MQTT_HOST port:MQTT_PORT usingSSL:NO connectHandler:^(NSError *error)
     {
         if(error)
             DDLogError(@"Unable to connect to RabbitMQ server : %@",error.localizedDescription);
     }];`
It works like charm, with all the conditions i mentioned.

- To be very true i have not used `MQTTInspector`. Though will check on it.
I have also drop you a mail on your email account kindly reply on it.

Thanks for reply.
