### ISSUE TITLE
Websocket subspec is not compatible with tvos

### ISSUE THREAD

**Issue by ynnckcmprnl** [ckrey/MQTT-Client-Framework#123]
The MQTTClient/Websocket Cocoapods subspec (0.7.3) is not compatible with tvos. The MQTTClient pod is, is there a specific issue or has this not been updated yet?

https://github.com/CocoaPods/Specs/blob/master/Specs/MQTTClient/0.7.3/MQTTClient.podspec.json

```json
{
  "name": "Websocket",
  "platforms": {
    "ios": "6.1",
    "osx": "10.10"
  },
  "source_files": "MQTTClient/MQTTClient/MQTTWebsocketTransport/*.{h,m}",
  "dependencies": {
    "SocketRocket": [],
    "MQTTClient/Core": []
  }
}
```

**Comment by ckrey** [comment]
SocketRocket just added support for tvOS.
0.7.4 will run on with Websockets on tvOS

**Comment by ckrey** [comment]
when they upload the tvOS compatible version to cocoapods 
see square/SocketRocket#279

**Comment by ynnckcmprnl** [comment]
Thanks!
