### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by shokaveli** [ckrey/MQTT-Client-Framework#125]
I am trying to connect but keep getting the following error on connection attempt, then I receive a timeout.

[MQTTSession] mqttTransport didFailWithError Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={kCFGetAddrInfoFailureKey=8}

Any help would be appreciated. I am able to successfully connect my MQ server using a diff lib..not sure why its not working with this lib.

**Comment by ckrey** [comment]
kCFGetAddrInfoFailureKey means the host name you specified cannot be translated into an IP address by DNS. Would you please double check if the hostname you use in your code is correct?

**Comment by shokaveli** [comment]
yes host name is correct, and now I just get the following messages on the 
- (void)mqttTransport:(id<MQTTTransport>)mqttTransport didFailWithError:(NSError *)error delegate - >

: [MQTTCFSocketEncoder] NSStreamEventErrorOccurred
: [MQTTCFSocketEncoder] setState 0/2
: MQTTSession] mqttTransport didFailWithError Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"

Im not sure what I'm doing wrong.  Im supplying the same information as the IBM provided MQ iOS library but I just can't connect.  I provide the correct url, username, and password but keep getting "Op timed out" .  Any ideas as to what could be the cause?

On the IBM lib the protocol being used is MQTT v.3. I tried using both protocol 3 and 4 on your library but still nothing.  Could the protocol maybe be the issue?

Heres my init and connect methods -> 

 _session = [[MQTTSession alloc] initWithClientId:[self generateClientID]
                                            userName:_serverUsername
                                            password:_serverPassword
                                           keepAlive:60
                                        cleanSession:1
                                                will:NO
                                           willTopic:nil
                                             willMsg:nil
                                             willQoS:0
                                      willRetainFlag:NO
                                       protocolLevel:4
                                             runLoop:[NSRunLoop currentRunLoop]
                                             forMode:NSRunLoopCommonModes
                                      securityPolicy:nil
                                        certificates:nil];

    _transport = [MQTTCFSocketTransport new];
    _transport.host = _serverHost;
    _transport.port = _serverPort;

    _session.transport = _transport;
    _session.delegate = self;

    [_session connect];

After some time, maybe 60 seconds I get 2 handleEvent Callbacks -> 

MQTTSessionEventConnectionClosed
then
MQTTSessionEventConnectionError

**Comment by ckrey** [comment]
`I provide the correct url,` suggests you are not using a hostname (e.g. `test.mosquitto.org`)
`Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out"` my indicate a closed firewall in between!?

**Comment by shokaveli** [comment]
I'm using the following format -> 'blah.hostname.com'

**Comment by shokaveli** [comment]
I'm just confused because it works using a diff iOS library using the same hostname and creds : / but not this one..

**Comment by ckrey** [comment]
I am confused too. To get clarity, could you specify the IP address instead of the hostname for a test e.g. @"1.2.3.4"

**Comment by shokaveli** [comment]
The IP is inside my work's network so you wouldn't be able to access it : /

**Comment by shokaveli** [comment]
I only use 4 parameter to connect ->

1.host
2.port
3.username
4.password

We don't use SSL...Im trying to see if maybe theres something else i need to configure

**Comment by ckrey** [comment]
but you can try to use the IP please instead of the hostname!

My library uses iOS' CFNetwork, which works different to the low level socket library you are using.

**Comment by shokaveli** [comment]
Oh! So you think using the IP instead might work?

**Comment by ckrey** [comment]
yes, if it does, we know where to look for the problem

**Comment by shokaveli** [comment]
Ok so i tried it with the IP address and still keep getting the same errors : ( Is there any way to crank up the verbosity on the debug logs?

**Comment by ckrey** [comment]
Yes, change DDLogLevelWarning to DDLogLevelVerbose in

https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTLog.h

```
    #ifndef myLogLevel
        #ifdef DEBUG
            static const DDLogLevel ddLogLevel = DDLogLevelWarning;
        #else
            static const DDLogLevel ddLogLevel = DDLogLevelWarning;
        #endif
    #else

```

**Comment by ckrey** [comment]
@shagedorn were you able to resolve the problem?

**Comment by shagedorn** [comment]
I think you mentioned the wrong guy, did you? :)

**Comment by ckrey** [comment]
@shagedorn sorry, I meant @shokaveli

**Comment by nikeshmangwani** [comment]
Hi ckrey I am using SSL certificate but i am getting this type of error can you please guide me what i need to do.


MqttSession[902:151497] [MQTTCFSocketEncoder] NSStreamEventErrorOccurred
2016-11-15 01:55:48.654 MqttSession[902:151497] [MQTTCFSocketEncoder] setState 0/2
2016-11-15 01:55:48.654 MqttSession[902:151497] [MQTTSession] mqttTransport didFailWithError Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)"

**Comment by ckrey** [comment]
@nikeshmangwani your question is a bit off-topic here, could you open a separate issue, please?

How is the server certificate generated? Self signed or an official one (e.g. letsencrypt)?
If you have an official one you do not have to specify any certificate in the code.
If you have a self signed certificate (why?) you need to use MQTTSecurityPolicyTransport and set the pinnedCertificates there. To do that, you need the certificates in .cer format.

If you want to use client certificates, you need to specifiy them and provide them in .p12 format. See examples in MQTTTestHelper.m.


Error code kCFErrorDomainCFNetwork Code= 1 means 
>   kCFHostErrorHostNotFound = 1,

you are not using the correct hostname, or the hostname cannot be resolved by DNS, please double check

**Comment by ckrey** [comment]
http://developer.limneos.net/headers/4.0/CFNetwork.framework/Headers/CFNetworkErrors.h

**Comment by nikeshmangwani** [comment]
*Hi Christoph Krey Sir,*

*Thanks for the Reply, as per your guidance and questions i want to share
some details.*

*The certificate is generated by Godaddy.Com. Its a official certificate. *

*So, from this point--> *If you have an official one you do not have to
specify any certificate in the code.

*I made a project and place in github. I am getting the error connection
refused.*

*Github link for the project:*

*https://github.com/nikeshmangwani/Mqtt_POC_With_SSL
<https://github.com/nikeshmangwani/Mqtt_POC_With_SSL>*


*Can You please guide.*

*I am getting this error when i am connecting with device. Screen Shot
attached.*
*Connection refused is coming.*


*Thanks and Regards*
*Nikesh*

**Comment by ckrey** [comment]
Hi Nikesh,

the problem you have is not MQTT. You can try yourself with openssl:

```
$ openssl s_client -connect msg.falcontrack.com:8883
connect: Connection refused
connect:errno=61
```

Probably port 8883 of your server is not open

Regards
Christoph Krey

**Comment by nikeshmangwani** [comment]
*Hi Christoph Krey Sir,*

*Thanks for the Reply, as you said it was correct we have our development
and production type. So the correct thing is *devmsg.falcontrack.com:8883
<http://msg.falcontrack.com:8883/> instead of msg.falcontrack.com:8883

*But after that changes I got this error.*

*mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain
Code=-9807 "(null)"*


*Then after i tried to include the certificate in the NSBundle. and used
security policy but then also it is Not working.*


*After NSStreamHasSpaceAvailable it is not moving.*

*I have created a project for the project with *

https://github.com/nikeshmangwani/Mqtt_POC-With-SSL-Certificate-included

Screen Shot Attached For Log messages

Thanks and Regards

Nikesh

**Comment by ckrey** [comment]
Hi Nikesh,

I am ready to help, but I think you should read a bit more about TLS/SSL…


As openssl (see below) shows, you are using an untrusted certificate on devmsg.

Please note that the format for pinned certificates need to be .cer, not .crt

For development you may not use the certificate but then you should set
        policy.allowInvalidCertificates = YES;
        policy.validatesCertificateChain = NO;
        policy.validatesDomainName = NO;

Let me know if you need more support. Remember MQTTClient is open source and non profit.

Cheers
   Christoph

```
        NSString *filePath = [[NSBundle mainBundle] pathForResource:@"3d584c863c4aa16c" ofType:@"crt"];
        NSLog(@"%@",filePath);
        NSData *crtData = [NSData dataWithContentsOfFile:filePath];
        NSLog(@"%@",crtData);
        policy.pinnedCertificates = [[NSMutableArray alloc] initWithObjects:crtData, nil];
        
        NSLog(@"%@", policy.pinnedCertificates);
        policy.allowInvalidCertificates = NO;
        policy.validatesCertificateChain = YES;
        policy.validatesDomainName = YES;
```

```
$ openssl s_client -connect devmsg.falcontrack.com:8883
CONNECTED(00000003)
depth=0 /OU=Domain Control Validated/CN=*.falcontrack.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /OU=Domain Control Validated/CN=*.falcontrack.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /OU=Domain Control Validated/CN=*.falcontrack.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.falcontrack.com
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
—
```

**Comment by nikeshmangwani** [comment]
*Hi Christoph Krey Sir,*

*Thanks for the Reply, thanks for guiding me. I studied and tried few
things.*

*First Approach: I converted the Certificate in .cer format and then i have
added in bundle and tried.*
*But again same thing is happening ** NSStreamHasSpaceAvailable it is not
moving. please see the attached screen shot.*

*Github project:*

https://github.com/nikeshmangwani/Mqtt_POC-With-SSL-Certificate-included


*Second Approach:*

*I have installed the Certificate in device and tested again still the Same
result.*

*Can U please guide me. I am Stuck in that part and no idea is working. Can
you please tell me where i am getting wrong*


*Thanks and Regards*

*Nikesh*


Thanks and Regards

**Comment by nikeshmangwani** [comment]
Hi Sir,I am attaching one device photo with certificate installed.

Thanks and Regards
Nikesh

On Fri, Nov 18, 2016 at 12:35 AM, NIKESH MANGWANI <nikymangwani007@gmail.com

**Comment by ckrey** [comment]
Sorry, no photo here (doesn't work by mail)

**Comment by nikeshmangwani** [comment]
*Hi Christoph Krey Sir,*

*please read the below mail*

*I attached photo of certificate installed in device nothing else was there*

On Fri, Nov 18, 2016 at 12:35 AM, NIKESH MANGWANI <nikymangwani007@gmail.com

**Comment by ckrey** [comment]
The certificate in your github repo
https://github.com/nikeshmangwani/Mqtt_POC-With-SSL-Certificate-included/blob/master/Mqtt_POC/certificate.cer

is __NOT__ in cer/der format (easy to see as cer/der is binary, not text).

You can check this by yourself:

```
$openssl x509 -inform DER -in certificate.cer -text
unable to load certificate
88974:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/crypto/asn1/tasn_dec.c:1344:
88974:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/crypto/asn1/tasn_dec.c:387:Type=X509

```

**Comment by nikeshmangwani** [comment]
*Hi Christoph Krey Sir,*

*Thanks for your Support, Certificate was the Problem. We Changed the
certificate and it Worked.*

*Thanks for all your efforts and Guidance. Nice to have contact with you.*

*Thank you Very Much*


*Thanks and Regards*
*Nikesh*

**Comment by nikeshmangwani** [comment]
Hi Ckrey Sir,

Can u Please erase the conversation from the github because it contains our
legal data so please requesting you to erase it.

thanks and regards
Nikesh

**Comment by ckrey** [comment]
> 
> Can u Please erase the conversation from the github because it contains our
> legal data so please requesting you to erase it.
> 

Done

**Comment by nikeshmangwani** [comment]
Hi ckrey Sir,

Thank you very much.

Thanks and Regards
Nikesh

**Comment by amoshsueh** [comment]
@ckrey I have the same issue. Using IP address instead hostname can solve this issue. Is any idea I can use host name because IP address might be changed sometimes?
