### ISSUE TITLE
Connection closed by Broker or Protocol Error

### ISSUE THREAD

**Issue by gkaur1** [ckrey/MQTT-Client-Framework#126]
Hi I am using MQTT-Client-Framework library to talk to an Mosquito server.
For initializing the session I am using the code below
session = [[MQTTSession alloc] initWithClientId:@"SomeString" userName:@"MYUSERNAME" password:@"MYPASSWORD" keepAlive:60 cleanSession:true will:false willTopic:nil willMsg:nil willQoS:MQTTQosLevelAtMostOnce willRetainFlag:false protocolLevel:MQTTProtocolVersion31 runLoop:nil forMode:nil];
    session.delegate = self;
    [session connectToHost:host port:port usingSSL:usingSSL];

The host is an inhouse server installed mosquito and listening on port 8080 and not using SSL.
Is there some extra logging that I can do figure out why is the connection being closed by the broker?

**Comment by ckrey** [comment]
Are you sure mosquitto is listening to port 8080? Typically it would be 1883.
Are you using mqtt as the protocol on port 8080, or websockets? (please check your mosquitto.conf).

Can you connect and subscribe with mosquitto_sub to the broker with the same credentials?

`mosquitto_sub -h host -p port -i SomeString -u MYUSERNAME -P MYPASSWORD -t '#' -v`

You may implement the
`- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error;`method and have a look at event and error codes

**Comment by gkaur1** [comment]
Yes I am able to connect to the mosquitto server thru command subscribe and publish.

I did implement handleEvent delegate method...which is always return ConnectionClosed followed by Connection closed by broker (event code) or Protocol error...Its either or...

**Comment by ckrey** [comment]
Do you have access to the mosquitto logs?
