### ISSUE TITLE
Max 120 messages incoming

### ISSUE THREAD

**Issue by GKoons** [ckrey/MQTT-Client-Framework#130]
If I subscribe to a topic that has 200 retained messages on a mosquitto broker, I'm only receiving 120 of those. I believe it has something to do with the max inflight messages the mosquitto broker supports. From my research it seems that any messages that are not acknowledged by the client will be re-sent when the inflight queue starts to go empty, but I don't see that happening. I was able to bypass this limitation by increasing the max inflight window on the broker and all 200 are then received.

Is there additional support on the client needed to match these values and enable all 200 messages to to be delivered to the client even with the lower / default inflight window? I noticed the MQTTInMemoryPersistence class might be used here, but I'm not clear on how to utilize it.

**Comment by ckrey** [comment]
Retained messages are delivered when subscribed to.
Which QoS do you use when subscribing?
If you use QoS0 it is normal to loose messages if a lot of messages are send at once.
Try subscribing with QoS1 or QoS2.
Acknowledgements and resends will only happening with QoS > 0.

The inflight window on the server (which server are you using?) controls how many messages are sent to the client before waiting for acknowledgements.

A similar window exists on the client.

**Comment by GKoons** [comment]
All topics are subscribed with QoS 1: [self.mqttClient subscribeToTopic:topic atLevel:MQTTQosLevelAtLeastOnce], but the server still seems to drop any messages that exceed the server's inflight window.

The mosquitto broker is hosted on AWS. One note: when I subscribe to the same topic using the mosquitto command-line based client then all 200 retained messages are received. 

I'm not utilizing the MQTTSessionManager right now, and I'm assuming that might be my problem.

**Comment by GKoons** [comment]
I found the issue. MQTTSession's delegate was responding to newMessage:.. instead of newMessageWithFeedback: in order to send the pub ack to the broker. I'll close this down and thanks for your patience!
