### ISSUE TITLE
On how to subscribe to Message

### ISSUE THREAD

**Issue by 1247706647** [ckrey/MQTT-Client-Framework#133]
When I want to subscribe to message
    self.session=[[MQTTSession alloc] initWithClientId:@"clientId"];
    self.session.delegate=self;
    [self.session connectAndWaitTimeout:30];
    self.session.cleanSessionFlag = YES;
    [self receiveMessage];
-(void)subscribeMessage
{
        [self.session  connectToHost:@"tcp://mqtt.ons.aliyun.com" port:1883 usingSSL:YES connectHandler:^(NSError *error) {
        NSLog(@"error=%ld@",error.code);
        [self.session subscribeToTopic:@"swantest" atLevel:MQTTQosLevelExactlyOnce];
    }];
}

but I can't receive any messages, error.code=1.Where did I go wrong？

**Comment by ckrey** [comment]
host is the hostname (e.g. "mqtt.ons.aliyun.com"), not the url!
1883 is typically used for plain (usingSSL:NO), but that's obviously your choice. Please check.

cleanSessionFlag is only used at connect, set it before connect.

If you are calling connectToHost, you don't need connectandWait.

**Comment by 1247706647** [comment]
than,I I according to the example of writing:
    MQTTCFSocketTransport* transport=[[MQTTCFSocketTransport alloc] init];
    transport.host=@"mqtt.ons.aliyun.com";
    transport.port = 1883;
    self.session=[[MQTTSession alloc] initWithClientId:@"clientId"];
    self.session.delegate=self;
    self.session.transport=transport;
    [self.session connectAndWaitTimeout:10];
    [self subscribeMessage];

 -(void)subscribeMessage
{
    [self.session subscribeToTopic:@"swantest" atLevel:1 subscribeHandler:^(NSError *error,        NSArray<NSNumber *> *gQoss){
            if (error) {
                NSLog(@"Subscription failed %@", error.localizedDescription);
            } else {
                NSLog(@"Subscription sucessfull! Granted Qos: %@", gQoss);
            }
        }]; 
}
but I also can't receive anymessage

**Comment by 1247706647** [comment]
When using MQTTSession to connect to the server, I set up the host, port, the client id, if I want the connection is successful, in addition, I also want to configure which parameters

**Comment by ckrey** [comment]
@1247706647 did you check of your connect worked?
```
[self.session connectAndWaitTimeout:10];

if (self.session.status == MQTTSessionStatusConnected) {
     [self subscribeMessage];
...
}
```
