### ISSUE TITLE
Can MQTTSessionManager make MQTT over websocket?

### ISSUE THREAD

**Issue by lianghuiyuan** [ckrey/MQTT-Client-Framework#134]
Hi, ckrey
    It seems that MQTTSessionManager make MQTT only over TCP? 
    Can MQTTSessionManager make MQTT over websocket?
    Thank you!

**Comment by ckrey** [comment]
Correct. 

It could but I never started to extend the interface.
I would though accept contributions.

And again/still I would like to understand the use case for MQTT over websockets from a device.

**Comment by ganjmeng** [comment]
Hi, ckrey
How to user MQTT-Client-Framework over websocket??? any example?  I need your help!😥

Thank you！

**Comment by ckrey** [comment]
MQTTSessionManager builds on top of MQTTSession.

MQTTSession fully supports Websockets. To use it, create an MQTTWebSocketTransport instead of an MQTTCFNetworkTransport.

I have not implemented this alternatives in the MQTTSessionManager layer yet.

**Comment by ganjmeng** [comment]
I had solve this problem ,Thank your  very much!!!

最后一个问题，I don't know what is  'checkDup' mean，Thank you！！！
![image](https://cloud.githubusercontent.com/assets/12026835/16649352/289f0212-446b-11e6-9e49-abb7e25391e7.png)
我的英语太差了，谢谢您一直回答我的问题！！真心的感谢

**Comment by mendirattanishant** [comment]
@ganjmeng  how did you solve it? Do you have any code you can share?

**Comment by ganjmeng** [comment]
@mendirattanishant  create an MQTTWebSocketTransport instead of an MQTTCFNetworkTransport.
