### ISSUE TITLE
Detect disconnection from broker

### ISSUE THREAD

**Issue by szemian** [ckrey/MQTT-Client-Framework#135]
Hi,

is there a way for a client to detect that it has been disconnected from the broker?

I started a local test mosquitto broker, connect the client, then kill the broker process. The client did not receive any event. The error only occurs when I try to publish a topic from the client and it received a Error Domain=MQTT Code=-5 "Encoder not ready".

Is there a better way to monitor the connection?

**Comment by ckrey** [comment]
mmh, I always get an event when killing the broker e.g.:

```
2016-05-10 06:49:18:248 MQTT eventCode: connection closed (2) (null)
...
2016-05-10 06:49:18:253 MQTT eventCode: connection closed by broker (5) (null)
```

You may always check the MQTTSession status.

**Comment by szemian** [comment]
Currently I am checking the status. I think the client did not receive any event because the status is "stuck" at MQTTSessionStatusDisconnecting but not MQTTSessionStatusClosed. However, I am unable to trace which part to the code change the status to MQTTSessionStatusDisconnecting.

**Comment by szemian** [comment]
My bad. I thought the delegate method connectionClosed: will be called, and didn't implement the handleEvent:event:error: method.

Thanks for your help.

**Comment by ithaqua** [comment]
Hi , how to fix encode not ready ?
