### ISSUE TITLE
When you kill your app from the app swicher,MQTTCoreData Persistence can't work well

### ISSUE THREAD

**Issue by lichao1992** [ckrey/MQTT-Client-Framework#137]
I'd like to implement MQTT persistence by setting the persistence before connecting to an MQTT broker
This is my implementation test:

step1: Setting the properties of persistence immediately after creating MQTTSession,then conenct to MQTT Broker
    self.mqttSession = [[MQTTSession alloc] init];
    self.mqttSession.persistence.persistent = YES;

step2: Close network equipment and Publish data on topic, then in this method
// tell
- (void)tell {
    NSUInteger incoming = [self.persistence allFlowsforClientId:self.clientId
                                                   incomingFlag:YES].count;
    NSUInteger outflowing = [self.persistence allFlowsforClientId:self.clientId
                                                     incomingFlag:NO].count;
    if ([self.delegate respondsToSelector:@selector(buffered:flowingIn:flowingOut:)]) {
        [self.delegate buffered:self
                      flowingIn:incoming
                     flowingOut:outflowing];
    }
    if ([self.delegate respondsToSelector:@selector(buffered:queued:flowingIn:flowingOut:)]) {
        [self.delegate buffered:self
                         queued:0
                      flowingIn:incoming
                     flowingOut:outflowing];
    }
}

I  NSLog the value of outflowing,the value is 1,if continue to publish data,the value increase,in this situation,it work well

step3: I swiping up to kill the app and runing the app again, in MQTTSesson connect method, in tell function I get the value of outflowing is 0. that is a problem i encountered and i have test it many times,
// connect
- (void)connect {
    DDLogVerbose(@"[MQTTSession] connecting");
    if (self.cleanSessionFlag) {
        [self.persistence deleteAllFlowsForClientId:self.clientId];
        [self.subscribeHandlers removeAllObjects];
        [self.unsubscribeHandlers removeAllObjects];
        [self.publishHandlers removeAllObjects];
    }
    [self tell];
..........

step4:I thought of a solution,I add some code in method inside MQTTCoreDataPersistence,let the parentManagedObjectContext also save,then it work well

// sync
- (void)sync {
    [self.managedObjectContext performBlockAndWait:^{
        if (self.managedObjectContext.hasChanges) {
            DDLogVerbose(@"[MQTTPersistence] pre-sync: i%lu u%lu d%lu",
                         (unsigned long)self.managedObjectContext.insertedObjects.count,
                         (unsigned long)self.managedObjectContext.updatedObjects.count,
                         (unsigned long)self.managedObjectContext.deletedObjects.count
                         );
            NSError *error = nil;
            if (![self.managedObjectContext save:&error]) {
                DDLogError(@"[MQTTPersistence] sync error %@", error);
            }
            if (self.managedObjectContext.hasChanges) {
                DDLogError(@"[MQTTPersistence] sync not complete");
            }
            
            // This line is my added code
            if ([parentManagedObjectContext hasChanges] && ![parentManagedObjectContext save:&error])      {
                DDLogError(@"[MQTTPersistence] sync error %@", error);
            }
            
            NSError *parentError = nil;
            if (![parentManagedObjectContext save:&parentError]) {
                DDLogError(@"parentManagedObjectContext save error");
            }
            DDLogVerbose(@"[MQTTPersistence] postsync: i%lu u%lu d%lu",
                         (unsigned long)self.managedObjectContext.insertedObjects.count,
                         (unsigned long)self.managedObjectContext.updatedObjects.count,
                         (unsigned long)self.managedObjectContext.deletedObjects.count
                         );
            [self sizes];
        }
    }];
}

I don't know whether or not my test procedure is wrong....

**Comment by ckrey** [comment]
You are right! I knew about this problem (see #117), but wasn't sure how to correctly fix it.
I think I found a solution now.
