### ISSUE TITLE
App crashes when network connection status changes between offline and online

### ISSUE THREAD

**Issue by liennh** [ckrey/MQTT-Client-Framework#139]
(lldb) bt
- thread #1: tid = 0x5859de, 0x0000000199881bd0 libobjc.A.dylib`objc_msgSend + 16, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x12820790)
  frame #0: 0x0000000199881bd0 libobjc.A.dylib`objc_msgSend + 16
  frame #1: 0x0000000184c23b0c CoreFoundation`_inputStreamCallbackFunc + 56
  frame #2: 0x0000000184bcdd04 CoreFoundation`_signalEventSync + 192
  frame #3: 0x0000000184bcdc20 CoreFoundation`_cfstream_shared_signalEventSync + 444
  frame #4: 0x0000000184c305a4 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
  frame #5: 0x0000000184c30038 CoreFoundation`__CFRunLoopDoSources0 + 540
  frame #6: 0x0000000184c2dd38 CoreFoundation`__CFRunLoopRun + 724
  frame #7: 0x0000000184b5cdc0 CoreFoundation`CFRunLoopRunSpecific + 384
  frame #8: 0x000000018fcb0088 GraphicsServices`GSEventRunModal + 180
  frame #9: 0x000000018a236f44 UIKit`UIApplicationMain + 204
  - frame #10: 0x000000010010d5e8 FollowMe`main(argc=1, argv=0x000000016fd37a80) + 124 at main.m:14
    frame #11: 0x000000019a09a8b8 libdyld.dylib`start + 4
    (lldb)

**Comment by ckrey** [comment]
Is this problem still happening? 
In which environment?

**Comment by liennh** [comment]
It happened a long time ago. Now I don't work on it. Anyway thank you for your interest.
