### ISSUE TITLE
The message received by the client is empty.

### ISSUE THREAD

**Issue by YZDCDL** [ckrey/MQTT-Client-Framework#141]
Hello, I have a client 1 to send a message to a topic 'A', another client 2 to receive the message of this topic 'B'. But when the client 1 sends a number of messages, the message on the client 2 is empty. The server side print out the error PUBCOMP'Qos is not '0', so I want to know PUBCOMP'Qos change in which file, thank you;

my English is poor，hope you can understand the above description, thanks.

**Comment by ckrey** [comment]
@YZDCDL can you be a bit more specific, please?
