### ISSUE TITLE
How to use that in my task??

### ISSUE THREAD

**Issue by ganjmeng** [ckrey/MQTT-Client-Framework#146]
Hey ckrey!

My colleague commend your Framework to me,
But I don't konw How to use it in my task??
Please help me! many Thank!

**Comment by ganjmeng** [comment]
I'm sorry about that my English is so terrible...😂

**Comment by ckrey** [comment]
I can suggest to you to start with blog entry and the chat example here:
http://www.hivemq.com/mqtt-client-library-encyclopedia/

The hivemq blog is a very good and comprehensive MQTT encyclopedia

**Comment by ganjmeng** [comment]
I had use your demo successed to connect the server and revice  messages!!!  Thank your  very much!!!

![img_1154](https://cloud.githubusercontent.com/assets/12026835/15665782/907acd56-273f-11e6-89fe-fdc0123c1d7c.PNG)

**Comment by ganjmeng** [comment]
Hey ckrey!

I have problem that how I can know the mesaages I sended was success or faild ?
I know the 'MQTTSessionManager' delegate has a Method named `- (void)messageDelivered:(UInt16)msgID`,but when I send a message and my another program had reviced this message, the method was not execute。
![image](https://cloud.githubusercontent.com/assets/12026835/15734720/266c9156-28c5-11e6-8eb3-fa2e064c6dea.png)
my qos config was `MQTTQosLevelAtMostOnce`  when I setting the Qos to be `MQTTQosLevelAtLeastOnce` or `MQTTQosLevelExactlyOnce`  the message can't  be revice.

**Comment by ckrey** [comment]
Correct, the method is not called when qos is  `MQTTQosLevelAtMostOnce` (0)

>  /** gets called when a published message was actually delivered
> @param msgID the Message Identifier of the delivered message
> @note this method is called after a publish with qos 1 or 2 only
> */
> - (void)messageDelivered:(UInt16)msgID;

Which kind of broker do you use? Does it support qos > 0?

**Comment by ganjmeng** [comment]
Thank your for your help!
when I set Qos > 0 ,My app will can't send messages successfully，
Maybe this is a server configuration problem?
