### ISSUE TITLE
Getting Disconnected RabbitMQ

### ISSUE THREAD

**Issue by vipu1212** [ckrey/MQTT-Client-Framework#147]
When app lanuches, delegate method

> received

  is called and then suddenly 

> connectionClosed

method is called. What am I doing wrong? Am not receiving any messages I subscribed to cz am getting disconnected!(I guess)

```
        let transport = MQTTCFSocketTransport()
        transport.host = kHOST
        transport.port = 1883
        
        session.transport = transport
        
        session.delegate = self
        
        session.subscribeTopic("test")
        
        session.connect()

```

**Comment by ckrey** [comment]
you need to connect and wait for completion before sending or subscribing.

Either implement the callback methods, observe session.status, use the block methods or the synchronous methods

.connect completionHandler
.connectAndWait()

**Comment by vipu1212** [comment]
Ok. thanks. Saw error from completion handler. Was authentication issue. Thanks 👍
