### ISSUE TITLE
Crash while executing "CloseandWait"

### ISSUE THREAD

**Issue by rdalmia** [ckrey/MQTT-Client-Framework#15]
Hi,

I am able to produce this crash many times, where in the MQTTSession is executing this method closeandWait and the app crashes.

Following is some crash log for the same:

CoreFoundation 0x3106af53 __exceptionPreprocess + 131
libobjc.A.dylib 0x3b4436af objc_exception_throw + 36
CoreFoundation 0x3106e8e7 -[NSObject(NSObject) doesNotRecognizeSelector:] + 200
CoreFoundation 0x3106d1d3 ___forwarding___ + 704
CoreFoundation 0x30fbc598 _CF_forwarding_prep_0 + 22
AppName 0x0006bc7b -[MQTTSession closeAndWait] (MQTTSession.m:497)
AppName 0x00187283 -[MQTTConnection connectionClosed:withError:] (MQTTConnection.m:543)
AppName 0x00186855 -[MQTTConnection timerIntervalCompleted] (MQTTConnection.m:315)
Foundation 0x31a4eecd __NSFireTimer + 62

Could you have a look and let me know in case there is any issue.

Regards
Ravi

**Comment by ckrey** [comment]
@rdalmia did you get this working? You may have a look at the discussion in #33

**Comment by rdalmia** [comment]
No for now, I saw the discussion it was a great hang out.
But my scenario is more typical and an handling reconnects even
in foreground if we do not get acknowledgement for 5 ping responses even if
the app is not doing anything.

I plan to work on this at some point in time.
Thanks for your concern.

Regards
Ravi
