### ISSUE TITLE
About the self-signed certificate

### ISSUE THREAD

**Issue by xiaopohaihouhou** [ckrey/MQTT-Client-Framework#154]
The Server give me a self-signed certificate(.crt),i write it in the local.I know MQTT-Client-Framework  support cer or der, but how do I use this certificate(.crt) to connect the MQTT server?

**Comment by ckrey** [comment]
There are lots of resources (e.g. http://info.ssl.com/article.aspx?id=12149) which describe how to convert certificate formats.
