### ISSUE TITLE
Support for Apple Watch?

### ISSUE THREAD

**Issue by duncsand** [ckrey/MQTT-Client-Framework#156]
The cocoapods install doesn't build for Apple Watch. Is there any reason why the build can't be updated to support?

**Comment by duncsand** [comment]
I have an iOS app that listens for MQTT msgs that I want an Apple Watch client for. To work around not using MQTT on the watch, I thought I'd try running MQTT on the phone and using WCSession to send data between watch and iPhone.
The scenario is iPhone isn't active and the user is using the watch. WCSession activates the app in background mode when the watch app is started (this bit works ok). My plan then was for the watch to subscribe to MQTT and start receiving msgs. However, it doesn't seem that I can subscribe and receive msgs in background mode (at least I can't seem to get that working). Is this correct? i.e. is it possible at all to do what I want to?

**Comment by ckrey** [comment]
I have no experience with WCSession, but in all other Background modes it is possible to connect.
But all Background modes are time limited, so you need to be quick and gracefully disconnect before iOS  kills your app.

**Comment by ckrey** [comment]
With regards to your original question, I have not tried and tested MQTT natively on WatchOS.
If you want to give it a try, I would be happy to accept contributions

**Comment by ankittayde1987** [comment]
Hi All, 

I am having the same issue like yours. I am successfully able to process  MQTT over iPhone & iPad, but now I want it to be done through apple watch - I tried with the same files and framework dropping into the project and run it into iWatch but no luck. I also tried it through Cocoapods but it gives me an error saying its not supported for watchos2. So please suggest some other library or framework with supports apple watch MQTT.
