### ISSUE TITLE
Value of qos level from PUBACK Packet should be limited to zero?

### ISSUE THREAD

**Issue by lichao1992** [ckrey/MQTT-Client-Framework#158]
Today, my friend had a problem when she used Ali cloud server, after publish a packet, receive PUBACK Packet, will encounter an error, [MQTTMessage] illegal header flags
   Then I looked at the source code, navigate to the specific location，I find source code limite the qos level of PUBACK Packet
![image](https://cloud.githubusercontent.com/assets/10915413/16144573/6b824faa-34a6-11e6-91dd-708eb043af8b.png)

   First,I don't know why Ali cloud server send PUBBACK packte with qos level equal to 1,it may Ali cloud server error.  MQTT3.1.1 don't explain the value of PUBACK Packet qos,But I think it should be zero,becase PUBACK merely a response to PUBLISH,The only similarities is the mid
  Second, Although this value should be zero, but I think it should not limit this value，I've seen the Android client code and server-side code, they have not done for this limiting process value。
  Here are my questions and a suggestion，I hope this will be useful to you.

**Comment by ckrey** [comment]
I am pointing you to the standards document:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

have a look at 3.4 where the PUBACK header is described and at 2.2.2 where 
the reaction to protocol errors is described.

I have not tested my library against AIi cloud service, but to many other brokers and services. Please log an issue with Ali

**Comment by lichao1992** [comment]
I have this question to reflect the Ali cloud server，Their initial response was to say, Their side  PUBACK Packet qos default is 1
  My friend has made two shots to the other side
![image](https://cloud.githubusercontent.com/assets/10915413/16182573/6fbfe9de-36da-11e6-9996-bf35e0997808.png)
![image](https://cloud.githubusercontent.com/assets/10915413/16182588/8ab59e14-36da-11e6-984c-33de6047eb23.png)
  I'm waiting for them further response

**Comment by lichao1992** [comment]
![image](https://cloud.githubusercontent.com/assets/10915413/16252437/aae86aae-3860-11e6-8e8c-5ddc0c4856bd.png)
This is the latest Ali cloud server reply，They will fix this problem in the next version~
