### ISSUE TITLE
About session subscribe behavior

### ISSUE THREAD

**Issue by jhaoheng** [ckrey/MQTT-Client-Framework#162]
Hello

```
MQTTSessionManager *manager = [[MQTTSessionManager alloc]init];
    manager.delegate = self;
    
    [manager addObserver:self
              forKeyPath:@"effectiveSubscriptions"
                 options:NSKeyValueObservingOptionInitial | NSKeyValueObservingOptionNew
                 context:nil];
    
    manager.subscriptions = [@{@"/#": @(0),@"$SYS/#": @(0)} mutableCopy];
    
    [manager connectTo:url
                  port:1883
                   tls:NO
             keepalive:60
                 clean:true
                  auth:true
                  user:username
                  pass:password
                  will:false
             willTopic:nil
               willMsg:nil
               willQos:0
        willRetainFlag:false
          withClientId:@"ttt"];
[manager removeObserver:self forKeyPath:@"effectiveSubscriptions"];
```

Although  i set `manager.subscriptions`, but i can not get message by other device's publish.
and when i use `manager.effectiveSubscriptions` to get all `effectiveSubscriptions`, it response empty to me.
So could you help me to solve this question?

and #44 say [avoid re-subscriptions of already subscribed topic filters to avoid]
How to do it with `MQTTSession.h`
I can subscribe by `MQTTSession.h` but need subscribe every connect.
How to [avoid re-subscriptions of already subscribed topic filters to avoid]

Thank you

**Comment by jhaoheng** [comment]
[update]
I solve these questions

> Q1: about use `MQTTSessionManager.h`
Should use `self.manager` to set delegate, and then delegate workable.
and `manager.effectiveSubscriptions` only can get it when connect success.

> Q2: about use `MQTTSession.h` [avoid re-subscriptions of already subscribed topic filters to avoid]
I dont know about it.
when i use
```
sessionClient = [[MQTTSession alloc] initWithClientId:clientId
                                                 userName:email
                                                 password:pw
                                                keepAlive:60
                                             cleanSession:NO
                                                     will:NO
                                                willTopic:nil
                                                  willMsg:nil
                                                  willQoS:0
                                           willRetainFlag:NO
                                            protocolLevel:4
                                                  runLoop:[NSRunLoop currentRunLoop]
                                                  forMode:NSDefaultRunLoopMode
                                           securityPolicy:nil
                                             certificates:nil];
```
It is ok to get msg which i not set `subscribe` when connect.
Why i set this config will be ok to get msg from broker when connect second time?
(I had already subscribe topic in first time)
I do not set anything, just only remove my subscribe method in second compile.

and when i only set `clientId`, `username`, `password`, `keepalive` to session,
do the same things like above.
1. do subscribe topic method and compile
2. close app, and remove subscribe method
3. send msg from cmd.(mosquito_pub)
4. compile second time.

and, i can not get message from second time.

**Comment by ckrey** [comment]
Hi @jhaoheng 

you will only get messages "for the second time" when
a) the messages are "retained" and
b) you subscribe to the topic freshly

With cleansession=NO and using the same clientId, your broker will remember the subscriptions you made before (if the broker was not restarted ...)

MQTTSessionManager does manage this for you if you don't want to manage it yourself using MQTTSession.

There is a good primer on MQTT and the different QoS levels, client persistence and retained messages here: http://www.hivemq.com/blog/mqtt-essentials-wrap-up

**Comment by ckrey** [comment]
@jhaoheng  did you resolve the issue? Can we close the issue?

**Comment by jhaoheng** [comment]
Yes, thanks your help.
