### ISSUE TITLE
Duplicated messages sent using MQTTQosLevelExactlyOnce

### ISSUE THREAD

**Issue by crsantos** [ckrey/MQTT-Client-Framework#169]
We're having duplicated messages delivered on an enviroment with bad network conditions. We're using `MQTTQosLevelExactlyOnce` QoS level (from what we can infer from that type - the client should not send duplicated messages).

From our analysis to the implementation of MQTTClientFramework it seems that this is related with a "lost"/"hang" _PUBACK_ on the network because the `messageDelivered:` delegate is not called sometimes.

On `MQTTSession.m` there is a timer that calls `- (void)checkTxFlows` from time to time.

We checked that 20s passes between the duplicated messages. The same value we found on the constant `DUPTIMEOUT`.

We concluded that the duplicated messages are sent on the following lines:

```
case MQTTPublish:
   DDLogInfo(@"[MQTTSession] resend PUBLISH %@ | topic:%@", flow.messageId);
   message = [MQTTMessage publishMessageWithData:flow.data
                                         onTopic:flow.topic
                                             qos:[flow.qosLevel intValue]
                                           msgId:[flow.messageId intValue]
                                      retainFlag:[flow.retainedFlag boolValue]
                                         dupFlag:YES];

   if ([self encode:message]) {
       flow.deadline = [NSDate dateWithTimeIntervalSinceNow:DUPTIMEOUT];
       [self.persistence sync];
   }
   break;
```

We would like to know if anyone was able to replicate this behaviour on similar network conditions.

From VernMQ logs we can see that our client is sending 2x `PUBLISH` for the same message.
Any help would be great.

Thanks in advance

We're using VerneMQ Broker and MQTTClient `0.7.9`.

**Comment by ckrey** [comment]
`MQTTQosLevelExactlyOnce` QoS level tries to ensure one time delivery from and end-to-end view.

Retransmission between client and broker are part of the protocol.

In the `MQTTQosLevelExactlyOnce` flow  `PUBACK` is not used, but there is a handshake of

```
--> PUBLISH
<-- PUBREC
--> PUBREL
<-- PUBCOMP
```

The code you quoted above is retransmitting the message with the `DUP` flag set because the `PUBREC`message was not received within 20 seconds. 

> If the DUP flag is set to 0, it indicates that this is the first occasion that the Client or Server has attempted to send this MQTT PUBLISH Packet. If the DUP flag is set to 1, it indicates that this might be re-delivery of an earlier attempt to send the Packet.
> The DUP flag MUST be set to 1 by the Client or Server when it attempts when it attempts to re-deliver a PUBLISH Packet [MQTT-3.3.1.-1].

@dergraf can I do anything to track down this problem between MQTTClient and verneMQ?

**Comment by testark** [comment]
@ckrey we are facing a similar problem using QoS 1. Published messages are correctly `PUBACK`ed by VerneMQ and the client receives this `PUBACK` (we made some sniffing both client- and server-side). However, even these `PUBACK`ed messages are being re-`PUBLISH`ed by your client after ~20s. Could you please have a look at this?

**Comment by ckrey** [comment]
Does this happen in a congested situation e.g. client is flooded with retained or queued messages?

**Comment by testark** [comment]
@ckrey no retained messages are being sent / received. As for queued messages, we are sending, say, two messages per second. The client is connected to an isolated VerneMQ node (no other clients are connected).

**Comment by ckrey** [comment]
can you share some of your sniffed data with me?

**Comment by testark** [comment]
@ckrey yes. Please allow me 15m or so.

**Comment by ckrey** [comment]
np

**Comment by testark** [comment]
@ckrey https://gist.github.com/testark/5a3f7767ce9b41a5b3adb8d8890b6475. I had to edit payloads and topics which cannot be disclosed, so packet lengths will seem not to match. If you absolutely need the full version please let me know.

**Comment by ckrey** [comment]
I see what you see.

Where was that log taken? Close to the broker (10.39.10.160) or at the client (172.18.2.28)?

There is a time gap of 140 seconds between the first and second PUBLISH. Was the client off-line during this time? Is it possible that the messages 2...8 were sent from the client earlier than received at the point where the log was taken.

Do you have logical timestamps in the payload?

**Comment by testark** [comment]
> Where was that log taken? Close to the broker (10.39.10.160) or at the client (172.18.2.28)?
This log was taken close to the broker. But we've captured another close to the client at the same time for comparison. Do you need it?

> Was the client off-line during this time?
No, always online.

> Do you have logical timestamps in the payload?
I may be able to extract from some other logs (but not in the form of a packet capture). Do you need them?

**Comment by ckrey** [comment]
Yes, let me view the capture taken close to the client, please.

**Comment by testark** [comment]
@ckrey OK, please allow me for 15m, give or take.

**Comment by testark** [comment]
@ckrey https://gist.github.com/testark/20891a2a7d0f50a27f8a22ea7df34605.

**Comment by ckrey** [comment]
Thanks, unfortunately, the first message (Message ID 2) is missing in that capture...

Sorry, I cannot see any reason for the retransmission in the capture.

What happens after the time you captured, do the retransmissions continue or is it a startup problem?

If you have a log saying when the messages were generated on the client, it might give a hint.

**Comment by testark** [comment]
> Sorry, I cannot see any reason for the retransmission in the capture.

So, how do we go about debugging this?

> If you have a log saying when the messages were generated on the client, it might give a hint.

Messages are being generated immediately before being sent. Do you need any client logs?

**Comment by testark** [comment]
We'll now inject timestamps from the client on the messages being sent, maybe that will be helpful.

**Comment by ckrey** [comment]
yes, this may help

**Comment by testark** [comment]
We can confirm that messages are being retransmitted even though they are correctly `PUBACK`ed. We've injected timestamps and we can confirm that the creation timestamp stays the same across retransmitted packets. What else can we do?

**Comment by testark** [comment]
@ckrey please have a look at this new capture: https://gist.github.com/testark/e93288854a3a44ae1d8f85b09676a779.

**Comment by ckrey** [comment]
You can switch on detailed log in MQTTLog.h
```
        #ifdef DEBUG
            static const DDLogLevel ddLogLevel = DDLogLevelWarning;
        #else
```
to
```
            static const DDLogLevel ddLogLevel = DDLogLevelVerbose;
```

**Comment by testark** [comment]
@ckrey we'll be sending you these verbose logs in a minute.

**Comment by testark** [comment]
@ckrey here are the logs: https://gist.github.com/testark/c52bbe55ca5743862172eb8d8a4f5221.

**Comment by ckrey** [comment]
The problem is that the messages are sent in a background thread, while MQTTsession runs in the main thread.
This causes the the list of ACKs to wait for being written to disk after the ACK is actually received.
When they are eventually written, MQTTsession picks them up and retransmits the message.

As all the MQTTsession methods are nonblocking, could you perform publish on the main thread?

**Comment by testark** [comment]
> As all the MQTTsession methods are nonblocking, could you perform publish on the main thread?

This seems to solve the problem! Many thanks!

**Comment by ckrey** [comment]
Thanks to the power of OSS!

**Comment by crsantos** [comment]
Many thanks @ckrey! 🎉 
That was the problem! 
Thanks for your time

**Comment by Nododo** [comment]
> > As all the MQTTsession methods are nonblocking, could you perform publish on the main thread?
> 
> This seems to solve the problem! Many thanks!

i meet the same problem
can you show the detail code?
thank you~
