### ISSUE TITLE
mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain Code=-9836

### ISSUE THREAD

**Issue by cnzlh** [ckrey/MQTT-Client-Framework#170]
server log:
1467857490: OpenSSL Error: error:1408F10B:SSL 
routines:SSL3_GET_RECORD:wrong version number
1467857490: Socket error on client a590a147907a4c76acfb5c5eaf35b949, 

client log:
 mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain Code=-9836 "(null)"

please help

**Comment by ckrey** [comment]
-9836 means "A bad protocol version was encountered"

What iOS (tvOS, macOS) version are you running. What is your broker, which TLS version?

**Comment by ckrey** [comment]
Does this error relate to your questions in #168 and #161 ?

**Comment by cnzlh** [comment]
I'm use iOS 9.3.2, most of time when I first connected to mosquito it was successful. and when I reconnect or enter background then enter forceground Error response as 
mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain Code=-9836
the mosquito didn't set the TLS version. and I set TLS version follow the instructions from the http://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9 . but is didn't work
