### ISSUE TITLE
MQTTSessionErrorConnectionRefused isn't called?

### ISSUE THREAD

**Issue by magavelis** [ckrey/MQTT-Client-Framework#171]
In my current implementation i using MQTTSessionErrorConnectionRefused event to update MQTT client data before reconnecting to MQTT session again. Everything worked just fine, until I updated MQTT client to newest version.
In current version this event doesn't arrive... I tried to debug and I have saw that [MQTTSession error:(MQTTSessionEvent)eventCode error:(NSError *)error] is called with MQTTSessionEventConnectionClosedByBroker eventCode and it should generate an error if connectHandler is used, but i'm not using it. So how should I receive this error to know, that my connection was refused, because of wrong connection parameters?

**Comment by ckrey** [comment]
Can you show me some debug output?
