### ISSUE TITLE
Hi, ckrey How to user MQTT-Client-Framework over websocket??? any example? I need your help!😥  Thank you！

### ISSUE THREAD

**Issue by ganjmeng** [ckrey/MQTT-Client-Framework#172]
Hi, ckrey
How to user MQTT-Client-Framework over websocket??? any example? I need your help!😥

Thank you！

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/16648385/55f1aab2-4466-11e6-9a20-eb737f15ccaa.png)

![image](https://cloud.githubusercontent.com/assets/12026835/16648358/379dddec-4466-11e6-9da3-2d4d1fa39549.png)

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/16648485/da6a1e14-4466-11e6-9280-01dedb2f3612.png)

**Comment by ckrey** [comment]
In the 2nd example you are not using MQTTWebsocketTransport, but MQTTCFSocketTransport (plain MQTT)

If you could open plain MQTT on port 9999 it is not likely that you can connect to the same port with websocket.

Are you sure your server's websocket port is 9999?

**Comment by ganjmeng** [comment]
I had solve the problem!  ,The correct port is 9998.😓😓😓😓

Thank your very much!!!👌🏻
