### ISSUE TITLE
I try to connect my server, response connection closed.

### ISSUE THREAD

**Issue by sudotamm** [ckrey/MQTT-Client-Framework#175]
I try to connect my server 120.24.236.253, port is 1883, you can open 120.24.236.253:8080 with browser, response "connection closed". But my android client with java can connect succeed. Can't understand the reason. Please help to test that server, thanks.

**Comment by ckrey** [comment]
Which parameters do you use when you create MQTTSession?

**Comment by sudotamm** [comment]
I use mqtt protocol 3.1.1 to connect and response connection closed.

It is ok if I connect broker with Mqtt protocol 3.1

发自我的 iPhone

**Comment by xtreme8210** [comment]
Hi Sudotamm, 

I resolved my problem my adding 
`self.session.protocolLevel = MQTTProtocolVersion31;`
or
`self.session.protocolLevel = MQTTProtocolVersion311;`
