### ISSUE TITLE
弱网络环境下，connectionClosed不触发。Weak network environment, connectionClosed does not trigger.

### ISSUE THREAD

**Issue by CoderTaoX** [ckrey/MQTT-Client-Framework#179]
在网络环境弱（服务器与前端运营商不同）的情况下，- (void)connectionClosed:(MQTTSession *)session方法出发时间超长，服务器端已经掉线，前端不提示掉线，请问应该用什么方法坚挺mqtt断线？

In weak environment of network server and front-end operators of different case. - (void) connectionClosed: (MQTTSession *) session method of over long periods of time, the server has been dropped, and the front end does not prompt dropped, excuse me should do strong broken mqtt?

**Comment by ogres** [comment]
What duration do you use for `keepAlive` ?
