### ISSUE TITLE
Connection getting closed - [MQTT detected framing error "ip address"-> "ip address"  for connection protocol_header_corrupt]

### ISSUE THREAD

**Issue by shyamjimishra1993** [ckrey/MQTT-Client-Framework#180]
Added observer over sessionManager's state key and trying to connect as follows- 

 [self.manager connectTo:"Our server ip" port:1883  tls:false keepalive:60 clean:true auth:false user:nil pass:nil will:false willTopic:@"a/b" willMsg:[@"offline" dataUsingEncoding:NSUTF8StringEncoding] willQos:MQTTQosLevelAtLeastOnce willRetainFlag:false withClientId:@"Test123"] ; 

// Tried all possible combination of values for connectTo method

While using broker "broker.mqttdashboard.com" it is working fine and able to do all the things but while trying with our own rabbitMQ instance running on amazon, i am not able to connect to broker.(i verified port and ip address]

session manager state goes like:-
"Connecting"
"closed"
"Not Connected"

"Connecting"
"closed"
"Not Connected"
 tried reconnecting it also when it comes to closed state. Did not work.

**Asked server team to look into logs, got following error.

=INFO REPORT==== 22-Jul-2016::09:29:52 ===
accepting MQTT connection ("ip address"-> "ip address")
 
=ERROR REPORT==== 22-Jul-2016::09:29:52 ===
MQTT detected framing error "ip address"-> "ip address"  for connection protocol_header_corrupt**

**Able to hit our rabbit MQ broker server from sample applications available on app store and android team is also able to hit our server.**

server team is running Rabbit MQ instance on amazon deployment server.

Don't know what to do. Tried all the way, but could not make it possible. Kindly help me.Thanks in advance.

**Comment by ckrey** [comment]
When you specify willTopic, willMsg or willQos > 0 you have to say will:true, otherwise the server will detect "protocol_header_corrupt" and close the connection

**Comment by shyamjimishra1993** [comment]
Tried with will : true also. Did not work. Any way i tried all possible combination also. Same is working for server "broker.mqttdashboard.com".
Getting same error on server side: 
MQTT detected framing error "ip address"-> "ip address" for connection protocol_header_corrupt

Please help me. Already spent so much time on this issue.
is it something that this library does not support Rabbit MQ Broker?

**Comment by ckrey** [comment]
No, Rabbit MQ works well

**Comment by ckrey** [comment]
Is it possible that your Rabbit MQ does only accept MQTT3.1 messages, not MQTT3.1.1? MQTTSessionManager uses MQTT3.1.1.

You can use the alternative method to specify the protocolLevel
```

MQTTMessage.h:    MQTTProtocolVersion31 = 3,
MQTTMessage.h:    MQTTProtocolVersion311 = 4

- (void)connectTo:(NSString *)host
             port:(NSInteger)port
              tls:(BOOL)tls
        keepalive:(NSInteger)keepalive
            clean:(BOOL)clean
             auth:(BOOL)auth
             user:(NSString *)user
             pass:(NSString *)pass
             will:(BOOL)will
        willTopic:(NSString *)willTopic
          willMsg:(NSData *)willMsg
          willQos:(MQTTQosLevel)willQos
   willRetainFlag:(BOOL)willRetainFlag
     withClientId:(NSString *)clientId
   securityPolicy:(MQTTSSLSecurityPolicy *)securityPolicy
     certificates:(NSArray *)certificates
    protocolLevel:(MQTTProtocolVersion)protocolLevel;
```

**Comment by shyamjimishra1993** [comment]
Providing prototype level , it is working fine.
Thanks a lot.
