### ISSUE TITLE
Sample for Offline Message Buffering available?

### ISSUE THREAD

**Issue by gerdwatmann** [ckrey/MQTT-Client-Framework#182]
Hi all,

this is more of a question than an issue.

I am searching for a sample / test with the MQTT Client Framework that leverages offline message buffering. Anything available that shows how to initialize the session and publish the data for such a scenario? Thanks a lot for any pointer.

With kind regards
Gerd

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
