### ISSUE TITLE
 newMessage

### ISSUE THREAD

**Issue by wangchaochaoc** [ckrey/MQTT-Client-Framework#183]
- (void)newMessage:(MQTTSession *)session data:(NSData*)data onTopic:(NSString*)topic qos:(MQTTQosLevel)qos retained:(BOOL)retained mid:(unsignedint)mid   

This method has no call， delegate is set up，so  it  is why

**Comment by ckrey** [comment]
maybe because your connect did not go through or your subscribe did not succeed or you don't have read priviledges on the broker for the requested topic.
