### ISSUE TITLE
MQTT : Waiting For Acknowledgement

### ISSUE THREAD

**Issue by Chintanp038** [ckrey/MQTT-Client-Framework#184]
Hello All,

We are working on the MQTT. Subscribe the the packet on mac address as topic.
I have two confusion:
1> We subscribe the packet on the topic sometime working fine but after sometime it shows waiting for the acknowledgement   continuously.
2> Subscribe time more

So how we bug fix..need help

**Comment by OmidID** [comment]
this is how you can fix your problem
https://github.com/ckrey/MQTT-Client-Framework/pull/174/commits/81bb25c5dcd47acc794eb488b2d68768bbf0d016

@ckrey did you take a look to my file?
Currently we have a problem when we want to use pod still the old code we will receive and again we should update the code manually.
I hope the code it will be accept by you. 🙂
Thanks for your great job

**Comment by ckrey** [comment]
#174 is merged, closing the issue now
