### ISSUE TITLE
On fast subscribe and unsubscribe app stucks

### ISSUE THREAD

**Issue by Abhishek9634** [ckrey/MQTT-Client-Framework#186]
Neither it crashes but it stops and nothing happen furthur
Also thread bad acess to NSInteger outflow

**Comment by ckrey** [comment]
As all api calls are non-blocking except the ...AndWait methods, you can run all calls in the same theead as the one you created the MQTTsession in

**Comment by ckrey** [comment]
Did this help you?

**Comment by Abhishek9634** [comment]
Currently i reduced my calls and using old MQTT version

**Comment by Divjyot** [comment]
iOS 10 Crash @ [self.subscribeHandlers removeObjectForKey:@(mid)];  MQTTSession EXE_BAD_ACCESS while subscribing to topics starting point at [session subscribeToTopic:topicString atLevel:MQTTQosLevelAtMostOnce];
