### ISSUE TITLE
Application extensions is not supported

### ISSUE THREAD

**Issue by YehonatanVonage** [ckrey/MQTT-Client-Framework#188]
I'm trying to use the MQTT client framework as part of the iOS application extension, but the extension is not compiling cause the class UIApplication is not supported for extensions target.

The class MQTTSessionManager contains several times the phrase "[UIApplication sharedApplication]":
[[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:...];
[[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];

Please advise

**Comment by ckrey** [comment]
MQTTSessionManager is not supposed to work in an extension.

I haven't tried, but I am unsure if MQTTSession will work in an extension because of the lifecycle of an extension.
I used it in the main app and shared the data with the extension.

What are you trying to achieve?

**Comment by YehonatanVonage** [comment]
We use the MQTT pod as part of one of our infrastructure pods, which we use in our application (The pod is responsible for passing messages between two instances of our application). We need to use it in the application layer, but also in one of our iOS extensions. It is very hard to separate the MQTT to another pod, cause of dependencies. 

The methods "beginBackgroundTaskWithExpirationHandler" and "endBackgroundTask", are methods of an application layer, but the MQTT library needs to be handled as a network layer, so those methods shouldn't be used in the pod.
 
Is there a way to work around this?

Thanks

**Comment by ckrey** [comment]
As I already said, use MQTTSession instead of MQTTSessionManager and implement your own re-connect and lifecycle handling methods. You may use the source of MQTTSessionManager as a blueprint.

MQTTSessionManager needs to handle Background events because iOS stops TCP networking when the app goes into background

**Comment by YehonatanVonage** [comment]
I don't use the MQTTSessionManager in my code, but when getting the pod, I get also this class. The fact that it appears in the source files prevents from the iOS extension to compile. 

Can you make one more subspec that disables the import of this "lifecycle class" (MQTTSessionManager)?

**Comment by ckrey** [comment]
yes, good idea. will do

**Comment by ckrey** [comment]
please try with version `0.8.0` and the subspec `MQTTClient/Min`instead of the `MQTTClient`

**Comment by byliling** [comment]
I met the same question. Do you have any solutions?

**Comment by YehonatanVonage** [comment]
@byliling, there are several subspecs created for this library, choose the one that is relevant for you in your code. Information about subspecs:
http://www.dbotha.com/2014/12/04/optional-cocoapod-dependencies/
