### ISSUE TITLE
Error when calling unsubscribeAndWaitTopic inside MQTTSessionDelegate method newMessage

### ISSUE THREAD

**Issue by gianluca-venturini** [ckrey/MQTT-Client-Framework#19]
Hi,

I've an error that cause the disconnection of the MQTT client when I call unsubscribeAndWaitTopic inside the callback newMessage. The problem is due to the fact that in MQTTDecoder class the delegate method is called before resetting dataBuffer and status (MQTTDecoder.m:134).
```
[self.delegate decoder:self newMessage:msg];
self.dataBuffer = NULL;
self.status = MQTTDecoderStatusDecodingHeader;
```
 In order to solve the bug I suggest to switch the instructions order in this way, it worked for me:
```
self.dataBuffer = NULL;
self.status = MQTTDecoderStatusDecodingHeader;
[self.delegate decoder:self newMessage:msg];
```
Is it a good solution for the bug or are there better ways for solve it?

**Comment by ckrey** [comment]
@gianluca-venturini,

while the change you suggested may work in your environment, I do not recommend calling MQTT methods from the delegate (callback) methods directly.

I suggest you queue your desired action from the newMessage callback method and do the unsubscribe in there.

```
    [self performSelector:@selector(unsubscribeFromMyTopics:) withObject:info afterDelay:0];
```

**Comment by ckrey** [comment]
@gianluca-venturini did this work for you?

**Comment by gianluca-venturini** [comment]
In the final version of my code I left my solution because it works just fine for my purpose, I totally agree with you, your's more elegant and for sure will work better in general but I didn't tested yet (it's been a while that I don't work on that project).

Thank you very much for the assistance.
