### ISSUE TITLE
Error when connect with wss://

### ISSUE THREAD

**Issue by shutendoji-evan** [ckrey/MQTT-Client-Framework#190]
I got 6478: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-758.5.3/Foundation/NSURLProtocol.mm:182)
error when using wss:// link from aws iot

**Comment by ckrey** [comment]
you need to specify the hostname, port, ssl and either use MQTTCFTransport or MQTTWebSocketTransport. URLs like "wss://host:port" do not work!
