### ISSUE TITLE
Connect to test.mosquito.org got "SSLHandshake failed -9828" by using TLS

### ISSUE THREAD

**Issue by Tuzr** [ckrey/MQTT-Client-Framework#191]
Actually, I want to using TLS to connect to my own broker.

I already have my own .cer and .p12 file.

At first, I referenced the code on MQTTTestSessionManager.

And I used the **mosquitto.org.cer** and **KreyChristoph.p12** as certificate.

But when I connect to test.mosquitto.org , the log show 

> CFNetwork SSLHandshake failed (-9828)

Is that certificate expired? I just want to verify my code is correct by using that.

By the way, how to enable the DDLogVerbose(any other)? I see it in the code,but not show when execute.
Forgive me, It's a stupid question, but I really don't know how to enable it.

My code is below:

        MQTTSSLSecurityPolicy *securityPolicy = [MQTTSSLSecurityPolicy new];
        NSString *cerPath = [[NSBundle bundleForClass:[MQTTManager class]] pathForResource:@"mosquitto.org" ofType:@"cer"];

        if(cerPath) {
            NSData *certificateData = [NSData dataWithContentsOfFile:cerPath];
            if (certificateData) {
                securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeCertificate];
                securityPolicy.pinnedCertificates = [[NSArray alloc] initWithObjects:certificateData, nil];
            }
        }else{
            securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeNone];
        }
        
        securityPolicy.allowInvalidCertificates = YES;
        securityPolicy.validatesDomainName = NO;           //Default: YES
        securityPolicy.validatesCertificateChain = NO;     //Default: YES
        
        NSString *p12Path = [[NSBundle bundleForClass:[MQTTManager class]] pathForResource:@"KreyChristoph" ofType:@"p12"];
        
        NSArray *clientCerts = nil;
        if(p12Path) {
            clientCerts = [MQTTCFSocketTransport clientCertsFromP12:p12Path passphrase:@"abcde"];
        }
        
        [_mqttSessionManager connectTo:HOST port:PORT tls:YES keepalive:60 clean:YES auth:NO user:nil pass:nil will:NO willTopic:nil willMsg:nil willQos:MQTTQosLevelAtMostOnce willRetainFlag:NO withClientId:nil securityPolicy:securityPolicy certificates:clientCerts];

**Comment by ckrey** [comment]
To enable logging change line 19 in MQTTlog.h

![bildschirmfoto 2016-08-18 um 13 11 48](https://cloud.githubusercontent.com/assets/4027289/17771781/5957068e-6545-11e6-9cd4-01cad7a4cf92.png)

**Comment by ckrey** [comment]
It is possible that the .cer and .p12 file have expired. I will check later when I am back at my desk

**Comment by Tuzr** [comment]
@ckrey Thanks !

**Comment by ckrey** [comment]
-9828 means `errSSLPeerCertExpired`. My certificate expired. Removing from the repo.
Functionality is still in and works

**Comment by Tuzr** [comment]
Excuse me, I have another question about the certificate.
I have another MQTT app in Android, 
how can I get the certificate(.bks) to connect to "test.mosquito.org"?

And I want to convert your "mosquito.org.cer" to .bks , but it request password.
Thanks for your help!

**Comment by ckrey** [comment]
The website where you can download the ca certificate for the self signed certificate of for test.mosquitto.org:8883 is down (http://test.mosquitto.org) - I cannot help you in that matter.

**Comment by Tuzr** [comment]
@ckrey Thanks! Finally, I  connect to my mqtt server successfully.
