### ISSUE TITLE
MQTTClient processes streams sync on the main thread 

### ISSUE THREAD

**Issue by DanielMandea** [ckrey/MQTT-Client-Framework#193]
I have a issue when receiving a huge amount of data. Realized that all streams processing is handled on main thread and mainRunLop even though is initialized properly. 
 
`self.runLoop = [NSRunLoop currentRunLoop];
  self.runLoopMode = NSRunLoopCommonModes;`

Please check MQTTDecoder and MQTTSocketDecoder:

`- (void)stream:(NSStream*)sender handleEvent:(NSStreamEvent)eventCode`

Due to all of this processing, ui freezes. 
I have tried multiple ways of moving all streams processing on a background thread but with no success.
Is there any designated way of doing this. 
It would be a huge improvement for my app if this would be possible.

**Comment by ckrey** [comment]
If you create the session in a separate thread all is executed there

**Comment by ckrey** [comment]
see examples here https://github.com/ckrey/MQTT-Client-Framework

**Comment by ckrey** [comment]
sorry here: https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/MQTTTestMultiThreading.m

**Comment by DanielMandea** [comment]
Thanks, I will keep you updated with my progress

**Comment by DanielMandea** [comment]
So I succeeded to make it run on a an other thread by creating the session on a separate thread. 
But i have a problem is that i don't know how should i call subscribe / publish /. 
Should i call this async, the problem is that at some point i don't receive anything of after first publish i receive a message but after the second publish i don't receive anything back.
Do I miss something ?
My code looks like this: 

`
// I have this in some singletone class that handles mqtt stuff
- (void)runMQTT {
   // Run this on a sequential queue  
   dispatch_async(self.mqttQueue, ^{
      NSThread *thread = [[NSThread alloc] initWithTarget:self selector:@selector(runAsync:) object:nil];
       [thread start];
       [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:10]];
  });
}
- (void) runAsync {
      [self createMQTTSession];
      [self connectMQTTSession];
      while (self.event == -1) {
          [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1]];
     }

    if (self.session.status == MQTTSessionStatusConnected) {
       // Subscribe 
        [self subscribeToTopics:self.topics];
        while (test.event == -1) {
            //DDLogVerbose(@"%@ waiting for suback", test.session.clientId);
            [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1]];
        }

       // Publish 
        [self  publish:self.topic
           payload:self.testpaylod
           retained:self.testretained
                   qos:self.testquos];

        while (test.event == -1) {
            //DDLogVerbose(@"%@ waiting for puback", test.session.clientId);
            [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1]];
        }
    }
}

- (void)createMQTTSession {
        self.mqttSession = [[MQTTSession alloc] init];
        self.mqttSession.cleanSessionFlag = NO;
        self.mqttSession.protocolLevel    = MQTTProtocolVersion311;
        self.mqttSession.delegate         = self;
        self.mqttSession.keepAliveInterval = 60;
        self.mqttSession.clientId  = self.clientID;

       // Transport 
       self.transport.host = server;
       self.transport.port = port.integerValue;
       self.transport.tls = YES;
       self.mqttSession.transport = self.transport;
}

- (void)connectMQTTSession {
       self.event = -1;
       [ self.mqttSession connectWithConnectHandler:^(NSError *error) {
           if (self.mqttSession .status != MQTTSessionStatusConnected || error) {
               // Check if connected  some log 
          }
      }];
}

- (void)subscribeToTopics:(NSDictionary<NSString *, NSNumber *> * _Nonnull)topics {
    self.event = -1;
    [self.mqttSession  subscribeToTopics:topics];
}

- (void)publish:(NSString * _Nonnull)topic
           payload:(NSString * _Nonnull)payload
           retained:(BOOL)retained
                   qos:(NSInteger)qos {
    self.event = -1;
    // Publish payload
    NSData *payloadData = [payload dataUsingEncoding:NSUTF8StringEncoding];
    [self.session publishData:payloadData onTopic:topic retain:retained qos:qos];
}

`

**Comment by DanielMandea** [comment]
@ckrey An other thing, after connection and receiving the first message something  is happening and The dump is not running anymore. Do you have a clue for me ... what should I do ?

**Comment by DanielMandea** [comment]
Hey guys, after long investigation i have successfully get MQTT to work on a background thread. 
There are few things that we should take into consideration 
1. Strong reference to the queue we are performing initialization on. 
`@property (nonatomic, strong, readwrite, nullable) dispatch_queue_t mqttQueue;`
2. Init the queue as a queue with a DISPATCH_QUEUE_PRIORITY_HIGH 
`_mqttQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, DISPATCH_QUEUE_SERIAL);`
3. Call MQTT setup (init, create session, connect) as follows 
```
- (void)connect {
    // BPBMQTTSession was set up only reconnect
    dispatch_async(self.mqttQueue, ^{
        NSRunLoop *loop = [NSRunLoop currentRunLoop];
        [self setupMQTT];
        [loop run]; // make sure that you have a running run-loop.
    });
}
```

**Comment by JohnHow0537** [comment]
@DanielMandea thx,solve my problem. I think i should study the runloop in depth, it confuse me sometimes
