### ISSUE TITLE
Progressing the connect on background thread

### ISSUE THREAD

**Issue by JohnHow0537** [ckrey/MQTT-Client-Framework#194]
i want my session run on  background thread,  I read the issue #193 , and i use the MQTTSessionManager , i write the following code , find it connect to the service successfully, but i can't receive any message when i subscribe a topic ,  did i subscribe the topic on the wrong thread? 
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

        self.manager = [MQTTSessionManager new];
        self.manager.delegate = self;
        
        [self.manager connectTo:@"test.c"
                           port:1883
                            tls:NO
                      keepalive:60
                          clean:YES
                           auth:YES
                           user:@"t_username"
                           pass:@"t_password"
                      willTopic:@"test"
                           will:[NSData data]
                        willQos:0
                 willRetainFlag:YES
                   withClientId:@"dsdsdsd"
         ];
        
        self.manager.subscriptions = @{@"test":@0};
        NSLog(@"%@",[NSThread currentThread]);
     });

**Comment by w3hacker** [comment]
把self.manager.subscriptions = @{@"test":@0};放到connectTo前面试试

**Comment by w3hacker** [comment]
看看我这个是为什么? #195

**Comment by JohnHow0537** [comment]
@w3hacker 不是这个问题

**Comment by DanielMandea** [comment]
@JohnHow0537 It's working only by moving 
`self.manager.subscriptions = @{@"test":@0};`
before 
` [self.manager connectTo:@"test.c"`
Thanks.

**Comment by JohnHow0537** [comment]
@DanielMandea I did it,but it don't work for me.

**Comment by DanielMandea** [comment]
@JohnHow0537 check https://github.com/ckrey/MQTT-Client-Framework/issues/193

**Comment by JohnHow0537** [comment]
see #193, thx to @DanielMandea
