### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=49 "Can't assign requested address" in LAN。

### ISSUE THREAD

**Issue by CoderTaoX** [ckrey/MQTT-Client-Framework#197]
The same code, one of the works in this problem, there is no problem in other projects.

`sessionManager = [[MQTTSessionManager alloc] init];
    MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
    NSLog(@"%@",MQTT_HOST);
    transport.host = MQTT_HOST;
    transport.port = MQTT_PORT;
    _session = [[MQTTSession alloc] initWithClientId:[RTXRemoveOwner owner]];
    _session.transport = transport;
    _session.willRetainFlag = YES;

```
_session.cleanSessionFlag = NO;
_session.willQoS = 2;
_session.keepAliveInterval = 25;
_session.delegate = self;
_session.protocolLevel = 4;`
```

**Comment by ckrey** [comment]
Does the HOSTname you use resilve to a valid address in your environment (you may check with Safari)
MQTTClient uses iOSs CFNetwork

**Comment by CoderTaoX** [comment]
The address is not working on safari

**Comment by CoderTaoX** [comment]
The server only supports IPv4, how should I set up?

**Comment by CoderTaoX** [comment]
But in another project I can connect, the same network environment, the same HOSTname.

**Comment by ckrey** [comment]
You are probably in an IPv6 only environment.

Are you specifiying a server name which is resolved via DNS or do you specify an IPv4 address as MQTT_HOST?

If you use DNS, you have to make sure you do not return an AAAA record for the name, but just an A record.

You may probably find everything you need here https://developer.apple.com/news/?id=05042016a

**Comment by ckrey** [comment]
@CoderTaoX did you solve the problem in the mean time?
