### ISSUE TITLE
Issue when using Carthage - builds the MQTTFramework scheme

### ISSUE THREAD

**Issue by ksachdeva** [ckrey/MQTT-Client-Framework#198]
Hi,

When I use Carthage as the dependency management tool I have few issues :

brew install carthage (in case you do not have it installed)

Content of cart file:
Github "ckrey/MQTT-Client-Framework"

Issue following commands in the same directory where you have the Cartfile

carthage bootstrap --no-build --platform "iOS"
carthage build --no-skip-current --platform "iOS"

This results in building the MQTTFramework scheme (which I believe is not correct !!)

```
$ carthage build --no-skip-current --platform "iOS"
*** xcodebuild output can be found in /var/folders/bd/dxr3714n6vn6cws2x8dh3t200000gn/T/carthage-xcodebuild.f3p8sk.log
*** Building scheme "MQTTFramework" in MQTTClient.xcworkspace

```

Please suggest a workaround.

Regards & thanks
Kapil

**Comment by ckrey** [comment]
@eltonlivera was so kind to add carthage support in #128.

Unfortunately I personally have no experience with Carthage, but if the two of you come up with a fix / solution I would be happy to include the PR

**Comment by eltonlivera** [comment]
Marking the scheme as shared in Xcode makes the framework Carthage compatible. Added this change in #210 
![xcode-share-scheme](https://cloud.githubusercontent.com/assets/3668466/19016071/6555dbd2-8808-11e6-9182-37fc040ecc0e.png)
