### ISSUE TITLE
Cannot build after CocoaLumberjack new release

### ISSUE THREAD

**Issue by wenxin3262** [ckrey/MQTT-Client-Framework#199]
Xcode shows LOG_ASYNC_SOMETHING_FLAG not found.
I fixed it by fork and change line 46 to `s.dependency = 'CocoaLumberjack', '2.2.0'` in podspec.
But I'd rather like a complete removal of CocoaLumberjack in pod dependency.

**Comment by ckrey** [comment]
There is already a provision for compiling w/o CocoaLumberjack.
I updated the podspec, so you can use subspec `minNSLog` instead of `min`, but this is not the default.
Will become available in next version

**Comment by Raymond26** [comment]
How do you compile without CocoaLumberjack?

**Comment by wenxin3262** [comment]
I don't see `minNSLog` subspec?

**Comment by sonysum** [comment]
where is line 46?

**Comment by wenxin3262** [comment]
@sonysum in `podspec`

**Comment by ckrey** [comment]
I will upload 0.8.3, with minNSLog and a reference to CocoaLumberjack 2.3.x at maximum

**Comment by ckrey** [comment]
By default, the dependency to CocoaLumberjack is removed.

If you want to include CocoaLumberjack, specify 
```
pod 'MQTTClient/WithLumberjack'
```
in your Podfile

**Comment by crsantos** [comment]
I have a doubt, why are you forcing `CocoaLumberJack` `2.3` and not `3.0.0`?

**Comment by ckrey** [comment]
Because CocoaLumberjack 3.0.0 was broken see initial issue

```
Xcode shows LOG_ASYNC_SOMETHING_FLAG not found.
```

**Comment by crsantos** [comment]
Thanks @ckrey ;)

**Comment by crsantos** [comment]
Weird thing is... I can't find that `LOG_ASYNC_SOMETHING_FLAG` on this repo or on CocoaLumberjack..
@wenxin3262 where did you find that flag?
