### ISSUE TITLE
Swift tests fail with Swift3 / Xcode8

### ISSUE THREAD

**Issue by ckrey** [ckrey/MQTT-Client-Framework#202]
Swift help required

**Comment by ogres** [comment]
Hello Christoph,

I have updated the MQTTSwift project and its now building/running,
I will go through "SwiftTests.swift" file inside MQTTClientTests

**Comment by ckrey** [comment]
Thanks Sergo, very appreciated. You made my day!

**Comment by ogres** [comment]
Tests also run with Swift3/Xcode 8 now

**Comment by ckrey** [comment]
👍
