### ISSUE TITLE
MQTTSessionManager lastErrorCode set too late?

### ISSUE THREAD

**Issue by delitestudio** [ckrey/MQTT-Client-Framework#203]
When an error occurs these instructions are executed:

```
self.state = MQTTSessionManagerStateError;
self.lastErrorCode = error;
```

However, since you recommend using the observers on MQTTSessionManager.state, in my opinion they should be reversed in this way:

```
self.lastErrorCode = error;
self.state = MQTTSessionManagerStateError;
```

Otherwise in the observer we will never know what was the error that occurred. What do you think?

Thanks!

**Comment by ckrey** [comment]
updated and uploaded to repo.

**Comment by delitestudio** [comment]
Great, thanks!
