### ISSUE TITLE
Random crash in MQTTDecoder.m

### ISSUE THREAD

**Issue by adarshmishra** [ckrey/MQTT-Client-Framework#207]
We are getting crashes sometime in MQTTDecoder.m. Need help in debugging the root cause.

![screen shot 2016-09-29 at 5 12 56 pm](https://cloud.githubusercontent.com/assets/5002214/18952702/799ce3ca-8668-11e6-9f0a-6d1c0b7b33d7.png)

**Comment by adarshmishra** [comment]
@ckrey , any suggestions, what is causing this. We observer that this happens, when app is in background for longer time.

**Comment by ckrey** [comment]
Are you aware of the fact that iOS kills the app after some time in the background?

How are you keeping the app running? (Background Modes)

If you don't keep it running, you have to DISCONNECT the MQTT connection when you iOS tells your app it will be terminated. Have a look at the example in MQTTSessionManager.m

**Comment by adarshmishra** [comment]
Sorry for my earlier comment, it is happening when app is in foreground and kept for some duration. We are closing connection as soon as app is going to background and connecting when it appears to foreground.

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
