### ISSUE TITLE
App crashes on [MQTTDecoder stream:handleEvent:] method dring reconnecting

### ISSUE THREAD

**Issue by govindprasadgupta** [ckrey/MQTT-Client-Framework#21]
After removing an active connection, then I tired to establish a new connection again. (I did this process 3 to 4 time).

During connection app crashed at following method
- (void)stream:(NSStream*)sender handleEvent:(NSStreamEvent)eventCode

Line no: 77
while (self.status == MQTTDecoderStatusDecodingLength) {

**Comment by HiveHicks** [comment]
Same for me:

```
-[MQTTDecoder status]: message sent to deallocated instance 0x1792a380
```

**Comment by ckrey** [comment]
Please do make sure you `close`a connection before removing, Otherwise the eventhandler (which is no longer allocated) may get called from the underlying CFSocket/Stream.

**Comment by ckrey** [comment]
@HiveHicks @govindprasadgupta did my hint solve your problem?

**Comment by govindprasadgupta** [comment]
Thank you for your time and attention. Yes, this hint solved my issue.

**Comment by HiveHicks** [comment]
@ckrey I'm pretty sure that I only removed a connection in `connectionClosed:` delegate method. Anyway, I solved a problem by storing an array of used `MQTTSession` objects and adding sessions there from `connectionClosed:` method. I know it's a hack, but it works.

**Comment by bournean** [comment]
thanks, @HiveHicks @ckrey you guys' solution solved my issue. NO.1 crash issue ;)

**Comment by ithaqua** [comment]
can you provide a sample for this , thanks.
