### ISSUE TITLE
Will Message not working sometimes with MQTTSessionManager

### ISSUE THREAD

**Issue by wenxin3262** [ckrey/MQTT-Client-Framework#214]
```
        sessionManager.connect(to: mqttServer,
                               port: 1883,
                               tls: false,
                               keepalive: 10,
                               clean: true,
                               auth: false,
                               user: "",
                               pass: "",
                               will: true,
                               willTopic: lastWillTopic,
                               willMsg: lastWillMessage,
                               willQos: .atLeastOnce,
                               willRetainFlag: false,
                               withClientId: clientId)
```
My broker is working correctly. Will Message works all the time when using MQTTSession directly. But with the manager, will message is missing. Sub/Pub goes fine, and I didn't use persistence feature.
1. click home button to enter background, saw connection closed in the log, but will message never shows up.
2. terminate app directly, will message not working.
3. Now weird stuff is calling connect twice in a row like the code above, will message working when terminate the app.

**Comment by ckrey** [comment]
This is a feature, not a bug.

The MQTTSessionManager disconnects gracefully when the App is going to background.
According to the MQTT spec the will message is sent only if the broker detects a hard disconnect or if the ping message is not received (keepAlive interval).

**Comment by JakeSc** [comment]
@ckrey I noticed that `MQTTSessionManager` disconnects from the socket for `WillResignActive` events, and not `WillEnterBackground` events. This means that even for minor events like when the user opens the control panel, or when we pop a permissions dialog, the socket will be disconnected, even though the app remains on-screen. Would you consider changing this to disconnect for `WillEnterBackground` instead?

Would you accept a PR in which I add a BOOL flag to `SessionManager` like `disconnectsOnResginActive` to control this behavior?

**Comment by ckrey** [comment]
The enhancement is a bit off-topic. I created a separate issue for this
