### ISSUE TITLE
Reconnect MQTTSession

### ISSUE THREAD

**Issue by shyamjimishra1993** [ckrey/MQTT-Client-Framework#221]
Hi Christoph,

I am using **MQTTSession** class for MQTT connection and i am able to connect, subscribe and send data. Everything seems to work fine.

The only issue is i am not able to reconnect the connection once it is broken.
The connection is getting closed when Network goes / Sometime when app goes to background.
I am sure there is something to re-establish the connection but i am not getting that part. Kindly help me.

I downloaded sample code with code mentioned below- 

 manager!.connectToHost("xyz.com", port: 1883, usingSSL: false)
        while !sessionConnected && !sessionError {
            NSRunLoop.currentRunLoop().runUntilDate(NSDate(timeIntervalSinceNow: 1))
        }

Is this while loop related to Reconnection anyhow OR it is for some other purpose.

 I am quite new to IOS dev, It will be good if you can share some sample code for reconnection using MQTTSession class not the MQTTSessionManager. I got ways to reconnect using MQTTSessionManager but we are using MQTTSession class for MQTT connection. 

**So kindly guide us how to reconnect MQTT when network goes and comes again Or sometimes when app comes from background to foreground**
Thanks in advance.

**Comment by ckrey** [comment]
I would like to suggest to you to study what MQTTSessionManager does: https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSessionManager.m

The loop you quote above is just to simulate a synchron call. It just waits until you are connected or an error occurs.
In a real app, you will not wait, but handle the events asychronously.

In general to reconnect, you just call `session.connectTo` again.

**Comment by ckrey** [comment]
![bildschirmfoto 2016-10-17 um 15 22 08](https://cloud.githubusercontent.com/assets/4027289/19439175/7dfce1a4-947d-11e6-863d-913ac1b7bc9c.png)

**Comment by JakeSc** [comment]
Hey @ckrey, thanks for the guidance here. We're considering adopting this framework for a major MQTT investment in our app to improve syncing performance. I've been playing around with `MQTTSession` and `MQTTSessionManager` just to make sure I'm thinking about it in the right way, could you explain the conceptual purpose of `MQTTSessionManager` vs. `MQTTSession`? As I understand it, `SessionManager` is a wrapper around `Session` to manage reconnects. Is that correct?

Would you ever consider adding something like `didChangeState()` to the `SessionManagerDelegate` to propagate this information to consumers?

Thanks!

**Comment by JakeSc** [comment]
I just saw that `SessionManager.state` is KVO-observable. I think a delegate callback would be better design. Thoughts?

**Comment by ckrey** [comment]
I think both ways of implementing this have pros and cons.

The observable allows multiple consumers to watch state changes but it is a pain adding and removing the observer.

Yes, a delegate would add to the usability of MQTTManager.

**Comment by ckrey** [comment]
And I would accept a PR :smile:

**Comment by ckrey** [comment]
I think the proposed enhancement is a bit off topic here. Opening a separate issue for that
