### ISSUE TITLE
SSL connection: error 9831: no certificate returned

### ISSUE THREAD

**Issue by Reetalibrarian** [ckrey/MQTT-Client-Framework#225]
We surely can connect to the server if server is open for anyone without checking cert/key.
However, since we added SSL, I kept receiving handshake failed or no certificate returned

We require pinning Certificate to verify the server (not self-signed certificate) 
and use p12 client certificate to verify the client side from server

code:

```objective-c
    NSString *certificate = [[NSBundle mainBundle] pathForResource:@"server_cert" ofType:@"cer"];
    MQTTSSLSecurityPolicy *securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeCertificate];
    securityPolicy.pinnedCertificates = @[[NSData dataWithContentsOfFile:certificate]];
    securityPolicy.allowInvalidCertificates = NO;
    securityPolicy.validatesCertificateChain = NO;
    self.mqttSession = [[MQTTSession alloc]
                       initWithClientId:@"clientID"
                       userName:nil
                       password:nil
                       keepAlive:60
                       cleanSession:YES
                       will:NO
                       willTopic:nil
                       willMsg:nil
                       willQoS:2
                       willRetainFlag:NO
                       protocolLevel:4
                       runLoop:[NSRunLoop currentRunLoop]
                       forMode:NSRunLoopCommonModes
                       securityPolicy:securityPolicy
                       certificates:[MQTTCFSocketTransport clientCertsFromP12:[[NSBundle mainBundle] pathForResource:@"client_cert" ofType:@"p12"] passphrase:@"1234"]];
    self.mqttSession.delegate = self;
    [self.mqttSession connectToHost:SERVICE_HOST port:8883 usingSSL:YES connectHandler:^(NSError *error) {
        if (error) {
            NSLog(@"Error Connect %@", error.localizedDescription);
        } else {
            NSLog(@"Connected sessionPresent");
        }
    }];
 ```

Server log :
##### OpenSSL Error: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned

My Plist:

 ```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>server_address</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.2</string>
                <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
        </dict>
    </dict>
 ```
Server SSL version: TLS V1.2

Does anyone know what's going on here? 

update: 
openssl works fine with the following command
```
openssl s_client -connect server_address:8883 -cert <client_cert> -key <client_key> -keyform PEM -CAfile <root_ca_cert>
```

**Comment by jhaoheng** [comment]
#34 

check @bobwenx post will be ok.

1. `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt`
2. set the crt & key to emqttd.config
3. `openssl x509 -in server.crt -out server.pem -outform PEM` 
4. `openssl x509 -outform der -in server.pem -out server.der`
5. set server.der to MQTTSSLSecurityPolicy

**Comment by Reetalibrarian** [comment]
Update: 

I alternatively built up a mosquitto localhost to communicate with rather than directly using AWS server. I used self-signed Cafile and one client p12 certificate. (and also change a bit MQTTSSLSecurityPolicy.m in 
```
- (BOOL)evaluateServerTrust:(SecTrustRef)serverTrust
                  forDomain:(NSString *)domain
```
)

Things works well, I can publish message to localhost with SSL. 

However, I switch back to our AWS server, I still receive error 9831. and I got NSStreamEventErrorOccurred even before evaluateServerTrust. 

They have almost the same mosquitto.conf file except the file locations.

**Comment by ckrey** [comment]
For AWS you do not need any `server.cer`, because the CA AWS uses is known to iOS:

Here is what I did to setup AWS and connect via MQTT-Client:

```
#!/bin/sh
#
# http://docs.aws.amazon.com/iot/latest/developerguide/verify-pub-sub.html
#
pip install awscli
aws iot help
aws configure

aws iot create-thing --thing-name "MQTTClient"

aws iot create-keys-and-certificate --set-as-active
aws iot describe-certificate --certificate-id MYCERTIFICATE --output text --query certificateDescription.certificatePem > cert.pem
aws iot create-policy --policy-name "PubSubToAnyTopic" --policy-document file://policy
aws iot attach-principal-policy --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE" --policy-name "PubSubToAnyTopic"
aws iot attach-thing-principal --thing-name "MQTTClient" --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE"
aws iot describe-endpoint
mosquitto_sub --cafile rootCA.pem --cert cert.pem --key thing-private-key.pem -h A399VGY1YE9C5J.iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t topic/test -i clientid1
mosquitto_pub --cafile rootCA.pem --cert cert.pem --key thing-private-key.pem -h A399VGY1YE9C5J.iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t topic/test -i clientid2 -m "Hello, World"
openssl pkcs12 -in cert.pem -inkey thing-private-key.pem -out aws.p12 -export

aws iot create-thing --thing-name "owntracks"
aws iot attach-thing-principal --thing-name "owntracks" --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE"
```

**Comment by Reetalibrarian** [comment]
@ckrey  

We do not use AWS iot, we build a mosquitto server on AWS.
so we still can use server.cert, right?

**Comment by ckrey** [comment]
Sure

**Comment by ckrey** [comment]
can you connect to your AWS server with mosquitto_sub ?

**Comment by Reetalibrarian** [comment]
Yes, it works fine with mosquitto_sub & pub

**Comment by ckrey** [comment]
And the content of the ``--cafile rootCA.pem``` is the same you are using in the app as `server_cert.cer`?

**Comment by Reetalibrarian** [comment]
Yes, they are the same. 

We use cafile (rootCA.pem as you called) to generate all crt / key 
and this cafile also used as verify the server from app side.

**Comment by ckrey** [comment]
Are you using mosquitto on AWS with direct access from the internet or do you have an haproxy in front?

**Comment by ckrey** [comment]
Why and what?
> (and also change a bit MQTTSSLSecurityPolicy.m in

**Comment by Reetalibrarian** [comment]
first question: 
no, we don't have haproxy


second question: 
It seems like our single cer was divided into 2 object afterword in the array (serverCertificates), when it was call by evaluateServerTrust, 
```
NSUInteger trustedCertificateCount = 0;
            for (NSData *trustChainCertificate in serverCertificates) {
                if ([self.pinnedCertificates containsObject:trustChainCertificate]) {
                    trustedCertificateCount++;
                }
            }
```
it only got count 1 but not 2 , thus return NO in the following codes
```
return trustedCertificateCount == [serverCertificates count];
```



Thus I modified it to be 
```
NSUInteger trustedCertificateCount = 0;
            for (NSData *trustChainCertificate in serverCertificates) {
                if ([self.pinnedCertificates containsObject:trustChainCertificate]) {
                    trustedCertificateCount++;
                    return YES;
                }
            }

            return NO;
```

**Comment by Jerming** [comment]
@ckrey Are you going to solve issue #225 ? Or just ignore it ?

**Comment by ckrey** [comment]
@Jerming  I don't who you refer to when you write "we". Your identity is as obscured as the profile image you are using. I don't know if you and @Reetalibrarian work together.

With regards to your question:

This is not a commercial product, I am not sponsored by any organisation or company.

You logged an issue without giving not very much details 4 days ago. I tried to understand your issue 2 days after and now you mention for the first time you are using Digicert certificate. Maybe if you provide more information to me or make some code available to me where I can reproduce the problem, I can provide a fix, which I cannot at the moment.

If you continue harassing me verbally I would like to recommend to you using another MQTT library.

Otherwise I will consider any Pull Request from the user community.

**Comment by Jerming** [comment]
@ckrey My apologies.

**Comment by Reetalibrarian** [comment]
Update: 

We change the way of generate Key & certificate 
and now app can communicate with server without problem. 
We suspect that the old generator got some configs which are not compatible with iOS devices (we used Paho on android has no problem with it) 

Here is the original command generator 

```
CMD_NAME=$(basename $0)
DEVICE_NAME=$1
if [ -z "$DEVICE_NAME" ]; then
    echo "Usage: $CMD_NAME  DEVICE_NAME"
    exit 1
fi
DEVICENAME=$DEVICE_NAME \
openssl req -new -nodes\
    -config conf/device.conf \
    -out device_certs/$DEVICE_NAME.csr \
    -subj "/C=US/O=Candy House Inc/CN=$DEVICE_NAME" \
    -keyout device_certs/$DEVICE_NAME.key
openssl ca -batch \
    -config conf/device-signing-ca.conf \
    -in device_certs/$DEVICE_NAME.csr \
    -out device_certs/$DEVICE_NAME.cer
#    -extensions identity_reqext
openssl rsa -in device_certs/$DEVICE_NAME.key -out device_certs/$DEVICE_NAME.key
TMP=$(mktemp /tmp/temp.XXXX)
openssl x509 -in device_certs/$DEVICE_NAME.cer > $TMP
openssl x509 -in ca/device-signing-ca.crt >> $TMP
mv $TMP device_certs/$DEVICE_NAME.cer
```

And now we just use openSSL, and I works

```
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1024 -out ca.crt
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 100 -sha256
openssl genrsa -out client.key 2048
openssl req -new -key client.key -out client.csr
openssl x509 -req -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out client.crt -days 100 -sha256
```

Thank you everyone above who provides assistances.
