### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by ajitam** [ckrey/MQTT-Client-Framework#226]
Hi, I've implemented this library into my project but I'm noticing quit some delay in message RCV.

I tried different MQTT server but the result is the same. Is there so additional parameter I can tweak to get more "instant" connection?

The delay is sometimes even for ~5 sec

My current setup is as follows

```c++
MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
transport.host = MQTT_HOST;
transport.port = MQTT_PORT;
	
_session = [[MQTTSession alloc] init];
_session.transport = transport;
_session.userName = MQTT_USERNAME;
_session.password = MQTT_PASSWORD;
_session.clientId = MQTT_DEVICE;
_session.delegate = self;
[_session connectAndWaitTimeout:10];
	
[_session subscribeToTopic:@"/test-topic" atLevel:2 subscribeHandler:^(NSError *error, NSArray<NSNumber *> *gQoss){
  if (error) { /* ... */}
]; // this is part of the block API

/* RCV message
 */
- (void)newMessage:(MQTTSession *)session data:(NSData *)data onTopic:(NSString *)topic qos:(MQTTQosLevel)qos retained:(BOOL)retained mid:(unsigned int)mid
{ /*..*/ }
```

**Comment by ckrey** [comment]
can you specify   "quite some delay"?

Number of messages, size of messages, type of connection,...?

You are using QoS2, which means there is a double handshake between broker and client for each message. Do you need QoS2 for you app?

If you are receive lots of messages in QoS1 or QoS2, you can consider to change the properties maxMessages and maxWindowSize of MQTTtransport. If you reach these limits, messages are ignored until space is freed. You may adjust the maxWindowsSize in your broker too, to avoid flooding the clients.

**Comment by ajitam** [comment]
1. quite some delay = ~5 sec
2. I'm using QoS0

For some reason after writing this issue I ran the app again and it seems that today it's working 0K. 

Should I subscribe to topic `atLevel:0` ?

**Comment by ckrey** [comment]
atLevel:2 means QoS2

**Comment by ckrey** [comment]
Is your question answered? Close the issue?

**Comment by ajitam** [comment]
I've been using application whole day yesterday with no delay so I guess problem was somewhere else (maybe network).

Sorry for inconvenience.
