### ISSUE TITLE
How do I connect to the AWS IoT server?

### ISSUE THREAD

**Issue by Frozenleaf** [ckrey/MQTT-Client-Framework#229]
After searching through this board, I have done the creation of the p12 file. (Both with and without CA)
`$ openssl pkcs12 -in certificate.pem.crt -CAfile root-CA.pem -inkey private.pem.txt -out aws.p12 -export 
`

I am testing  the MQTTSwift project, the only code I have change is to enable the _usingSSL_ parameter.

```
let certificate = Bundle.main.path(forResource: "aws2", ofType: "p12")
print (certificate!)

newSession.certificates = MQTTCFSocketTransport.clientCerts(fromP12: certificate!, passphrase: "password")
        
newSession.connect(toHost: "a70viq66vsgn2.iot.us-east-1.amazonaws.com", port: 8883, usingSSL: true)

```

I have also enable the _NSAppTransportSecurity_ permission for SSL in the plist file.
```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>amazonaws.com</key>
            <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
            <key>amazonaws.com.cn</key>
            <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>

```
No matter what I do, I am constantly getting the **"CFNetwork SSLHandshake failed (-9825)"** error.

Hope someone has try this before...Thanks

**Comment by ckrey** [comment]
Here is what I did to setup AWS and connect via MQTT-Client, you only need the `.p12` file and passphrase

```
#!/bin/sh
#
# http://docs.aws.amazon.com/iot/latest/developerguide/verify-pub-sub.html
#
pip install awscli
aws iot help
aws configure

aws iot create-thing --thing-name "MQTTClient"

aws iot create-keys-and-certificate --set-as-active
aws iot describe-certificate --certificate-id MYCERTIFICATE --output text --query certificateDescription.certificatePem > cert.pem
aws iot create-policy --policy-name "PubSubToAnyTopic" --policy-document file://policy
aws iot attach-principal-policy --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE" --policy-name "PubSubToAnyTopic"
aws iot attach-thing-principal --thing-name "MQTTClient" --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE"
aws iot describe-endpoint
mosquitto_sub --cafile rootCA.pem --cert cert.pem --key thing-private-key.pem -h A399VGY1YE9C5J.iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t topic/test -i clientid1
mosquitto_pub --cafile rootCA.pem --cert cert.pem --key thing-private-key.pem -h A399VGY1YE9C5J.iot.us-east-1.amazonaws.com -p 8883 -q 1 -d -t topic/test -i clientid2 -m "Hello, World"
openssl pkcs12 -in cert.pem -inkey thing-private-key.pem -out aws.p12 -export

aws iot create-thing --thing-name "owntracks"
aws iot attach-thing-principal --thing-name "owntracks" --principal "arn:aws:iot:us-east-1:708534704324:cert/MYCERTIFICATE"
```

**Comment by Frozenleaf** [comment]
@ckrey Thanks for the Extremely fast response.

I have seen your above post in another thread on how to create the p12 file. But I am not too sure if I am missing something trivial in my code. (Totally new to swift)

What i have done is have a p12 file generated, add it into the Xcode Project and I added few lines of code into the Swift test app that you have included in the repository. In the end I am getting a "CFNetwork SSLHandshake failed (-9825)" error. A quick google search shows me that my p12 file is not correct.

Is this even correct?

```
let certificate = Bundle.main.path(forResource: "aws2", ofType: "p12")
newSession.certificates = MQTTCFSocketTransport.clientCerts(fromP12: certificate!, passphrase: "password")
```

I got the hint from your post on HiveMq [http://www.hivemq.com/blog/mqtt-client-library-encyclopedia-mqtt-client-framework] but unfortunately it is in Objective-C 

Thank you.

**Comment by ckrey** [comment]
I think it should be: 
```
MQTTCFSocketTransport.clientCertsFromP12(certificate!, passphrase: "password")
```

Please check if `newSession.certificates` is nil and if a warning/error was printed

**Comment by ckrey** [comment]
I don't think you need `NSAppTransportSecurity` in the .plist file

**Comment by Frozenleaf** [comment]
Yes I set it as per Amazon's documentation. And I have even bump it up to 1.2 min. 

```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>amazonaws.com</key>
            <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.2</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
            <key>amazonaws.com.cn</key>
            <dict>
                <key>NSThirdPartyExceptionMinimumTLSVersion</key>
                <string>TLSv1.2</string>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

But still no go... Right now, I am doing blind trial and error on different server port.

**Comment by ckrey** [comment]
@Frozenleaf did you solve your problem in the meantime?

**Comment by ackratos** [comment]
I am getting 
`2019-10-22 20:23:45.442868+0800 TrusTSS[51230:1686447] [MQTTSessionManager] eventCode: connection error (3) Error Domain=MQTT Code=-9807 "Unable to apply security policy, the SSL connection is insecure!" UserInfo={NSLocalizedDescription=Unable to apply security policy, the SSL connection is insecure!}` on connecting with my aws iot broker with same method above

Did anyone meet such issue?
