### ISSUE TITLE
Connection problem - Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)"

### ISSUE THREAD

**Issue by batrinuvlad** [ckrey/MQTT-Client-Framework#230]
Hello,

I'm trying to connect to AWS ioT with a presigned url.
 The URL looks something like this: wss://xxxxxx.iot.us-west-2.amazonaws.com/mqtt?etc

This is how i'm trying to connect:

        let clientID = NSUUID().UUIDString
        let transport = MQTTCFSocketTransport()
        transport.host = host
        
    
        let session = MQTTSession()
        session.transport = transport
        session.clientId = clientID
        
        
        session.delegate = self
        session.connectWithConnectHandler({
            (result) in
            
        })

I am receiving: mqttTransport didFailWithError Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)" 

If you think it might help, I can post the whole log.
Any idea what's with that code and what am I doing wrong?

**Comment by ckrey** [comment]
host should be `xxxxxx.iot.us-west-2.amazonaws.com` and you need to use MQTTWebsocketTransport

See #120 for an explicit description
