### ISSUE TITLE
Using client certificate from keychain

### ISSUE THREAD

**Issue by jannetak** [ckrey/MQTT-Client-Framework#237]
I'm trying to connect SSL-enabled Mosquitto-broker that requires client certificate to be used. Here is the code I'm using.  I have added all the certificates into iOS keychain and I'm getting client certificate from SecIdentity, which is also in the key chain.

        self.transport = MQTTCFSocketTransport()
        self.transport?.host = mqttAddress
        self.transport?.port = 8883
        self.transport?.tls = true
        let certs: CFArray? = getCertArray()
        var policy : MQTTSSLSecurityPolicy = MQTTSSLSecurityPolicy()
        let certs = certs as! [Any]
        var certsDer : [Any] = [] //CA certificates in DER format
        for i in certs{
            certsDer.append(SecCertificateCopyData(i as! SecCertificate))
        }
        policy.pinnedCertificates = certsDer 
        policy.allowInvalidCertificates = true
        policy.validatesCertificateChain = false
        policy.validatesDomainName = false

        self.session = MQTTSession()
        self.session?.transport = transport
        self.session?.delegate = self
        
        self.session?.securityPolicy = policy
        var clientCert:SecCertificate?
        let status = SecIdentityCopyCertificate(identity, &clientCert);
        var certArray: [Any] = []
        certArray.append(clientCertificate)
        self.session?.certificates = certArray 
        self.session?.connect()
       
Following is the response that I have got:

        2016-11-18 15:37:06.859378  [MQTTSession] init
        2016-11-18 15:37:06.864151 [MQTTSession] connecting
        2016-11-18 15:37:06.865455 [MQTTPersistence] Persistent store: /var/mobile/Containers/Data/Application/23g4g4g2322/Documents/MQTTClient
        2016-11-18 15:37:06.868803 [MQTTCFSocketTransport] open
        2016-11-18 15:37:06.874937  [MQTTCFSocketTransport] close`

However callbacks such as "connected(_ session: MQTTSession!)", "connectionClosed" or "connectionError" are not called. Any suggestions? I'm wondering how private key is given to MQTTSession?

**Comment by jannetak** [comment]
Now I managed to get following error:

`[9310:3349750] [MQTTSession] mqttTransport didFailWithError Error     Domain=kCFErrorDomainCFNetwork Code=1 "(null)" UserInfo={_kCFStreamErrorCodeKey=1, _kCFStreamErrorDomainKey=12}`

connectionClosed and connectionError callbacks are called.

**Comment by ckrey** [comment]
CFNetwork Code 1 means "hostname not found".  Are you using an address or hostname and can the hostname be resolved via DNS in your environment?

**Comment by jannetak** [comment]
Thanks for that. Now I got `[MQTTSession] mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain Code=-9807 "(null)" UserInfo={_kCFStreamErrorCodeKey=4294957489, _kCFStreamErrorDomainKey=3}`

Maybe there is something wrong with my certitificates?
