### ISSUE TITLE
How to get all message stored on MQTT persistence 

### ISSUE THREAD

**Issue by Ragava-vetri** [ckrey/MQTT-Client-Framework#239]
is there any API or any methods to get all messages stored on MQTT? i hope all mesaages are store on MQTT persistence, that why there will be a use of **"MQTTCoreDataPersistence"** Class.

**Comment by ckrey** [comment]
No, the messages are only stored while not acknowledged by the receiver in QoS1 and QoS2. This works in both directions: client to server and server to client. 
Persistence is necessary to let the messages survive app suspend / kill / crash.
