### ISSUE TITLE
 #import <CocoaLumberjack/CocoaLumberjack.h> not found in MQTTLog.h file

### ISSUE THREAD

**Issue by iHamVic** [ckrey/MQTT-Client-Framework#240]
Installed the MQTT Client and Cocoalumberjack framework via Cocoapods

Cocoapods Version: **1.0.0**
My pod files looks like 

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
 
def common_pods
    pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git'
    pod 'MQTTClient'
end

target 'Target1' do
      common_pods
end
target 'Target2' do
       common_pods
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == "MQTTClient"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'myLogLevel=0', 'LUMBERJACK=1']
            end
        end
    end
end
```

Then in Pods project I added ```CocoaLumberjack``` as ```Target Dependency``` in ```Build Phases``` of ```MQTTClient``` target. I also tried weak-linking ```CocoaLumberjack.framework``` in ```Link Binary with Libraries```.

But as I set LUMBERJACK=1, I am facing this issue. Is this issue due to CocoaPods version or Cocoalumberjack or MQTTClient Framework library?

**Comment by ckrey** [comment]
You need the CocoaLumbererjack package (the library is not Swift)

**Comment by iHamVic** [comment]
@ckrey CocoaLumbererjack added swift support as a subspec to their cocoa pods and suggested to use it as below
```pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git'```.
For more details, Read this: [converstion](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/405)
As I am using both swift and Obj-C files in my project I need this CocoaLumbererjack  support.
