### ISSUE TITLE
if i used a sub thread and config its run loop. then connect server by "- (BOOL)connectAndWaitTimeout:(NSTimeInterval)timeout"  main thread will be blocked

### ISSUE THREAD

**Issue by ruoyuruoshui** [ckrey/MQTT-Client-Framework#242]
i think this is caused by core data. 

you init object context with NSMainQueueConcurrencyType, if i set the sub thread runloop to MQTTSession , it will block main thread by call performBlockAndWait:

**Comment by ckrey** [comment]
Yes, please create the MQTTSession in the thread you will be using it in.

I see this is not ideal, but doing so will make it work.

On the other hand: As all but the `...AndWait` methods in the framework are non-blocking, it is save to use them in the main thread.
