### ISSUE TITLE
Silent Notification wake up and connect to broker

### ISSUE THREAD

**Issue by iOSRaj** [ckrey/MQTT-Client-Framework#248]
Hi @ckrey, 
It would be very nice if you can guide me on how to connect my app to my broker in response to silent push notifications.

I tried to connect using the did receive remote notification method but unfortunately I'm not able to connect to my broker even though i set background modes in the app.

I initialized my session like this.

`      
let socket :MQTTCFSocketTransport = MQTTCFSocketTransport()
        
        socket.host = "host"
        socket.port = 8883
        socket.tls =  true
        session.transport = socket
        
        session.delegate = self
        session.userName = "xxxx"
        session.password = "xxxx"
        session.connect()
`

or 

I have done like this also

` newSession.connect(toHost: "host", port: 8883, usingSSL: true)`

I'm able to call the connect method in both cases, but it doesn't do anything .

The moment app goes to background, whenever i send a message from the broker its not receiving on the device but it gets received in the simulator any config needs to be added ?

Usually as per apple, there is timeout of 180 sec but its not working in my case also it doesn't wake up the app from the background through silent notifications .
Would you guide me in this .

Any assistance is hugely appreciated. Thanks a lot

**Comment by wenxin3262** [comment]
If you can get it connected when app is in foreground, there should not be any difference to connect in the background. I would not use socket unless that's required.
Since you already got a silent notification, why not just send the data you need in the notification payload rather than talk to a broker? When your app running in the background, you have limited CPU execution time so it's better to just get things done without dealing with networking overhead. To not kill users battery life, do background fetch instead of silent notification. It's my opinion though, let me know if there is a batter way.

**Comment by iOSRaj** [comment]
@wenxin3262 Thanks a lot for your reply. Our use case is to fetch multiple queued messages from the broker and display it in the notification banner instead of user opening the app as he/she might be busy with some work.
So, We have to use the span of 30 sec to display as much as possible in the notification center.

Does this framework supports silent notifications ? I have tried many options but I'm not able to figure out. It would be very much helpful if you have any pointers

**Comment by wenxin3262** [comment]
@iOSRaj I think this framework is not intended to send apple remote notification. You can use some APN services directly, for example Firebase Cloud Messaging.

**Comment by iOSRaj** [comment]
@wenxin3262 Actually, I trying to connect to broker if i receive a silent notification from APNS.
From APNS, Im receiving silent notification but I'm not able to connect to broker in the background.

**Comment by ckrey** [comment]
The framework does support background connects. You should not call the completionsHandler before you have connected, received your messages and closed the connection again:

```
- (void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {

   connect

    [self performSelector:@selector(backgroundFetchFinished:)
               withObject:completionHandler
               afterDelay:10.0];
    
}

- (void)backgroundFetchFinished:(void (^)(UIBackgroundFetchResult result))completionHandler {

   close connection

    completionHandler(UIBackgroundFetchResultNewData);
}

```

**Comment by iOSRaj** [comment]
@ckrey , thank you so much.
It doesnt matter that i can use either of MQTTSessionManager or MQTTSession to connect in the background ?
Kindly guide me .

**Comment by ckrey** [comment]
MQTTSessionManager is not designed for background use. It uses MQTTSession which can be fine-tuned for different usage patterns

**Comment by iOSRaj** [comment]
@ckrey Thanks a lot.
