### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Abhishek9634** [ckrey/MQTT-Client-Framework#252]
After library update i'm getting errors
![screen shot 2016-12-21 at 11 53 03 am](https://cloud.githubusercontent.com/assets/10388287/21379446/14db010e-c774-11e6-9ddb-a9a4be6e67cb.png)

i have created object **session** of class **MQTTSession**

what i have to change??

**Comment by Abhishek9634** [comment]
Also 
[MQTTSession] checkDup agpzfmFwcGxvemljchMLEgZTdVVzZXIYgICAgMjyuQkM-1.245760 
logs are coming so is this a bug or it's a natural flow?
Can you explain what its actually mean?

**Comment by ckrey** [comment]
checkDup is just a debug message. To disable them change the settings in your project or directly in MQTTLog.h

**Comment by NathanMrtns** [comment]
@ckrey How to disable the log in the project settings?

**Comment by torinnguyen** [comment]
[MQTTLog setLogLevel:DDLogLevelWarning];
