### ISSUE TITLE
MQTTClient.xcdatamodeld Code Generation in Swift

### ISSUE THREAD

**Issue by JerOdd** [ckrey/MQTT-Client-Framework#256]
Hi,

The language of code generation for MQTTClient.xcdatamodeld is Swift. It can cause some build issues if the framework is integrated in a pure Objective-C project.

Kind regards.

**Comment by ckrey** [comment]
Sorry, There is no code generation for and no MQTTClient.xcdatamodeld used. The file / directory will be deleted now!
