### ISSUE TITLE
MQTT-Client linking to the local server error

### ISSUE THREAD

**Issue by hhuua123** [ckrey/MQTT-Client-Framework#258]
Hi,
I have some problems using MQTT。
When I was testing a network connection。I set _transport.host = @"192.168.11.26"._transport.port= 61616.
I deployed activemq server on my computer .
But Xcode reported an error ：
[MQTTSessionManager] eventCode: connection error (3) Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)" UserInfo={_kCFStreamErrorCodeKey=1, _kCFStreamErrorDomainKey=12} 
is that means I was wrong because of the host?
But when using Android link to this server is no problem.

**Comment by ckrey** [comment]
Are you sure you have an IPv4 network on your phone? Can you use DNS? If so, iOS will query the AAAA or A record and try IPv6 or IPv4 connection

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
