### ISSUE TITLE
Providing CA file for ssl communication

### ISSUE THREAD

**Issue by kirang89** [ckrey/MQTT-Client-Framework#26]
I can't seem to find any way to provide a `cafile` parameter for a session. Without that, how is it possible to connect to a broker securely ? Or am I missing something ?

**Comment by ckrey** [comment]
MQTT-Client-Framework validates server certificates against the iOS/OSX keychain. If you use a self signed server certificate you have to add it to the keychain, e.g. by sending it to the device via email or retrieving it via https. The mail app or safari will open it in keychain automatically or you may call NSOpenUrl from your app.

**Comment by kirang89** [comment]
Thanks! Is the tls version implicit as well ?

**Comment by ckrey** [comment]
Yes, the library uses
`kCFStreamSocketSecurityLevelNegotiatedSSL`:
> Specifies that the highest level security protocol that can be negotiated be set as the security protocol for a socket stream.

**Comment by kirang89** [comment]
Thanks for the help!
