### ISSUE TITLE
MQTTClient locks up main thread on occassion in [MQTTCoreDataPersistence sync] trying to get "lock"

### ISSUE THREAD

**Issue by SuperTango** [ckrey/MQTT-Client-Framework#267]
We recently upgraded to the latest cocoapod (0.8.7).  We're starting to see the main thread hang on occasion, pausing the app always shows a deadlock in `[MQTTCoreDataPersistence sync]`.  It's very intermittent, but when it happens, the app is effectively dead as the UI is unresponsive.  We don't have much more to go on yet other than the picture below.  We are trying to get more info, but thought I should bring it up here.

![pasted image at 2017_01_31 11_49 am](https://cloud.githubusercontent.com/assets/709342/22514621/c4af3194-e854-11e6-93d9-8f067763ee95.png)

**Comment by dimohamdy** [comment]
@ckrey can you check this bugs ?

**Comment by dimohamdy** [comment]
@SuperTango did you fix it

**Comment by SuperTango** [comment]
We were not able to solve the problem. We ended up rolling back our own fork of 0.7.8 that has a patch for a memory leak (https://github.com/ckrey/MQTT-Client-Framework/commit/d49805edcf072af0990a90f8a455110482082d89)

**Comment by dimohamdy** [comment]
I use MQTTInMemoryPersistence and the same problem

**Comment by dimohamdy** [comment]
@SuperTango  the fix of this problem https://github.com/ckrey/MQTT-Client-Framework/issues/164 make the deadlock

**Comment by OmidID** [comment]
> I use MQTTInMemoryPersistence and the same problem 
Interesting. can you describe what is the relation between MQTTInMemoryPersistence AND #164 ????!!!!
If you have same problem you should check your side. 
This code currently working without problem and i cannot see any deadlock. 
I have published app with same code, until now there is no any problem.

any way you should read commit description #174

**Comment by niuhongwei** [comment]
I use MQTTCoreDataPersistence and the same problem

**Comment by jcavar** [comment]
This should be fixed with https://github.com/ckrey/MQTT-Client-Framework/pull/375
