### ISSUE TITLE
Method to check if subscribe for a Topic has been enqueued

### ISSUE THREAD

**Issue by piyushgupta27** [ckrey/MQTT-Client-Framework#269]
Hi, 
I want to know if there is an API to check if subscribe command has been enqueued for a given topic. We have a logic where multiple subscriptions might be enqueued for the same topic. In order to fix this, We'd prefer if the framework provides a way to access state for this (access enqueued subscription topics) rather than having to maintain a state of our own.

```[self.session subscribeToTopic:subscription.topic
                                              atLevel:MQTTQosLevelAtLeastOnce
                             subscribeHandler:^(NSError *error, NSArray<NSNumber *> *gQoss) {
            // handle subscription event's reponse here
      }];```

**Comment by ckrey** [comment]
Please have a look at MQTTSessionManager. This is a wrapper for MQTTSession which implements a number of methods. With respect to your question, there is an "effectiveSubscriptions" property.
