### ISSUE TITLE
MQTTCFScoketDecoder

### ISSUE THREAD

**Issue by 1247706647** [ckrey/MQTT-Client-Framework#270]
I pod 'MQTTClient' in my project ,when I run it,There are a lot of errors in MQTTCFSocketDecoder.m ,tip "Use of undeclear identifier 'LOG_ASYNC_ENABLED'"
![Uploading 屏幕快照 2017-02-08 15.57.17.png…]()

**Comment by ckrey** [comment]
This is related to CocoaLumberjack. Can you please check if you are using the latest pod version of MQTTClient. It should use the latest correct version of CocoaLumberjack.

Otherwise you can uses the Min Subpackage of MQTTClient instead of MinL. This compiles without CocoaLumberjack.
