### ISSUE TITLE
Crash in [MQTTCoreDataFlow .cxx_destruct]

### ISSUE THREAD

**Issue by dimohamdy** [ckrey/MQTT-Client-Framework#271]
I get crash when  publish data  i make clean session false

![screen shot 2017-02-09 at 2 54 45 pm](https://cloud.githubusercontent.com/assets/1476754/22784058/272940ac-eed7-11e6-9e4e-f58f22915791.png)

**Comment by ckrey** [comment]
Are you keeping a reference to the MQTTSession object after connect?

There seem to be a problem allocating the MQTTSession
