### ISSUE TITLE
What is the best way to keep MQTT alive in background

### ISSUE THREAD

**Issue by Semrubo** [ckrey/MQTT-Client-Framework#272]
We are developing VoIP app and using MQTT also for call signaling.

So the app has enabled "audio" for UIBackgroundModes, which means in case when app moves to background with active call, it remains functional.
But the problem is that as soon as app moves to background MQTT connection is closed, which leads to problems. For example the call hangup doesn't work because hangup message fails to be sent or received via MQTT.

We want to change this behavior and now looking for a solution.
One of options we are trying is initiating MQTT by [initWithPersistence](https://github.com/ckrey/MQTT-Client-Framework/blob/96c81ac6f1766fe6924b1b40def901680ebce4ef/MQTTClient/MQTTClient/MQTTSessionManager.m#L115) and setting `shouldConnectInForeground` to `false`. In this case MQTT connection is not closed when moving to background and we have possibility to close it when call is closed in background.
The worry is that in this case we will need additionally handle of all other cases for MQTT connection and disconnection. For example in [appDidBecomeActive](https://github.com/ckrey/MQTT-Client-Framework/blob/96c81ac6f1766fe6924b1b40def901680ebce4ef/MQTTClient/MQTTClient/MQTTSessionManager.m#L161) `connectToLast` is called, should I do the same in my appDelegate?

Also network reachability doesn't work in background, which is another issue to be addressed.

What other option we have to solve it?

**Comment by ckrey** [comment]
I guess you are using MQTTSessionManager. This is a simplified wrapper for MQTTSession, intended to be used in "normal" apps. For your environment I suggest you use MQTTSession directly. You may take MQTTSessionManager as an example implementation.

What do you need network reachability for? Apple suggests not to use preflighting anyhow. If you try to connect using MQTTSession in off-line, connecting just fails.

**Comment by ziaoang** [comment]
@Semrubo I also want to run my app in the background mode, so I did
1. enabled "voip" for UIBackgroundModes
2. set `voip` of MQTTSession to `YES`
3. set `shouldConnectInForeground` of MQTTSessionManager to` false`
But it cannot work, do I miss something?

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
