### ISSUE TITLE
Question : How persistance work and How to only use In Memory Persisntace

### ISSUE THREAD

**Issue by alaeddineG** [ckrey/MQTT-Client-Framework#275]
How is the MQTT-Client choosing how to persiste : In Memopry or Core Data ?
Is there a way to force using one instead of the other ? Or maybe disable it completely ?
Recently our app have received a lot of crashes that is related to CoreData (MQTTCient 0.8.7) so that way I'am asking this !

Thank you ! :)

**Comment by ogres** [comment]
Hello,

See `MQTTPersistence` and `MQTTSession`, 
it has a property `@property (strong, nonatomic) id<MQTTPersistence> persistence;`

>/** Control MQTT persistence by setting the properties of persistence before connecting to an MQTT broker.
>    The settings are specific to a clientId.
> 
>    persistence.persistent = YES or NO (default) to establish file or in memory persistence. IMPORTANT: set immediately after creating the MQTTSession before calling any other method. Otherwise the default value (NO) will be used
>        for this session.
> 
>    persistence.maxWindowSize (a positive number, default is 16) to control the number of messages sent before waiting for acknowledgement in Qos 1 or 2. Additional messages are
>        stored and transmitted later.
> 
>    persistence.maxSize (a positive number of bytes, default is 64 MB) to limit the size of the persistence file. Messages published after the limit is reached are dropped.
> 
>    persistence.maxMessages (a positive number, default is 1024) to limit the number of messages stored. Additional messages published are dropped.
>
>    Messages are deleted after they have been acknowledged.
>*/


There are two implementations provided:
1. `MQTTCoreDataPersistence`
2. `MQTTInMemoryPersistence`

You can set this property to `MQTTInMemoryPersistence`,


P.S.

`MQTTCoreDataPersistence` also has a property `persistent` and if its set to NO, it does not save to file, just uses CoreData in memory

**Comment by ckrey** [comment]
thanks @ogres

**Comment by alaeddineG** [comment]
Thank you @ogres :)
