### ISSUE TITLE
when i use TLS ,get CFNetwork SSLHandshake failed (-9807)

### ISSUE THREAD

**Issue by jxzy999** [ckrey/MQTT-Client-Framework#277]
MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
        transport.host = self.mqttHost.text;
        transport.port = [self.mqttPort.text intValue];
        transport.tls = YES;
        transport.certificates = nil;
        
        MQTTSession *session = [[MQTTSession alloc] init];
        session.transport = transport;
        session.delegate = self;
        _session = session;
        _session.userName = self.mqttuser.text;
        _session.password = self.mqttpass.text;

        _session.certificates = nil;
        _session.clientId = self.clientId;
        MQTTSSLSecurityPolicy *policy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeNone];
        policy.allowInvalidCertificates = YES;
        policy.validatesCertificateChain = NO;
        policy.validatesDomainName = NO;
        _session.securityPolicy = policy;
        _session.keepAliveInterval = 60;
        _session.willFlag = NO;
        _session.willQoS = 0;
        _session.willTopic = nil;
        _session.willMsg = nil;
        _session.cleanSessionFlag = NO;
        _session.willRetainFlag = NO;
        
        

       BOOL isSucess =   [self.session connectAndWaitTimeout:30];

when connect,I get an error CFNetwork SSLHandshake failed (-9807)
[MQTTSession] mqttTransport didFailWithError Error Domain=NSOSStatusErrorDomain Code=-9807 "(null)" UserInfo={_kCFStreamErrorCodeKey=-9807, _kCFStreamErrorDomainKey=3}

please help,let me know what`s wrong

**Comment by jxzy999** [comment]
MQTTSSLSecurityPolicy *policy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeNone];
        policy.allowInvalidCertificates = YES;
        policy.validatesCertificateChain = NO;
        policy.validatesDomainName = NO;
        
        MQTTSSLSecurityPolicyTransport *transport = [[MQTTSSLSecurityPolicyTransport alloc] init];
        transport.host = self.mqttHost.text;
        transport.port = [self.mqttPort.text intValue];
        transport.tls = YES;
        transport.certificates = nil;
        transport.securityPolicy = policy;

        MQTTSession *session = [[MQTTSession alloc] init];
        session.transport = transport;
        session.delegate = self;
        session.userName = self.mqttuser.text;
        session.password = self.mqttpass.text;



when i used MQTTSSLSecurityPolicyTransport,that is ok,i thank you should write it in README

**Comment by ckrey** [comment]
Thanks, I was just about to write that

**Comment by jxzy999** [comment]
thanks,I think using session.securityPolicy and  MQTTCFSocketTransport it not work is also a problem.

**Comment by ckrey** [comment]
I now removed the securityPolicy property from MQTTSession.

It is a property of MQTTSSLSecurityTransport and was introduced to MQTTSession only to support legacy methods

**Comment by jxzy999** [comment]
thanks a lot
