### ISSUE TITLE
Callback function for publishing message failed

### ISSUE THREAD

**Issue by woshiziye** [ckrey/MQTT-Client-Framework#279]
I found there's a callback when delivered a message - (void)messageDelivered:(MQTTSession *)session msgID:(UInt16)msgID;

But there's not a callback for sending a message failed, can anyone tell me how deal with problem?

**Comment by ckrey** [comment]
Sending a message does not fail. Either it is sent on best effort (QoS0) where no assumption on the delivery can be made or the message will be delivered and acknowledged (QoS1 or QoS2) eventually even if the client is currently not connected.
Logical errors like insufficient access rights are not sent by the server in MQTT3.1.1 and will appear to the client as successfully sent.

**Comment by woshiziye** [comment]
Many thanks for replying the question, and I'm so excited the author answered me by yourself!
