### ISSUE TITLE
[MQTTSession connect] Cause a crash

### ISSUE THREAD

**Issue by duanruiying** [ckrey/MQTT-Client-Framework#298]
SIGSEGV
SEGV_ACCERR
0 libobjc.A.dylib	objc_msgSend + 5
1 MQTTFramework	-[MQTTSession tell] + 148
2 MQTTFramework	-[MQTTSession connect] + 264
3 MQTTFramework	-[MQTTSession(Legacy) connectToHost:port:usingSSL:connectHandler:] + 740
4 MQTTFramework	-[MQTTSession(Legacy) connectToHost:port:usingSSL:] + 34
5 MQTTFramework	-[MQTTSession(Legacy) connectToHost:port:] + 30
6 libdispatch.dylib	__dispatch_call_block_and_release + 11
7 libdispatch.dylib	__dispatch_root_queue_drain + 1561
8 libdispatch.dylib	__dispatch_worker_thread3 + 97
9 libsystem_pthread.dylib	_pthread_wqthread + 1024

**Comment by ckrey** [comment]
`6 libdispatch.dylib	__dispatch_call_block_and_release + 11`suggest you are calling connectToHost in a separate thread. This is not necessary as connectToHost is nonblocking.

Anyhow, I suggest to create MQTTSession in the same thread that you will use for connecting, publishing etc. You may have a look at the examples here: https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/MQTTTestMultiThreading.m

**Comment by duanruiying** [comment]
Thanks, I'm looking at it
