### ISSUE TITLE
connectAndWaitTimeout doesn't wait for connected complete

### ISSUE THREAD

**Issue by ithaqua** [ckrey/MQTT-Client-Framework#300]
I'm using MQTT Client for developing, when I am using connectAndWaitTimeout and need return state for initial control, but I found this method will not wait for connected complete. Is this is an issue or how to use this method correctly ? 
Thanks for help

**Comment by ckrey** [comment]
If you want to wait without a timeout, specify timeout = 0.

> /** connects to the specified MQTT server synchronously
> @param timeout defines the maximum time to wait. Defaults to 0 for no timeout.
> @return true if the connection was established
> @code
> #import "MQTTClient.h"
> MQTTSession *session = [[MQTTSession alloc] init];
> [session connectAndWaitTimeout:30];
> @endcode
> */
> - (BOOL)connectAndWaitTimeout:(NSTimeInterval)timeout;

**Comment by ithaqua** [comment]
Hi ckrey,
I try to set timeout = 0, but still not wait until connect success and direct return the result.

**Comment by benstadin** [comment]
Same here. It definitely does not wait for me. When the method returns with NO, the status is MQTTSessionStatusConnecting. I canwait for some time myself, and later subscribe to a topic and receive messages.

**Comment by ithaqua** [comment]
Does any one help to answer this question ?

**Comment by ithaqua** [comment]
any update ?

**Comment by ckrey** [comment]
@ithaqua in which environment (thread, etc) are you using connectAndWaitTimeout?

There are examples in MQTTClientTests.m you can look at.
