### ISSUE TITLE
 'SocketRocket/SRWebSocket.h' file not found

### ISSUE THREAD

**Issue by n4nachiket** [ckrey/MQTT-Client-Framework#304]
Hello, I am not able to build the project after adding MQTTClient repo to my project. I am getting "'SocketRocket/SRWebSocket.h' file not found" in MQTTWebsocketTransport.h file. I added it using a traditional way (drag/drop). What's wrong?

**Comment by ckrey** [comment]
if you drag and drop, you need to get the SocketRocket files the same way.
If you use Cocoapods, the dependencies are included automatically.

**Comment by n4nachiket** [comment]
After adding SocketRocket file using drag/drop I had to change import format from SocketRocket/SRWebSocket.h to "SRWebSocket.h". And after changing this in few files, I got an error on this line : `urlRequest.SR_SSLPinnedCertificates = self.pinnedCertificates;` in 

> MQTTWebsocketTransport.h

 file.
