### ISSUE TITLE
No informing the client of  'Not authorized' error

### ISSUE THREAD

**Issue by woshiziye** [ckrey/MQTT-Client-Framework#305]
When I use a wrong password or client id to connect, I get only 'MQTTSessionEventConnectionClosed' and 'MQTTSessionEventConnectionClosedByBroker' the two eventCode, from the function '- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error', and the errors I get always are nil, although I have implemented all the callbacks.

I want to get the error, and it contains 'MQTTSessionErrorConnackNotAuthorized' to let user know the passport is wrong. 

Can someone help me? Many thanks!

**Comment by ckrey** [comment]
It depends on the broker you are using. Some brokers do return a return code, others do just close the connection. Please try using a different broker (which one do you use?).

**Comment by woshiziye** [comment]
@ckrey Thanks for your replaying again ha.
We used mosca as the broker, i wonder if the mosca just close the connection what you said.
And can I do something to get the not authorized status? Or the broker just don't support to this, need to change another one?

**Comment by ckrey** [comment]
I just tested with a local mosca instance and the error is delivered

```
        [self.session connectWithConnectHandler:^(NSError *error){
                         DDLogVerbose(@"connectHandler error:%@", error.localizedDescription);
 
```

**Comment by ckrey** [comment]
To capture logical connection errors, implement the delegate method:

```
/** gets called when a connection error happened
 @param session the MQTTSession reporting the connect error
 @param error an optional additional error object with additional information
 */
- (void)connectionError:(MQTTSession *)session error:(NSError *)error;
```

**Comment by ckrey** [comment]
You can choose between the block ... connectWithConnectHandler, install a connectHandler, or implement the delegate method. Your choice!

**Comment by RajaReddyiOS** [comment]
I was using MQTTSessionManager how do i get error code for unAuthorised User
Thank you
