### ISSUE TITLE
Question about client SSL's hostname verify 

### ISSUE THREAD

**Issue by bobwenx** [ckrey/MQTT-Client-Framework#31]
The Current MQTT client SSL implementation seems didn't verify hostname of server returned certification(or maybe i am wrong? i am not sure about this) :
```
    if (usingSSL) {
        const void *keys[] = { kCFStreamSSLLevel,
            kCFStreamSSLPeerName };
        
        const void *vals[] = { kCFStreamSocketSecurityLevelNegotiatedSSL,
            kCFNull };
        
        CFDictionaryRef sslSettings = CFDictionaryCreate(kCFAllocatorDefault, keys, vals, 2,
                                                         &kCFTypeDictionaryKeyCallBacks,
                                                         &kCFTypeDictionaryValueCallBacks);
        
        CFReadStreamSetProperty(readStream, kCFStreamPropertySSLSettings, sslSettings);
        CFWriteStreamSetProperty(writeStream, kCFStreamPropertySSLSettings, sslSettings);
        
        CFRelease(sslSettings);
    }
``` 

Does the property entry(`kCFStreamSSLPeerName=null`) will disable client-side hostname verify? if so, it's intentional to do or something else? because client-side hostname verify is important part of SSL security.

Also, i am try to implements client-side SSL certification pinning(or self-signed certification validate). does `MQTT-Client-Framework` already or planning to support this?

**Comment by ckrey** [comment]
@bobwenx you are right. MQTT-Client prevented hostname verification - remains of the early days of implementation. This insecure setting is removed now with version 0.1.6.

**Comment by ckrey** [comment]
See #27 regarding Client Certificate support. (Client Certificates are not supported yet.
See #27 on how to use self-signed certificate validation (Install your ca-certificate in your key chain).
