### ISSUE TITLE
MQTTSessionManager can't reconnect after applicationDidBecomeActive

### ISSUE THREAD

**Issue by algrid** [ckrey/MQTT-Client-Framework#312]
Here's what's producing the problem: I'm starting my iPhone-only portrait-only app on an iPad (which at the moment of app start is in landscape mode). I get the following:

* application didFinishLaunchingWithOptions call - here I create MQTTSessionManager and call connect()
* applicationDidBecomeActive call
* MQTTSessionManager.state: connected
* applicationWillResignActive
* MQTTSessionManager.state: closing
applicationDidBecomeActive
* MQTTSessionManager.state: closed
* MQTTSessionManager.state: starting
* MQTTSessionManager.state: closed
* MQTTSessionManager.state: starting

After that I never get MQTTSessionManager.state: connected.

It looks like some kind of race condition in the lib.

**Comment by ckrey** [comment]
MQTTSessionManager was not intended to be instantiated in didFinishLaunchingWithOptions.
Please instantiate it in one of your main View Controllers or in your Model after the app became active.

**Comment by algrid** [comment]
@ckrey Are you sure that the problem is not in the fact that applicationDidBecomeActive is arriving when MQTTSessionManager state is "closing"?

I get the same problem when I instantiate  MQTTSessionManager and call connect() in the first applicationDidBecomeActive.

If I do it later I cannot reproduce the problem. The transition from "closing" state to "closed" usually is very fast and I can't get applicationDidBecomeActive in between.

**Comment by ckrey** [comment]
There was a regression issue in the code since 143816e (April 19).
Please re-try with the current version

**Comment by ckrey** [comment]
@algrid I created a test repo for you  https://github.com/ckrey/mqttcf312

Please open the `mqttcf312.xcworkspace` and see the SessionManager working from the ViewController and the AppDelegate.

If you still have issues, try to recreate in that test reop

**Comment by ckrey** [comment]
Thanks for providing the test repo and for the patience
