### ISSUE TITLE
Websocket transport with certificate authentication

### ISSUE THREAD

**Issue by palivko** [ckrey/MQTT-Client-Framework#313]
Please help, 
I want to use MQTTWebsocketTransport in combination with client certificate authentication. My MQTT broker then reject the connection, see. log below. I noticed that connect MQTTMessage does not send this certificate after the transport has been opened. What am I doing wrong? Thank you very much for your advice.

[MQTTSession] init
[MQTTSession] connectWithConnectHandler:0x7fff56e50ca8
[MQTTSession] connecting
[MQTTPersistence] Persistent store: .../Documents/MQTTClient
[MQTTWebsocketTransport] open
[MQTTWebsocketTransport] connected to websocket
[MQTTSession] mqttTransportDidOpen
[MQTTSession] sending CONNECT
[MQTTMessage] wireFormat(46)=<102c0004 4d515454 0402001e 00206138 36396331 36346161 61633437 30393963 62363132 30643731 35366635 3030>...
[MQTTSession] mqttTransport send
[MQTTWebsocketTransport] send(46):<102c0004 4d515454 0402001e 00206138 36396331 36346161 61633437 30393963 62363132 30643731 35366635 3030>
[MQTTWebsocketTransport] didReceiveMessage(4)
[MQTTSession] mqttTransport didReceiveMessage
[MQTTDecoder] #streams=1
[MQTTDecoder] NSStreamEventOpenCompleted
[MQTTDecoder] NSStreamEventHasBytesAvailable
[MQTTDecoder] fixedHeader=0x20
[MQTTDecoder] digit=0x02 0x02 0 1
[MQTTDecoder] remainingLength=2
[MQTTDecoder] read 2 2
[MQTTDecoder] received (4)=<20020005>...
[MQTTSession] closeInternal
[MQTTWebsocketTransport] close
[MQTTWebsocketTransport] ConnectionClosed : (null)

**Comment by ckrey** [comment]
You don't see the SSL handshake (including client certificate) in the log, this is handled in iOS CFNetwork.

What you can see is that the MQTT CONNECT is send and a CONNACK with a negative code = 5 is returned.

You can catch this by implementing the MQTTSession delegate method 
```
/** gets called when a connection error happened
 @param session the MQTTSession reporting the connect error
 @param error an optional additional error object with additional information
 */
- (void)connectionError:(MQTTSession *)session error:(NSError *)error;
```

Anyhow, 5 as a connect return code means `not authorized`. This is a response from the broker. Please check if you have to use user/password in addition to the client identifier.

**Comment by palivko** [comment]
For sure, I send as I call MQTT broker...

session = [[MQTTSession alloc] init];
session.delegate = self;
session.clientId = [[UIDevice currentDevice] uuid];
session.keepAliveInterval = 30;
session.cleanSessionFlag = YES;

**1) Connection over SSL protocol**

MQTTSSLSecurityPolicyTransport *transport = [[MQTTSSLSecurityPolicyTransport alloc] init];
transport.host = url.host;
transport.port = (UInt16) port;
transport.tls = YES;
transport.securityPolicy = [self getDefaultSecurity];
transport.certificates = [self getClientCertificates];
session.transport = transport;
[session connect];

**2) Connection over Websocket**

MQTTWebsocketTransport *transport = [[MQTTWebsocketTransport alloc] init];
transport.host = url.host;
transport.port = (UInt16) port;
transport.path = [NSString stringWithFormat:@"%@/", url.path];
transport.tls = YES;
transport.pinnedCertificates = [self getTransportCertificates];
transport.allowUntrustedCertificates = YES;
session.certificates = [self getClientCertificates]; // It's OK?
session.transport = transport;
[session connect];

The first way over SSL protocol it works. Connection was successful.
Second way over Websocket doesn't work, see above in the log.

Thank you very much for your time.

**Comment by ckrey** [comment]
Sorry, no.

The Websocket implementation I use does not support client certificates (https://github.com/facebook/SocketRocket).

There is a fork (https://github.com/nickcheng/SocketRocket) which implements it but:
> This branch is 12 commits ahead, 267 commits behind facebook:master.
