### ISSUE TITLE
How to receive the message from broker to iOS ?

### ISSUE THREAD

**Issue by JyunKaKa** [ckrey/MQTT-Client-Framework#316]
Now I know how to publish the message to Broker by the swift example below,  but I have no idea to receive message(e.g. string or txt file) from Broker and then shown in iOS APP. 
I have read all the .m files of  mqttclient.framework,  searching about the func about "subsribe".
But they do not offer  the type like "data:Data!"  to receive the message.
 Can someone give some tips or advice? thanks.

```
func testSwiftSubscribe() {
        guard let newSession = MQTTSession() else {
            fatalError("Could not create MQTTSession")
        }
        session = newSession
        newSession.delegate = self
        newSession.connect(toHost: "192.168.1.111", port: 1883, usingSSL: false)
        while !sessionConnected && !sessionError {
            RunLoop.current.run(until: Date(timeIntervalSinceNow: 1))
        }
        
        newSession.subscribe(toTopic: "#", at: .atMostOnce)
        
        while sessionConnected && !sessionError && !sessionSubAcked {
            RunLoop.current.run(until: Date(timeIntervalSinceNow: 1))
        }
       
        newSession.publishData("sent from Xcode using Swift".data(using: String.Encoding.utf8, allowLossyConversion: false),
                               onTopic: "inTopic",
                               retain: false,
                               qos: .atMostOnce)
        
        while sessionConnected && !sessionError && !sessionReceived {
            RunLoop.current.run(until: Date(timeIntervalSinceNow: 1))
        }
        
        newSession.close()
    }

```

**Comment by ckrey** [comment]
To receive messages you have to implement the `newMessage`method in your MQTTSessionDelegate`:

( taken from https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/SwiftTests.swift )
```
    override func newMessage(_ session: MQTTSession!, data: Data!, onTopic topic: String!, qos: MQTTQosLevel, retained: Bool, mid: UInt32) {
        print("Received \(data) on:\(topic) q\(qos) r\(retained) m\(mid)")
    }
 ```

**Comment by JyunKaKa** [comment]
Thank you, ckrey.
I used the `        newSession.subscribe(toTopic: "#", at: .atMostOnce)` to  receive message.

I don't know how to implement **newMessage** method, because  some of constants I do not know.  I write in viewConroller like this:
 `let mqttSwift = MQTTSwift()
    mqttSwift.newMessage(_ session: MQTTSession!, data: Data!, onTopic topic: "myTopic", qos: 0, retained: false, mid: UInt32)`
What are  the constants [**session:** **,*data:*, and **mid:**]  ?
Am I get the wrong direction?

**Comment by gitjoost** [comment]
'data' is _your data_ i.e. what was sent by the publisher on that topic and 'mid' is a message identifier (normally not needed). BTW, this library is pretty well documented; you can browse through the code and read the comments to get all this.

**Comment by JyunKaKa** [comment]
Thanks you , gitjoost.   I have read the documentation. Now , I slove it  by use global values.    
```
var str1:String = ""
    func newMessage(_ session: MQTTSession!, data: Data!, onTopic topic: String!, qos: MQTTQosLevel, retained: Bool, mid: UInt32)  {
        print("123Received \(data) on:\(topic) q\(qos) r\(retained) m\(mid)")
            str1 = (String(data: data!, encoding: String.Encoding.utf8) as String!)!
            print("str1 is\(str1) Ohhhhh")
        
        sessionReceived = true;
    }
```
now, i got the value.   :)

**Comment by mwkim177** [comment]
which data can I put on these parameters? especially data. I'm having hard time on it.
