### ISSUE TITLE
Don't get Callback NewMessage

### ISSUE THREAD

**Issue by fatkhrus** [ckrey/MQTT-Client-Framework#318]
I'm trying to use Objective-C MQTTClient, but I can't  get messages from the subscribed topics. I don't get to NewMessage call back at all in some reasons. It seems I have connections because publish is working. Some callbacks of <MQTTSessionDelegate> is working. For example I get to connected call back, but NewMessage is not working. For testing purposes I'm using tcp://m11.cloudmqtt.com:16160 url. self.host = m11.cloudmqtt.com self.port = 16160

-(BOOL)connect{
    NSLog(@"connect");
    MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
    transport.host = self.host;
    transport.port = self.port;
   session = [[MQTTSession alloc] init];
   session.transport = transport;
    session.userName = self.username;
    session.password = self.password;
    session.delegate = self;
    [session connect];
    [session subscribeToTopic:@"Boiler/Tags/Level" atLevel:MQTTQosLevelAtLeastOnce ];
    [session publishAndWaitData:[@"10" dataUsingEncoding:NSUTF8StringEncoding ]
                        onTopic:@"Boiler/Tags/Level"
                         retain:NO
                            qos:MQTTQosLevelAtLeastOnce];
    return YES;
}
- (void)newMessage:(MQTTSession *)session
              data:(NSData *)data
           onTopic:(NSString *)topic
               qos:(MQTTQosLevel)qos
          retained:(BOOL)retained
               mid:(unsigned int)mid {
    NSLog(@"newMessage");
    NSString* newStr = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    NSLog(@"Data =%@",newStr);
    
}

**Comment by JyunKaKa** [comment]
I have  the same problem about it .  I solve it with the way below.
 You need to do the whole  process once.  
First,You need to do the function of subsriber and publisher  once. After that, you will found that you can connect the broker and get the callbackValue.   
Next time you would  just use the function of subsribe   to get the data by newmessage.

**Comment by ckrey** [comment]
you have to  wait until connected and until subscribed before the broker will send you messages.

> - (void)connectWithConnectHandler:(MQTTConnectHandler)connectHandler;

> - (UInt16)subscribeToTopic:(NSString *)topic atLevel:(MQTTQosLevel)qosLevel subscribeHandler:(MQTTSubscribeHandler)subscribeHandler;
