### ISSUE TITLE
[MQTTCoreDataPersistence Sync] jammed the main thread

### ISSUE THREAD

**Issue by niuhongwei** [ckrey/MQTT-Client-Framework#319]
this problem show in #174 

i replace this code solve the problem:

before code :
- (void)sync {
    @synchronized (lock) {
        DDLogVerbose(@"locked sync %d", [NSThread isMainThread]);
        NSLog(@"进入 lock sync %d", [NSThread isMainThread]);
        if ([NSThread isMainThread]) {
            [self internalSync];
        } else {
            //Changed to block and wait because sometime it was executed before internal parent sync
            [self.managedObjectContext performBlockAndWait:^{
                [self internalSync];
            }];
        }
        if ([NSThread isMainThread]) {
            [self internalParentSync];
        } else {
            [self.managedObjectContext.parentContext performBlock:^{
                [self internalParentSync];
            }];
        }
        DDLogVerbose(@"unlocked sync %d", [NSThread isMainThread]);
    }
}

my code:

- (void)sync {
    DDLogVerbose(@"lock sync %d", [NSThread isMainThread]);
    NSLog(@"执行 lock sync %d", [NSThread isMainThread]);
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        @synchronized (lock) {
            DDLogVerbose(@"locked sync %d", [NSThread isMainThread]);
            NSLog(@"进入 lock sync %d", [NSThread isMainThread]);
            [self.managedObjectContext performBlockAndWait:^{
                [self internalSync];
            }];
            
            
            [self.managedObjectContext.parentContext performBlock:^{
                [self internalParentSync];
            }];
            DDLogVerbose(@"unlocked sync %d", [NSThread isMainThread]);
        }
    });
}

but I don't know my code could cause new problem ;
please reutrun me ,thanks;
my QQ:539291360

**Comment by ckrey** [comment]
This change may lead to inconsistencies.

To avoid the locks, please do not call any MQTTSession methods from the delegate callbacks.

MQTTClient is **not** reentrant

**Comment by niuhongwei** [comment]
hi what problem should be bringed when i do not call any MQTTSession methods from the delegate callbacks? thanks

**Comment by jcavar** [comment]
This could be solved by https://github.com/ckrey/MQTT-Client-Framework/pull/375
