### ISSUE TITLE
Manual Acknowleding newMessages

### ISSUE THREAD

**Issue by behrad** [ckrey/MQTT-Client-Framework#32]
is there any possibility for an overload of `newMessage` with an extra `doAck` parameter to let applications asynchronously/selectively puback when they are finished handling the message.

**Comment by ckrey** [comment]
No, currently not. 

To be honest, I don't think delaying the PUBACK QoS1 or PUBREL/PUBCOMP for QoS2 is conferment to the MQTT protocol.

>The Client MUST acknowledge any Publish Packet it receives according to the applicable QoS rules >regardless of whether it elects to process the Application Message that it contains [MQTT-4.5.0-2].

If you want to establish an application end-to-end protocol, I would suggest to do this with separate messages.
