### ISSUE TITLE
Can't connect broker when willFlag = true

### ISSUE THREAD

**Issue by utnhim** [ckrey/MQTT-Client-Framework#320]
hi,
I want to get message after disconnect so I try set "willFlag = true".
But when i set "willFlag = true", i can't connect to broker.
can you tell me  how do fix it.

thanks :)

**Comment by algrid** [comment]
Does your broker allow to publish to your will topic? I mean access control settings. I've had similar issue when I was disabled to write to my will topic.

**Comment by ckrey** [comment]
When using willFlag = true, you should specifiy
- a willTopic which is writeable at your broker
- a willMsg
- a willQos supported by your broker (0,1,2 / AtMostOnce, AtLeastOnce, ExactlyOnce)
- a willRetain flag allowed by your broker

You may connect to your broker with your intended will message with the same Qos, Retain, Topic with the same user/pass/clientId using mosquitto_pub
```
...
 --will-payload : payload for the client Will, which is sent by the broker in case of
                  unexpected disconnection. If not given and will-topic is set, a zero
                  length message will be sent.
 --will-qos : QoS level for the client Will.
 --will-retain : if given, make the client Will retained.
 --will-topic : the topic on which to publish the client Will.
...
```

**Comment by ckrey** [comment]
@utnhim any progress on this?

**Comment by utnhim** [comment]
Thank Mr.Ckrey,

I fixed, but i get a error with "connections".

I have n* connection when i reconnnect. I try disconnec and close mqtt in funntion "connectionError" but i can't reconnect. 
Sometime it make crash app.

Thanks :)

This is my code.

-(void)connectionError:(MQTTSession *)session error:(NSError *)error{
    [self.mqttClient disconnect];
    [self.mqttClient close];
}

- (void)connectionClosed:(MQTTSession *)session{
    [self.mqttClient connectAndWaitTimeout:30];
}

**Comment by ckrey** [comment]
you should not call MQTTsession methods from within the delegate callbacks
