### ISSUE TITLE
Proposal: Use master branch for stable releases

### ISSUE THREAD

**Issue by benstadin** [ckrey/MQTT-Client-Framework#321]
I do not use pods in my project, and ran into some issues when adding the MQTT master branch as submodule to my project. It didn't compile, and some time later I found the actual commit of the last stable release and used that. 

I propose to use git-flow (develop branch for development, master for stable releases), or tag commits which were used for the releases. 

Regards
Ben

**Comment by ckrey** [comment]
You are absolutely right
