### ISSUE TITLE
Redundant logs

### ISSUE THREAD

**Issue by YueLiXing** [ckrey/MQTT-Client-Framework#323]
I use cocoapods input the Framework,but it log too large log.

```
MQTTLog.h
#ifdef DEBUG
#define DDLogVerbose NSLog
#define DDLogWarn NSLog
#define DDLogInfo NSLog
#define DDLogError NSLog
#else
#define DDLogVerbose(...)
#define DDLogWarn(...)
#define DDLogInfo(...)
#define DDLogError(...)
#endif /* DEBUG */
```

iPhone 5s,iOS 9.3.5,Xcode 8.3.3

<img width="1229" alt="qq20170612-114054 2x" src="https://user-images.githubusercontent.com/9456800/27018550-0ea7deba-4f64-11e7-9cf0-b02609009e15.png">

**Comment by anagram** [comment]
I would like to know how to turn off this logging, thanks!

**Comment by ckrey** [comment]
So you are not using CocoaLumberjack.

To turn the logging off in that case:

Change `#ifdef DEBUG`
to `#ifndef DEBUG` or `#ifdef I_DONT_WANT_LOGS`

**Comment by aterribili** [comment]
This is a poor solution, because I'm gonna need to do that modification every time after an pod install. Is it any other option?

**Comment by aterribili** [comment]
After `pod install` step, I'm executing the code below: 
```
sed 's/DEBUG/I_DONT_WANT_LOG/g' Pods/MQTTClient/MQTTClient/MQTTClient/MQTTLog.h
```

**Comment by ckrey** [comment]
you can now set [MQTTLog setLogLevel:DDLogLevelOff] etc. for the complete library
