### ISSUE TITLE
The child thread to send data frequently lead to the UI

### ISSUE THREAD

**Issue by codepgq** [ckrey/MQTT-Client-Framework#324]
[MQTTDecoder] NSStreamEventOpenCompleted
[MQTTDecoder] NSStreamEventHasBytesAvailable
[MQTTDecoder] fixedHeader=0x40
[MQTTDecoder] digit=0x02 0x02 0 1
[MQTTDecoder] remainingLength=2
[MQTTDecoder] read 2 2
[MQTTDecoder] received (4)=<4002001a>...
flowforClientId requestingPerform
flowforClientId performing
flowforClientId performed

**Comment by ckrey** [comment]
@codepgq can you explain a bit more what is your problem, please?

**Comment by codepgq** [comment]
Well, I have a demand, will send data frequently, when I do this time, frequently send data will lead to my UI card Dayton, so I sent the code to write the code in the child thread, I think this way Can be resolved, but not, when I test a break after the time, UI is stuck, I think the thread deadlock. I am using MQTTWebsocketTransport

this is my send method
- (void)sendData:(NSData *)data publishHandler:(void(^)(NSError * error))handler{
    if (!self.isOnLine) return;
    
    if (self.allPubs && self.allPubs.count) {
        
        for (NSString * key in self.allPubs.allKeys) {
            dispatch_async(sendDataQueue, ^{
//                [NSThread sleepForTimeInterval:0.05];
                [self.mqttSession publishData:data onTopic:key retain:_isRetain qos:_qosLevel publishHandler:handler];
            });
        }
    }
    if (self.pub) {
        dispatch_async(sendDataQueue, ^{
//            [NSThread sleepForTimeInterval:0.05];
            [self.mqttSession publishData:data onTopic:self.pub retain:_isRetain qos:_qosLevel publishHandler:handler];
            
        });
    
    }
}
_isRetain = NO;
qosLevel = 1;
sendDataQueue = dispatch_queue_create("SendDataQueue", NULL);

**Comment by jcavar** [comment]
Part of this problem could be resolved by https://github.com/ckrey/MQTT-Client-Framework/pull/375, for other part you need to initialise MQTTSession with custom runLoop parameter. To do that you need to create thread and start run loop. To get idea check:
https://github.com/facebook/SocketRocket/blob/master/SocketRocket/Internal/RunLoop/SRRunLoopThread.m
