### ISSUE TITLE
MqttSession.securityPolicy not found

### ISSUE THREAD

**Issue by HO-KAI-HSU** [ckrey/MQTT-Client-Framework#326]
This problem, i dont know how do solve it Please help!!

[
![mqttsessionproblem](https://user-images.githubusercontent.com/17850549/27507369-6ff6f7fa-5900-11e7-9aeb-caa49e461056.JPG)
](url)

**Comment by jcavar** [comment]
`securityPolicy` property is available on `MQTTSSLSecurityPolicyTransport`
