### ISSUE TITLE
Can I use this library from behind a proxy?

### ISSUE THREAD

**Issue by dii14** [ckrey/MQTT-Client-Framework#329]
My mqtt broker is behind a proxy. I am trying to reach it using secure websockets by passing the address and port where the broker is. I cannot really find anything that lets me set proxies. Is it possible to do it? Is the library picking up the system proxies?

**Comment by ckrey** [comment]
MQTTClient facebook's SocketRocket as a web socket implementation.
Unfortunately I don't have an environment to test proxied ws connections.

But according to the discussion here: https://github.com/facebook/SocketRocket/issues/114 it should work by picking up system settings

**Comment by dii14** [comment]
I was using the cocoapods which has the old version of SocketRocket which did not have proxy support. I updated to the facebook maintained SocketRocket version and it does work. Thanks
