### ISSUE TITLE
Reconnect support

### ISSUE THREAD

**Issue by behrad** [ckrey/MQTT-Client-Framework#33]
do the library support for auto reconnects?

**Comment by ckrey** [comment]
Please have a look at the included MQTTSessionManager class if it supports your needs. 
It manages backgrounding of an iOS app and reconnects when being foregrounded again.
It reconnects after error too.

**Comment by behrad** [comment]
thank you ckrey

**Comment by behrad** [comment]
It seems a generic IOS question not related to MQTT-Client however may be you can give me a helpful comment here @ckrey 

My problem is when the app is background my network reachability hooks doesn't work and I can't reconnect when WIFI/DATA is toggled :(

May be you have had the same experience/need in your apps, or can hint me.

**Comment by ckrey** [comment]
I think the place to start is the official Apple developer site:
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

A good tutorial is
http://www.raywenderlich.com/92428/background-modes-ios-swift-tutorial

There are lots of examples around, but I have to admit it takes a while to understand the concept of iOS handling apps.

**Comment by behrad** [comment]
thank you @ckrey

**Comment by bobwenx** [comment]
i resolve this by setup [Reachability](https://github.com/tonymillion/Reachability) hook(check whether `apple.com` is reachable). 
when network become available, just call MQTTSessionManager.reconnect immediately.

**Comment by behrad** [comment]
> i resolve this by setup Reachability hook(check whether apple.com is reachable). 
> when network become available, just call MQTTSessionManager.reconnect immediately.

I was known of `Reachability` module on github, Thank you.

@bobwenx is your network available hook always being called also when app is in background?!

**Comment by bobwenx** [comment]
No, it only get called when app active in foreground.

**Comment by behrad** [comment]
@bobwenx Oh! then how are you handling this in background mode?

I don't know how social apps like viber/telegram/whatsapp are handling server side events when app has a connection in background (without APNS) !?

**Comment by bobwenx** [comment]
I setup MQTT connection status listener in server side, when MQTT client connection is broken, the server will send message via APN.

`Reachability` hook only meaningful when MQTTSessionManager's reconnect interval become too large(such as try to reconnect per minute).

**Comment by behrad** [comment]
> I setup MQTT connection status listener in server side, when MQTT client connection is broken, the server will send message via APN.

same as us. Are you saying you just keep the MQTT connection open when app is in *foreground*? 
However I believe there should have been a way to keep MQTT connection open when app is in background.



> Reachability hook only meaningful when MQTTSessionManager's reconnect interval become too large(such as try to reconnect per minute).

I'm not sure if I got your point here

**Comment by ckrey** [comment]
Apps can register for background fetch to get server data.
This means the app is called once in a while (typically 10-15 min) to connect and check the server.
Anythin else relies on APNS

**Comment by bobwenx** [comment]
No matter what techs used by popular apps like viber/telegram/whatsapp, the app wouldn't bypass iOS push(APN) if app enter background.
but to setup our long-live connection, we can:
1. get bidirectional message communication.
2. encryption/compression the message payload.(apple's APN guide say you should not send sensitive payload via VPN)
3. reailable message send/consuming.

**Comment by bobwenx** [comment]
Another options: iOS 8's `silent push`, though there is limited time to execute code background code. but it's OK if server app are able to send silent push notification when MQTT connection is broken.

**Comment by ckrey** [comment]
you may use (silent) APN push to wake up app for urgent updates but leave the actual encrypted data transfer to MQTT

**Comment by bobwenx** [comment]
@ckrey that's what i am doing :)

**Comment by behrad** [comment]
really nice hang out guys, thank you.
I'll definitely check silent push for IOS8 however we need real time message pushes for IOS7 also.

1) According to your points, we should keep MQTT connection open as long as app is active!?




> No matter what techs used by popular apps like viber/telegram/whatsapp, the app wouldn't bypass iOS push(APN) if app enter background.
> but to setup our long-live connection, we can:
> 1. get bidirectional message communication.
> 2. encryption/compression the message payload.(apple's APN guide say you should not send sensitive payload via VPN)
> 3. reailable message send/consuming.

Still I can't figure out how are you handling app background!?

My problem is app in background (with our talk it now only should be limited to ios7)

**Comment by behrad** [comment]
we are currently keeping MQTT connection open when app is alive (both forground + background) however we can't test for network reachability events to reconnect MQTT if dropped :(

**Comment by ckrey** [comment]
Sorry, you can't keep it open in background. iOS will put the app to sleep latest 10min after backgrounded.
If you found a way to do this, let me know.
Declaring the app as an Voice over IP app will not be approved fot the app store.
You don't need to check for reachability, just try to reconnect from time to time

**Comment by bobwenx** [comment]
@behrad i am not handing anything when app enter background(i just disconnect MQTT Connection). but when MQTT Connection get disconnected(either by ourself or by tcp interrupted), my server side code(i write a MQTT server by myself) are able to known such things happen, and it will sending message via APN rather via MQTT.

**Comment by bobwenx** [comment]
for reachability check, it only meaningful if the reconnect interval time(range from 1 - 64) get too large. if reachability book notify me that network is OK, my code will try to reconnect MQTT connection immediately(of course, in this time, my app must be in foreground).
it's OK if there is no reachability check, the `MQTTSessionManager` still able to reconnect to server(after 64 second).

**Comment by behrad** [comment]
value-able info guys :) My only fear is that APN pushes cannot be reliable 

1) I see delivery delays when we sent APN push but client's phone has no network and client is online after minutes. We are using apple sandbox servers, I don't know if it's quality/garauntee changes switching to production servers!?

2) When using on high traffic deployments.

**Comment by bobwenx** [comment]
apple's documents do say: `APN pushes are not reliable`: https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW4

**Comment by behrad** [comment]
exactly @bobwenx And that was pushing me forward to try to build a reliable IOS push, with offloading much of the effort to our server MQTT connection instead of APNS when app is background or even killed!! , however this seems not-possible in IOS :(

I hope silent APN pushes (content-available:1) are more chancy to delivered as fast as client being online. Only the last push suffices :)

**Comment by ckrey** [comment]
I recently did a simple demo app called MQTTChat, which implements auto reconnect based on MQTTSessionManager: https://github.com/ckrey/MQTTChat

see also: http://www.hivemq.com/mqtt-client-library-encyclopedia-mqtt-client-framework/

**Comment by behrad** [comment]
:+1: great @ckrey will definitely check it out

**Comment by jholstead** [comment]
> Declaring the app as an Voice over IP app will not be approved fot the app store.

My apps will be distributed via MDM or 'side loading', not app store. I tried turning on VOIP and following the instructions. So far, no luck.

**Comment by dcy** [comment]
Does anyone use VOIP pushkit in IOS8 and can not reconnect?
The server shows the client already connected, It seems that client does not recieve puback(maybe received but not trigger) but server have sent the puback.
This can reproduce:

1. Kill the app, client not login.

1. Send a VOIP pushkit to app.

1. Then the app's client will wake up and reconnect, but can not reconnect success.
