### ISSUE TITLE
Externally define DDLogLevel

### ISSUE THREAD

**Issue by jcavar** [ckrey/MQTT-Client-Framework#330]
I am struggling to define MQTTClient log level from application code. We are using CocoaLumberjack in app as well and I want to share log level between MQTTClient and app. I can see that there is `myLogLevel` preprocessor in `MQTTLog.h` but I can't find a way to use it.

**Comment by jcavar** [comment]
Ok I believe the problem is that we use CocoaPods with dynamic frameworks and when we define `myLogLevel` it doesn't affect `MQTTClient`.

**Comment by ckrey** [comment]
Works without CocoaLumberjack too (using NSLOG macros)
