### ISSUE TITLE
Not receiving messages and not able to connect at all with async methods

### ISSUE THREAD

**Issue by jameyer** [ckrey/MQTT-Client-Framework#333]
Hi, I've been trying for days to get set up a working MQTT service in my app, but I'm unable to receive any messages. Based on the examples I put together this:

``` objc
// Called from main thread
- (void)doConnection {
    MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
    transport.host = @"test.mosquitto.org";
    transport.port = 1883; // 1883 = default
    
    self.session = [[MQTTSession alloc] init];
    self.session.clientId = [NSString stringWithFormat:@"MQTTClient%.0f", fmod([[NSDate date] timeIntervalSince1970], 1.0) * 1000000.0];
    self.session.delegate = self;
    self.session.cleanSessionFlag = YES;
    self.session.transport = transport;
    self.session.protocolLevel = 4;

    [self.session connectAndWaitTimeout:30];
}

- (void)connected:(MQTTSession *)session {
    DLog(@"Connected to MQTT broker.");
    
    [self.session subscribeAndWaitToTopic:@"qqU6U7MjrliTSgvj" atLevel:2];
    
    DLog(@"Subscribed to topic");
    
    NSString *randomString = [self randomStringWithLength:8];
    NSData *data = [randomString dataUsingEncoding:NSUTF8StringEncoding];
    [self.session publishAndWaitData:data onTopic:@"qqU6U7MjrliTSgvj" retain:NO qos:1];
    
    DLog(@"Published data: %@", randomString);
}

- (void)newMessage:(MQTTSession *)session
              data:(NSData *)data
           onTopic:(NSString *)topic
               qos:(MQTTQosLevel)qos
          retained:(BOOL)retained
               mid:(unsigned int)mid {
    DLog(@"MQTT - %@: %@", topic, [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
}

- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error {
    DLog(@"handleEvent: eventCode: %ld, %ld", (long)eventCode, (long)error.code);
}

- (void)connectionError:(MQTTSession *)session error:(NSError *)error {
    DLog(@"Connection error: %@", error.localizedDescription);
}

- (void)connectionRefused:(MQTTSession *)session error:(NSError *)error {
    DLog(@"Connection refused: %@", error.localizedDescription);
}

- (void)connectionClosed:(MQTTSession *)session {
    DLog(@"Connection closed");
}
```

Connecting, subscribing and publishing works, but newMessage never gets called. I've even set up another MQTT client (in Java with Paho) subscribed to the same topic, and this client is receiving the messages that this iOS client is publishing.

I tried using the async methods but the handlers are then not called at all. If I use

`[self.session connect]` instead of `[self.session connectAndWaitTimeout:30];`,

the - (void)connected:(MQTTSession *)session is never called. The log output when using `[self.session connect]` is then:

`2017-07-09 17:43:37.283068+0200 app[20256:7888727] [MQTTSession] init
2017-07-09 17:43:37.283514+0200 app[20256:7888726] [MQTTSession] connecting
2017-07-09 17:43:37.283563+0200 app[20256:7888726] lock managedObjectcontext 0
2017-07-09 17:43:37.283589+0200 app[20256:7888726] locked managedObjectcontext 0
2017-07-09 17:43:37.283671+0200 app[20256:7888726] lock persistentStoreCoordinator 0
2017-07-09 17:43:37.283696+0200 app[20256:7888726] locked persistentStoreCoordinator 0
2017-07-09 17:43:37.284478+0200 app[20256:7888726] [MQTTPersistence] Persistent store: /var/mobile/Containers/Data/Application/A4CC549F-9159-40B7-85C9-98DC55B554F3/Documents/MQTTClient
2017-07-09 17:43:37.284564+0200 app[20256:7888726] lock managedObjectModel 0
2017-07-09 17:43:37.284592+0200 app[20256:7888726] locked managedObjectModel 0
2017-07-09 17:43:37.285778+0200 app[20256:7888726] unlocked managedObjectModel 0
2017-07-09 17:43:37.286914+0200 app[20256:7888726] unlocked persistentStoreCoordinator 0
2017-07-09 17:43:37.287301+0200 app[20256:7888726] unlocked managedObjectcontext 0
2017-07-09 17:43:37.288696+0200 app[20256:7888726] lock sync 0
2017-07-09 17:43:37.288751+0200 app[20256:7888726] locked sync 0
2017-07-09 17:43:37.288802+0200 app[20256:7888726] unlocked sync 0
2017-07-09 17:43:37.288832+0200 app[20256:7888674] lock managedObjectcontext 1
2017-07-09 17:43:37.288882+0200 app[20256:7888674] locked managedObjectcontext 1
2017-07-09 17:43:37.288908+0200 app[20256:7888674] unlocked managedObjectcontext 1
2017-07-09 17:43:37.289604+0200 app[20256:7888726] [MQTTCFSocketTransport] open
2017-07-09 17:43:37.289973+0200 app[20256:7888726] [MQTTCFSocketEncoder] setState 0/0`

Am I missing something obvious? I've also tried with different brokers with the same results.

**Comment by ckrey** [comment]
You are blocking the library by calling API methods in the delegate connected: method.

If you are using synchronous methods ...AndWait, you better do subscribe and publish in your doConnection method.

**Comment by jameyer** [comment]
Thank you! Yeah that makes sense, my mistake. Could this be a potential fix for that?

``` objc
- (void)connected:(MQTTSession *)session {
    DLog(@"Connected to MQTT broker.");
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [self.session subscribeAndWaitToTopic:@"qqU6U7MjrliTSgvj" atLevel:2];
        
        DLog(@"Subscribed to topic");
        
        NSString *randomString = [self randomStringWithLength:8];
        NSData *data = [randomString dataUsingEncoding:NSUTF8StringEncoding];
        [self.session publishAndWaitData:data onTopic:@"qqU6U7MjrliTSgvj" retain:NO qos:1];
        
        DLog(@"Published data: %@", randomString);
    });
}
```

**Comment by jameyer** [comment]
I think I found my issue. The object these methods were called in was possibly being garbage collected. I changed the implementation to a singleton and the async methods + delegate seems to be working fine now. Thanks for the clarification on using synchronous methods within the delegate methods though.

**Comment by ActorNikhil** [comment]
Hi Jameyer,

I'm facing same issue, could you please update what changes you have made.

**Comment by jameyer** [comment]
> 
> 
> Hi Jameyer,
> 
> I'm facing same issue, could you please update what changes you have made.

We ended up with not using MQTT after all. But to avoid that your object receiving delegate callbacks gets deallocated, just make sure there is a strong reference to it by for instance your view controller.

**Comment by ActorNikhil** [comment]
Hi Ckrey,

Can you help me on how to setup connection time out for MQTTSession object.
