### ISSUE TITLE
Link the lib dynamically

### ISSUE THREAD

**Issue by Balaprabustar** [ckrey/MQTT-Client-Framework#334]
Hi Ckrey,
How can I link this mqtt client dynamically. As this is under Eclipse public licence, I can't attach this statically through pods into my code. So is there any steps to link this lib dynamically?

Regards
Bala

**Comment by ckrey** [comment]
@Balaprabustar Can you explain why you think you cannot link statically because of the Eclipse license?

When you open the MQTTClient workspace in XCode, you see Targets to build frameworks for iOS, tvOs and macOs. You can build them and then include in your project.

**Comment by ckrey** [comment]
I have to admin I am not an expert for dynamic linking. You may find some hints here: #198

**Comment by Balaprabustar** [comment]
Dear @ckrey ,
As per the Eclipce Public License - v 1.0's requirement(3rd section) says that:
**A Contributor may choose to distribute the Program in object code form under
its own license agreement, provided that:

  a) it complies with the terms and conditions of this Agreement; and
  b) its license agreement:
      i) effectively disclaims on behalf of all Contributors all warranties
         and conditions, express and implied, including warranties or
         conditions of title and non-infringement, and implied warranties or
         conditions of merchantability and fitness for a particular purpose;
     ii) effectively excludes on behalf of all Contributors all liability for
         damages, including direct, indirect, special, incidental and
         consequential damages, such as lost profits;
    iii) states that any provisions which differ from this Agreement are
         offered by that Contributor alone and not by any other party; and
     iv) states that source code for the Program is available from such
         Contributor, and informs licensees how to obtain it in a reasonable
         manner on or through a medium customarily used for software exchange.

When the Program is made available in source code form:

  a) it must be made available under this Agreement; and
  b) a copy of this Agreement must be included with each copy of the Program.
     Contributors may not remove or alter any copyright notices contained
     within the Program.** 

So if i link this lib via pods(static linking) we need to release our software also in EPL-v 1.0.

In oreder to over come this, we can link dynamically. So i need some help in dynamic linking.

Also, by any change you have idea to remove EPL-v 1.0 for this lib?
Thanks in advance.

**Comment by ckrey** [comment]
I don't think you have to release your software in EPL-v 1.0

What it says is that if you use this library, me and other contributors disclaim all warranties etc.

And if you make your application available in source code form and include this library, the license of the part of the library cannot be altered.

**Comment by ckrey** [comment]
I cannot alter the EPL license, because part of the software is based on a piece which was licensed under EPL itself.
