### ISSUE TITLE
MQTTSessionManager can't disconnect

### ISSUE THREAD

**Issue by markweng** [ckrey/MQTT-Client-Framework#338]
After the call disconnect method will reconnect

**Comment by ckrey** [comment]
@markweng can you give me some logs or a description of what you are trying to achieve?

**Comment by kirillyakimovich** [comment]
@ckrey i think this is covered by PR 352
@markweng, could you please try to reproduce with my changes?

**Comment by ckrey** [comment]
Thanks, but this will need to wait another week as I am travelling keyboard-free

**Comment by kirillyakimovich** [comment]
Sure, have a good holiday

**Comment by ckrey** [comment]
see #352
