### ISSUE TITLE
When I send data MQTT is crash but not all the time

### ISSUE THREAD

**Issue by codepgq** [ckrey/MQTT-Client-Framework#343]
- (void)openState{
    unsigned char command1[11] = {
        0x00, 0x02, 0x08, 0x04, 0x00, 0x04, 0x00, 0x12, 0x12, 0x00, 0x01
    };
    NSData * data = [NSData dataWithBytes:command1 length:11];
    [self publishData:data publishHandler:nil];
}
this is my send data

the crash
![mqtterror](https://user-images.githubusercontent.com/20208598/28610870-7d8060de-721c-11e7-8e1d-248adb7a7509.png)

![](https://user-images.githubusercontent.com/20208598/28610943-c228eb66-721c-11e7-874e-3cc5b41714f0.png)

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
