### ISSUE TITLE
didReceiveMessage not called before disconnected under SSL

### ISSUE THREAD

**Issue by foxchen2000** [ckrey/MQTT-Client-Framework#344]
* didReceiveMessage not called before disconnected under SSL, and thus app will lost the message

Here are the steps:
1. server sends a message to client.
2. server then disconnects the client, instantly.
3. client receive the message in MQTTCFSocketDecoder and then MQTTDecoder.
4. MQTTDecode tries to open the stream and parse the message.
5. client receives the disconnect stream and then close all the streams.
6. MQTTDecoder which was just opening will then not call delegate to the app.

How can I fix the issue so the app upside will not lost the message just before disconnecting? In my opinion, MQTTDecoder should not be closed if it is working on a stream when disconnected. Any suggestions?

Thank you in advance.

**Comment by ckrey** [comment]
A server should not disconnect except in error situations. The client should.
Which server are you using?

If you need to do so, you should use QoS 1 or 2 and wait until the messages was PUBACKed or PUBCOMPed by the client.

**Comment by foxchen2000** [comment]
Thanks for your quick response.

A server will do disconnect when the user logs on another device with the same clientId. In my project, I'd like the server to post a message to its client before it is disconnected (kicked off by another login).

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
