### ISSUE TITLE
CocoaLumberjack.h file not found

### ISSUE THREAD

**Issue by andy90s** [ckrey/MQTT-Client-Framework#348]
I used the `pod lib create static` , and I also set pod `CocoaLumberjack` in the podsepc .
I wirte the code `#define LUMBERJACK ` , but it prompts the error `CocoaLumberjack.h file not found` , cause I can't close the print log .  
Need your help , thank you !

**Comment by ckrey** [comment]
I do not understand what you are trying to achieve.
