### ISSUE TITLE
How to pass Data or NSData instead of p12 file?

### ISSUE THREAD

**Issue by SanyasiraoM** [ckrey/MQTT-Client-Framework#349]
Hi,

Our backend server generates different p12 files for different users. There I will be getting p12 hex string when user logins. and I can convert that hex string to either NSData or Data. So how can I pass NSData or Data while connecting?

**Comment by ckrey** [comment]
You can see here how the sundry method `clientCertsFromP12` does read certificates from a `.p12` file.

https://github.com/ckrey/MQTT-Client-Framework/blob/21a1d881e6bee3db5d7128c65b23a7581924cb25/MQTTClient/MQTTClient/MQTTCFSocketTransport.m#L149

Just follow along those lines to create your certificates from data directly.

Then set session.transport.certificates according to https://github.com/ckrey/MQTT-Client-Framework/blob/fad0943ddc1c96b5cecc68314f540ac1097b870e/MQTTClient/MQTTClient/MQTTCFSocketTransport.h#L44

@SanyasiraoM  Does this answer your question?

**Comment by SanyasiraoM** [comment]
@ckrey Thanks for responding. I'm a new bee in objective c. Will see what you replied and get back to you!

**Comment by ckrey** [comment]
@SanyasiraoM did you get it working?

**Comment by SanyasiraoM** [comment]
@ckrey Sorry for not responding to the previous answer. I stopped working on that for awhile. Will get back to you once I worked with your answer
