### ISSUE TITLE
If the network is interrupted, reconnection will crash

### ISSUE THREAD

**Issue by wangxumin** [ckrey/MQTT-Client-Framework#350]

**Comment by ckrey** [comment]
Do you want help? Then share a bit of your code. Hundreds of other users don't have your problem

**Comment by wangxumin** [comment]
When the connection is disconnected,i call this code `[self.session connectAndWaitTimeout:1];`reconnect,wait a minute,the application crash at the framework old version,but not happen in the latest version

**Comment by pantaopt** [comment]
me too
