### ISSUE TITLE
No retry on MQTTSessionEventConnectionClosedByBroker

### ISSUE THREAD

**Issue by jcavar** [ckrey/MQTT-Client-Framework#351]
MQTTSessionManager handles this event in specific way and does not call `triggerDelayedReconnect`. What is the reason for that?

**Comment by jcavar** [comment]
This is it seems happening to us in production. We are not exactly sure why but we found another way to reproduce:
1. Create hot spot on iPhone 1
2. Connect to it on iPhone 2
3. On iPhone 1 turn on network link conditioner with 100% loss
4. On iPhone 1 turn off network link conditioner after 10 seconds (exact number depends on keepalive)
5. iPhone 2 disconnects

**Comment by kirillyakimovich** [comment]
Hello, there is no retry on `MQTTSessionEventConnectionClosedByBroker`, but  there is an attempt to connect from scratch, without waiting for any time interval.
As far as i can see `connectToInternal` is called in both cases. 
So my question is: why do you need `triggerDelayedRecconnect` to be called?

**Comment by jcavar** [comment]
We don't need `triggerDelayedReconnect` but `reconnectAfterDisconnect` is false so `connectToLast` is not called in fact.
I don't understand this `reconnectAfterDisconnect` logic TBH. It seems like it is not supposed to reconnect when connecting first time?

**Comment by kirillyakimovich** [comment]
Probably we need to read MQTT spec to understand this handling or just wait for @ckrey 

But for me it looks like in your case `MQTTSessionEventConnectionClosedByBroker` is happening due to ping failure so there are 2 possible scenarios to work around this issue on client side only:
1. You can deactivate keepalive functionality by providing 0
2. You can increase ping interval

http://www.hivemq.com/blog/mqtt-essentials-part-10-alive-client-take-over

**Comment by jcavar** [comment]
We do this for messaging app and if client is disconnected we need to send push notification from server so by increasing keep alive we could miss messages and for the same reason we can't turn it off.

**Comment by jcavar** [comment]
btw, I am happy to create MR for this if we confirm this as a bug.

**Comment by jcavar** [comment]
Ok it seems like there is some history related to this:
Delayed reconnect added here: c59945b9fff8832792e82ec913ab29254d276ede
then changed here: e255874c11cbb6450cec9f8f8d826cc7d7874083
and then commented out here: 0f3ec5b9813a2b3df0ed6fbc58599698162ce9d0

**Comment by jcavar** [comment]
It seems to me like `shouldConnectInForeground` is complicating this somehow? I think these 2 things are not related. Reconnection logic and foreground reconnection logic could be separate and foreground reconnection could be implemented on top of `MQTTSessionManager`?

**Comment by ckrey** [comment]
The original intetion of SessionManager was to handle foreground reconnectiions.

We will have to redesign SessionManager to clarity the different use cases.

I can eirk on this after my return from bacations next week

**Comment by jcavar** [comment]
@ckrey I can post some MRs with my ideas if you are interested? Also, would it be ok to implement new code in Swift or you would prefer ObjC?

This is my plan:

- [ ] There is already one MR that does some basic code formatting https://github.com/ckrey/MQTT-Client-Framework/pull/353
- [ ] Extract timer logic in separate class and unit test it
- [ ] Extract `shouldConnectInForeground` logic in separate class and try to test it (may be harder)
- [ ] Finally fix bug with closed by broker event. I think we could just apply same logic as in error case, but I saw history of this so it may not be true. In that case we could add another event e.g `ClosedByBrokerUnexpectedly` and `ClosedByBrokerExpected`

We could maintain backwards compatibility with all of these changes but eventually my feeling is that `shouldConnectInForeground` should be extracted in separate repo as it doesn't have anything to do with MQTT. It is application specific logic and it depends on UIKit so it can't even be used on some platforms.
