### ISSUE TITLE
Quickly unsubscribing then subscribing to same topic -> still unsubscribed

### ISSUE THREAD

**Issue by sin2** [ckrey/MQTT-Client-Framework#359]

**Comment by ckrey** [comment]
Which qos does the server return with * SUBACK? (- implement subscribed method in delegate or use handler)
* Are you using MQTTSession or MQTTSessionManager?
* Which methods, topic filters , and qos  do you use?

**Comment by sin2** [comment]
MQTTSessionManager - I just set the subscriptions for the sessionmanager to update topic. The topic does not include any filter. Its just a simple string

**Comment by ckrey** [comment]
How do you tell you are unsubscribed?
Please share some code snippets

**Comment by sin2** [comment]
Subcribing
```
[_subscribedTopics addEntriesFromDictionary:@{@"topic" : @(MQTTQosLevelAtMostOnce)}];
self.sessionManager.subscriptions = _subscribedTopics;
```

Unsubscribing
```
[_subscribedTopics removeObjectForKey:@"topic"];
self.sessionManager.subscriptions = _subscribedTopics;
```

_subscribedTopics is a NSMutableDictionary. After unsubscribing,subscribing I know that I am unsubscribed because the effectiveSubscriptions does not contain the topic.

**Comment by ckrey** [comment]
The effectiveSubscriptions will only be updated after the server acknowledged the subscription positively.

Are you connected to the broker?

Best thing to do is to observe MQTTSession's effectiveSubscriptions and state to see changes

SUBSCRIBE/UNDUBSCRIBE need time

**Comment by ckrey** [comment]
Any news on this issue?

**Comment by sin2** [comment]
For now, I am just getting around the issue by keeping track of the subscriptions and retrying at a later time.

**Comment by harariyakamal** [comment]
I also have to do the same. Unsubscribe and subscribe again. But it isn't unsubscribing for me. Only subscribe is happening and I am getting multiple messages because it is subscribing multiple times. 

My code to unsubscribe is : 
let mqttSession = MQTTSession()
mqttSession?.unsubscribeTopic(topic)

Am I missing anything ?
