### ISSUE TITLE
I can't connect with ssl

### ISSUE THREAD

**Issue by wqxlcdymqc** [ckrey/MQTT-Client-Framework#362]
MQTTCFSocketTransport *transport = [[MQTTCFSocketTransport alloc] init];
        transport.port = CR_MQTT_Server_TCP_Port;
        transport.host = CR_MQTT_Server_Addr;
    
        MQTTSSLSecurityPolicy *securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeCertificate];
        NSString* certificate = [[NSBundle mainBundle] pathForResource:@"test" ofType:@"cer"];

        NSData *certData = [NSData dataWithContentsOfFile:certificate];
        securityPolicy.pinnedCertificates = [[NSArray alloc] initWithObjects:certData, nil];
        securityPolicy.allowInvalidCertificates = YES; // if your certificate is self-signed(which didn't coupled with CA infrastructure)
        
        _session = [[MQTTSession alloc]
                    initWithClientId:@"test"
                    userName:@"test"
                    password:@"123456"
                    keepAlive:60
                    cleanSession:YES
                    will:NO
                    willTopic:nil
                    willMsg:nil
                    willQoS:MQTTQosLevelExactlyOnce
                    willRetainFlag:NO
                    protocolLevel:4
                    runLoop:[NSRunLoop mainRunLoop]
                    forMode:NSRunLoopCommonModes
                    securityPolicy:securityPolicy
                    certificates:securityPolicy.pinnedCertificates];
        
        _session.transport = transport;
        _session.delegate = self;

   [self.session connectToHost:self.session.host port:self.session.port usingSSL:YES withConnectionHandler:^(MQTTSessionEvent event) {

     } messageHandler:^(NSData *data, NSString *topic) {

     }];

----------------------------------------------------------------------------------------------
# when i connect to server, I found connect error in -[MQTTSSLSecurityPolicyTransport open]
----------------------------------------------------------------------------------------------

if (self.certificates) {
            [sslOptions setObject:self.certificates
                           forKey:(NSString *)kCFStreamSSLCertificates];
        }
        
        if(!CFReadStreamSetProperty(readStream, kCFStreamPropertySSLSettings, (__bridge CFDictionaryRef)(sslOptions))){
            connectError = [NSError errorWithDomain:@"MQTT"
                                               code:errSSLInternal
                                           userInfo:@{NSLocalizedDescriptionKey : @"Fail to init ssl input stream!"}];
        }
        if(!CFWriteStreamSetProperty(writeStream, kCFStreamPropertySSLSettings, (__bridge CFDictionaryRef)(sslOptions))){
            connectError = [NSError errorWithDomain:@"MQTT"
                                               code:errSSLInternal
                                           userInfo:@{NSLocalizedDescriptionKey : @"Fail to init ssl output stream!"}];
        }

----------------------------------------------------------------------------------------------
#  I found connectError value is " Error Domain=MQTT Code=-9810 "Fail to init ssl input stream!" UserInfo={NSLocalizedDescription=Fail to init ssl input stream!}"
----------------------------------------------------------------------------------------------

**Comment by ckrey** [comment]
You are passing the server certificate as client certificates too. Don't do that, pass `nil` if you don't use client certificates
>                 certificates:securityPolicy.pinnedCertificates];

You are trying to set `willQos` to `MQTTQosLevelExactlyOnce` but you specify no will. The server will not accept that CONNECT packet. Don't do that, use `MQTTQosLevelAtMostOnce` (=0) when not working with will messages
> willQoS:MQTTQosLevelExactlyOnce

Please let me know if this solves your problem.

**Comment by wqxlcdymqc** [comment]
The problem has been resolved, thank you！
