### ISSUE TITLE
mqttTransport didFailWithError Error Domain=kCFErrorDomainCFNetwork Code=2

### ISSUE THREAD

**Issue by UserDhouha** [ckrey/MQTT-Client-Framework#364]
Hi, could you explain to me please why when I connect to the broker (host) using an Xcode simulator it works fine but when I use real device I get this: "**mqttTransport didFailWithError Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={_kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, kCFGetAddrInfoFailureKey=8}**"

thank you

**Comment by ckrey** [comment]
Which hostname ar you trying to connect to?

Probably your phone cannot resolve the name via DNS.

You may check if you can resolve the name with tools like "ISC dig".

Re your mail: What are your expectations on response time and quality of support for an open source, free of charge, non profit, one-man-show library?

**Comment by ckrey** [comment]
Dear @UserDhouha,

how to setup your broker and your internet router and your (Dynamic)DNS does depend on the broker you are using, your operating system, your internet provider.

There are a lot of resources available, but are obviously depending on your environment. One of them is here: https://internetofhomethings.com/homethings/?p=1398

Please understand that this is the issue tracker of MQTTClient library and I cannot give you specific support for your environment
