### ISSUE TITLE
client certificate

### ISSUE THREAD

**Issue by fatkhrus** [ckrey/MQTT-Client-Framework#365]
Is it possible to use private key and certificate of the client for secure communication purposes?

**Comment by ckrey** [comment]
Yes, no problem. Definition and helper to read .p12 files are here:

https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTCFSocketTransport.h

**Comment by fatkhrus** [comment]
Yes. Thank you. It works.
But. There are a lot of memory leaks during using this possibility. Leak Instruments of XCode says Security library is responsible for this. Is it normal?

**Comment by ckrey** [comment]
If you are using MQTTCFSocketTransport, you are using Apple's native CFNetwork implementation.
I have not noticed this yet.
Would you share a screenshot with some more details?

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
