### ISSUE TITLE
How to get the pending messages when connection is created after closed connection ?

### ISSUE THREAD

**Issue by Nautiyalsachin** [ckrey/MQTT-Client-Framework#366]
I tried almost all the ways like

     newSession.cleanSessionFlag = false

and after connection created I am setting 

    newSession.persistence.persistent = true

Any help will be appreciated thanks!

**Comment by ckrey** [comment]
Do you use the same explicit clientId?

**Comment by Nautiyalsachin** [comment]
Nope. Do I have to ? I haven't set the client ID as its not used in your example.

**Comment by Nautiyalsachin** [comment]
I just added it and still I am not getting the pending messages.

    mqttSession = newSession
        newSession.delegate = self
        newSession.clientId = clientId
        newSession.keepAliveInterval = 30
        newSession.cleanSessionFlag = false
        newSession.connect(toHost: host, port: port, usingSSL: false) { (error) in
            if let error = error {
                newSession.persistence.persistent = true
                print("Session is unable to connect",error)
            } else {
                print("Connected")
            }
        }

Here is the code I am using for setting up the connection.

**Comment by ckrey** [comment]
please set persistence = true before you connect

**Comment by ckrey** [comment]
And where are the pending messages you are hoping to receive?

**Comment by ckrey** [comment]
Messages are queued by the broker when you are connected and subscribed to a topic and your client disconnects / looses connection afterwards without unsubscribing.

**Comment by Nautiyalsachin** [comment]
In this delegate method i guess,

    func newMessage(_ session: MQTTSession!, data: Data!, onTopic topic: String!, qos: MQTTQosLevel, retained: Bool, mid: UInt32)

**Comment by ckrey** [comment]
you will receive the messages there, but which messages? Queueing only works when qos>0. 

Here is a good read:
http://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages

**Comment by Nautiyalsachin** [comment]
Oh I got it. When I kill the app and try to connect it again, in that case the session is not available. So I have to create it again, in that case I am not getting any message, is there any suggestion to solve this problem ? Thank you for the quick replies. And thank you for the link too. :)

**Comment by Nautiyalsachin** [comment]
Do i have to switch to session manager or any other suggestions for maintaining it in the app. I am getting the messages now, if the session is there.

**Comment by ckrey** [comment]
Sorry @Nautiyalsachin I have no idea what you are trying to achieve.

You have to connect to a server and subscribe to a topic to receive messages.
If you subscribe with QoS 1 or 2 and the messages are sent (by somebody else) with QoS 1 or 2, the server will queue those messages when your client is off-line, swiped out or whatever.

When you restart your app or reconnect, the server may still have your session status (you are identified by your clientID), it will send out the queued messages.

The server indicates that it has your old session information by setting the session present flag in the CONNACK package.

```
/** gets called when a connection has been successfully established
 @param session the MQTTSession reporting the connect
 @param sessionPresent represents the Session Present flag sent by the broker
 
 */
- (void)connected:(MQTTSession * _Nonnull)session
   sessionPresent:(BOOL)sessionPresent;

```

**Comment by ckrey** [comment]
Instead of writing your own "Session Manager", you can use MQTTSessionManager. It does nothing magic except using MQTTSession and reconnecting to the server after getting backgrounded, swiped out or just loosing connection.

**Comment by Nautiyalsachin** [comment]
MQTTSessionManager sounds awesome. I'll use that and thanks for the solutions. Happy to use this library Cheers!
