### ISSUE TITLE
How make MQTTSession continue to work when exit in background

### ISSUE THREAD

**Issue by NickWarrior** [ckrey/MQTT-Client-Framework#367]

**Comment by kirillyakimovich** [comment]
Hi, there is no way from the box to make MQTTSession, but you can useMQTTSessionManager.
Just provide YES to connectInForeground during initialization:
`- (MQTTSessionManager *)initWithPersistence:(BOOL)persistent
                                                     maxWindowSize:(NSUInteger)maxWindowSize
                                                      maxMessages:(NSUInteger)maxMessages
                                                                maxSize:(NSUInteger)maxSize
                             maxConnectionRetryInterval:(NSTimeInterval)maxRetryInterval
                                         connectInForeground:(BOOL)connectInForeground`

**Comment by NickWarrior** [comment]
Thanks, It worked for me !
