### ISSUE TITLE
Unable to subscribe multiple topics 

### ISSUE THREAD

**Issue by smithparkar** [ckrey/MQTT-Client-Framework#370]
using MQTT-Client-Framework i am unable to subscribe multiple topics. When i am trying to subscribe multiple topics that time 1st topic automatically disconnected and 2nd topic start receiving data.How to fix this problem

**Comment by ckrey** [comment]
There are hundreds of users doing this successfully. Please give us some more info on what your are doing and how (e.g. which methods on which classes you are calling).

*If*  you are using `MQTTSessionManager` and you are setting the `subscriptions` dictionary, please note that your dictionary needs to include all subscriptions you want to have at a time. There is no ~addSubscription~, ~removeSubscription~, or ~updateSubscription~
