### ISSUE TITLE
Format string warnings

### ISSUE THREAD

**Issue by wenxin3262** [ckrey/MQTT-Client-Framework#374]
after using Xcode 9 it shows 7 of this warnings.
```
Format specifies type 'unsigned long' but the argument has type 'unsigned int_Nullable'

Replace %lu with %u
```

for example, MQTTSession.m, line 170

**Comment by ckrey** [comment]
This war ing depends on the target you are building for (32 or 64 bit). The universal way is to use %ul and upcast to (unsigned long).

Will be done eventually.
