### ISSUE TITLE
How could I receive and publish more than one message at once?

### ISSUE THREAD

**Issue by UserDhouha** [ckrey/MQTT-Client-Framework#378]
Hello all :)

Could any one explain to me how **MQTTSwift.swift** works?
In my project I have to **subscribe**  and **publish** more than once:
I have three systems:
- iOS device
- X
- Y

1.    X **publish** to iOS device (MQTT)    # ✓
2.   iOS device **subscribe** (MQTT)        # ✓
3.   iOS device sends this **data** to Y (not using MQTT)     # ✓
4.   Y sends back a response (not using MQTT)   # ✓
5.   iOS device **publish** to X (MQTT)     # ✖

Do I need to create an other session? for every publish/subscribe do I need a separate instance for **MQTTSwift.swift** ??
How could I manage this please?
Thank you for your help 
Have a good day :)

Dhouha

**Comment by ogres** [comment]
Hello,

No, you don't have to create a new session. You should be able to subscribe and publish the data with just one session.

**Comment by ckrey** [comment]
Please direct support requests to support@ckrey.de. We love to hear about your projects with MQTT-Client
