### ISSUE TITLE
Error - mqttTransport didFailWithError Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}

### ISSUE THREAD

**Issue by smithparkar** [ckrey/MQTT-Client-Framework#379]
I am facing problem during subscribing MQTT Topic . I have used self sign SSL certificate. 
After connecting to server it throw error - mqttTransport didFailWithError Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}
2017-09-28 13:20:16.111 MQTTBikeData[3592:103262] [MQTTSession] closeInternal
2017-09-28 13:20:16.112 MQTTBikeData[3592:103262] [MQTTCFSocketTransport] close
2017-09-28 13:44:24.849 MQTTBikeData[3592:104014] Connection error Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}

Here code  - 

NSString *certificate = [[NSBundle mainBundle] pathForResource:certicateName ofType:@"cer"];
    MQTTSSLSecurityPolicy *securityPolicy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeNone];
    securityPolicy.pinnedCertificates = @[[NSData dataWithContentsOfFile:certificate]];
    securityPolicy.allowInvalidCertificates = YES;
    securityPolicy.validatesDomainName= NO;
    securityPolicy.validatesCertificateChain = NO;
   
    MQTTSSLSecurityPolicyTransport* securityPolicyTransport = [[MQTTSSLSecurityPolicyTransport alloc]init];
    securityPolicyTransport.securityPolicy=securityPolicy;
    securityPolicyTransport.port = 8883;
    securityPolicyTransport.host =kSERVERURL;

 MQTTSession *session = [[MQTTSession alloc]initWithClientId:clientID
                                                        userName:userName
                                                        password:password
                                                       keepAlive:60
                                                    cleanSession:YES
                                                            will:NO
                                                       willTopic:topicName
                                                         willMsg:nil
                                                         willQoS:2
                                                  willRetainFlag:NO
                                                   protocolLevel:4
                                                         runLoop:[NSRunLoop currentRunLoop]
                                                         forMode:NSRunLoopCommonModes
                                                 securityPolicy:securityPolicy];
    session.transport = securityPolicyTransport;
    
 [session connectToHost:kSERVERURL port:8883 usingSSL:YES connectHandler:^(NSError *error)
     {
    if (error) {
             NSLog(@"Connection error %@",error.description);
         }
         else
         {
             [session subscribeToTopictopicName atLevel:0 subscribeHandler:^(NSError *error, NSArray<NSNumber *> *gQoss){
                 
                 if (error)
                 {
                     NSLog(@"Subscription failed %@", error.localizedDescription);
                 } else {
                     NSLog(@"Subscription sucessfull! Granted Qos: %@", gQoss);
                 }
             }];
         }
     }];

//Delegate Method
- (void)newMessage:(MQTTSession *)session
              data:(NSData *)data
           onTopic:(NSString *)topic
               qos:(MQTTQosLevel)qos
          retained:(BOOL)retained
               mid:(unsigned int)mid {
    // this is one of the delegate callbacks
    
    
    NSLog(@"recive data onTopic: %@", topic);
    
    NSString *returnString = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    
    NSLog(@" recive  Data: %@", returnString);

}

Please correct if anything wrong here.

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:

```
<!-- Before filing an issue, please search the existing issues (both open and closed) to see if your report might be duplicate -->
<!-- Please don't file an issue when you have a support question, send support questions to the support@ckrey.de) We love to hear about your new projects -->
<!-- We have a mailing list for developers which you can join by sending a mail to mqttclient-dev-subscribe@ckrey.de -->
```

* This is not an issue MQTT-Client-Framework!

* If you want support, mail to support@ckrey.de

* If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de
