### ISSUE TITLE
connectivity with ActiveMQ / Apollo broker

### ISSUE THREAD

**Issue by mfeingold** [ckrey/MQTT-Client-Framework#38]
Your list of 'tested with' brokers does not include ActiveMQ. Did you try to test it? Should we expect any trouble?

**Comment by ckrey** [comment]
no you shouldn't. The only reason why I didn't test is because I couldn't find a test broker or download for test.

I would be happy to run the tests if you can point me to

**Comment by mfeingold** [comment]
There is no separate broker. The out of the box configuration includes MQTT
connector on port 1883. Just download
<http://activemq.apache.org/download.html>it and run

**Comment by ckrey** [comment]
you are right. I do now remember why I excluded ActiveMQ from my initial tests:
According to the feature list it complies to MQTT 3.1, not 3.1.1
This shouldn't be a problem if you set session.protocolLevel = 3.
I will guve it a test run later this afternoon

**Comment by ckrey** [comment]
just like I did for RabbitMQ and rsmb

**Comment by ckrey** [comment]
I ran the complete test suite against an out-of-the-box ActiveMQ:
All tests even with protocolLevel = 4 (MQTT 3.1.1) worked well except a few edge cases, which I will report back to ActiveMQ.

@mfeingold Good luck with your project

**Comment by mfeingold** [comment]
Thank you for the update. Can you share the list of the failing edge cases?

**Comment by ckrey** [comment]
I will log the issues individually in ASF's Jira.
If you would like to deep into it: All the tests are part of the source package

![bildschirmfoto 2015-07-14 um 18 34 02](https://cloud.githubusercontent.com/assets/4027289/8678808/0d18a950-2a57-11e5-9259-4d7e30c6ac59.png)

**Comment by ckrey** [comment]
![bildschirmfoto 2015-07-14 um 19 14 03](https://cloud.githubusercontent.com/assets/4027289/8679708/95f1f5ec-2a5c-11e5-9068-8724f3831a71.png)

**Comment by ckrey** [comment]
Are you planning to use ActiveMQ or Apollo?

![bildschirmfoto 2015-07-15 um 07 01 01](https://cloud.githubusercontent.com/assets/4027289/8691141/748f576a-2abf-11e5-8bd2-fa82f93402bd.png)

**Comment by mfeingold** [comment]
ActiveMQ. Apollo is too new to my taste and there are stability concerns on
the net. We are already using it in prod as internal ESB, as well as 1500
mobile devices - to be expanded to 20000. At this time all devices are
Android based. We are working on coering the iOS plafform

**Comment by mfeingold** [comment]
What about SSL support? Is it OpenSSL based?

**Comment by ckrey** [comment]
yes it has TLS support. Implementatuon is Apple's CFNetwork

**Comment by ckrey** [comment]
Tested positively with Apollo and ActiveMQ
