### ISSUE TITLE
Swift4 call API tutorial？

### ISSUE THREAD

**Issue by jinfagang** [ckrey/MQTT-Client-Framework#380]
Does this support for swift4 and Xcode9?

**Comment by ckrey** [comment]
I work with Xcode9 and can confirm it works!
I don't work with swift4, but I see no reason why it shouldnt work.

There is a swift [example](https://github.com/ckrey/MQTT-Client-Framework/tree/master/MQTTSwift) included.

Reference [documentation](https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/dist/documentation/latex/refman.pdf) is available (for Objective-C).

To answer you headline: No there is no tutorial in swift, but in objective-c [here](http://www.hivemq.com/blog/mqtt-client-library-encyclopedia-mqtt-client-framework).

I do not plan to do a swift tutorial, but would be happy if you contribute one.

To reach out for other developers, subscribe and mail to the [mqttclient developers mailing list](mailto:mqttclient-dev-subscribe@ckrey.de)

**Comment by jinfagang** [comment]
Thanks pal, I am a newbie in swift4, hhhhhhhh
