### ISSUE TITLE
Swift Example can not connect to broker

### ISSUE THREAD

**Issue by jinfagang** [ckrey/MQTT-Client-Framework#381]
Hi, I just running swift example code but can not get connect to broker, here is the log message:
```
Received Optional(27 bytes) on:Optional("jarvis") qMQTTQosLevel rfalse m1
2017-10-01 11:11:11.511902+0800 MQTTSwift[3067:1689861] refreshPreferences: HangTracerEnabled: 0
2017-10-01 11:11:11.512094+0800 MQTTSwift[3067:1689861] refreshPreferences: HangTracerDuration: 500
2017-10-01 11:11:11.512217+0800 MQTTSwift[3067:1689861] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
```
I simply changed the host into my host, but the client wrote in golang and python are just work very fine. this swift version cannot work.
Is there any permission issue I lost? If anyone using swift example worked please let me know is there any changed should add. Many many thanks.

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:

```
<!-- Before filing an issue, please search the existing issues (both open and closed) to see if your report might be duplicate -->
<!-- Please don't file an issue when you have a support question, send support questions to the support@ckrey.de) We love to hear about your new projects -->
<!-- We have a mailing list for developers which you can join by sending a mail to mqttclient-dev-subscribe@ckrey.de -->
```

* This is not an issue MQTT-Client-Framework!

* If you want support, mail to support@ckrey.de

* If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de

Here is *one* hint for you: if you received 27 bytes on topic "Jarvis", you are connected, subscribed and received a message...

**Comment by jinfagang** [comment]
Sorry for bother, it's working fine now, thanks for help.
