### ISSUE TITLE
Not able to unsubscribe

### ISSUE THREAD

**Issue by harariyakamal** [ckrey/MQTT-Client-Framework#382]
I am supposed to do unsubscribe and subscribe again for my application. But it isn't unsubscribing for me. Only subscribe is happening and I am getting multiple messages because it is subscribing multiple times.

My code to unsubscribe is :
let mqttSession = MQTTSession()
mqttSession?.unsubscribeTopic(topic)

Am I missing anything ?

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:

```
<!-- Before filing an issue, please search the existing issues (both open and closed) to see if your report might be duplicate -->
<!-- Please don't file an issue when you have a support question, send support questions to the support@ckrey.de) We love to hear about your new projects -->
<!-- We have a mailing list for developers which you can join by sending a mail to mqttclient-dev-subscribe@ckrey.de -->
```

* This is not an issue MQTT-Client-Framework!

* If you want support, mail to support@ckrey.de

* If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de

Here is *one* hint for you: You have to connect to the broker before you can subscribe, unsubscribe, publish or receive anything ...
