### ISSUE TITLE
How  to pub ack ？

### ISSUE THREAD

**Issue by hongruqi** [ckrey/MQTT-Client-Framework#383]
- Part: MQTT Protocol, MQTTSession, MQTTSessionManager 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system:  iOS, tvOS, macOS 
 - Software version: 
 - Package Manager: Cocoapods, Carthage, Manual 
 - MQTT Broker used: mosquitto, HiveMQ, vernemq, ... 

### Steps to reproduce

1. 
2. 
3.

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:




This is not an issue MQTT-Client-Framework!

If you want support, mail to support@ckrey.de

If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de

Here is one hint for you: You don't have to send PUBACK, the framework does this for you ...

**Comment by hongruqi** [comment]
thanks ckrey. I will send mail to you.
