### ISSUE TITLE
About pending messages and local storage capacity

### ISSUE THREAD

**Issue by Nautiyalsachin** [ckrey/MQTT-Client-Framework#385]
I am using session manager now, Thank you for your suggestion, as I implemented it fully, I am getting some issues here with that, Like

I am unable to send the messages, I am able to get the messages of checkDup but still not able to send any message, its getting stored and I can see the message count increasing.

Its only storing 10 - 12 msgs, after creating the session again.

Edit:

I am getting flow as nil because maxSize = 64 and maxMessages = 1024 it might helps but I can't able to understand still why this causing the failure to the sending message.

in this method :-

- (MQTTCoreDataFlow *)storeMessageForClientId:(NSString *)clientId
                                    topic:(NSString *)topic
                                     data:(NSData *)data
                               retainFlag:(BOOL)retainFlag
                                      qos:(MQTTQosLevel)qos
                                    msgId:(UInt16)msgId
                             incomingFlag:(BOOL)incomingFlag
                              commandType:(UInt8)commandType
                                 deadline:(NSDate *)deadline {
if (([self allFlowsforClientId:clientId incomingFlag:incomingFlag].count <= self.maxMessages) &&
    (fileSize <= self.maxSize)) {

Thanks in advance.

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:




This is not an issue MQTT-Client-Framework!

If you want support, mail to support@ckrey.de. Support is available commercially or maybe for free if you convince us of your cool project

If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de
