### ISSUE TITLE
How SSL supports？

### ISSUE THREAD

**Issue by q393780144www** [ckrey/MQTT-Client-Framework#386]
- Part: MQTT Protocol, MQTTSession, MQTTSessionManager 
 - Issue type: Bug report/Feature request 

### Environment

 - Operating system:  iOS, tvOS, macOS 
 - Software version: 
 - Package Manager: Cocoapods, Carthage, Manual 
 - MQTT Broker used: mosquitto, HiveMQ, vernemq, ... 

### Steps to reproduce

1. 
2. 
3.

**Comment by ckrey** [comment]
You did not read the instructions in the issue template:




This is not an issue MQTT-Client-Framework!

If you want support, mail to support@ckrey.de

If you want to ask the developer community, subscribe to the mqttclient-dev mailing list by sending a mail to mqttclient-dev-subscribe@ckrey.de

Here is one hint for you: Read the [Introduction](https://www.hivemq.com/blog/mqtt-client-library-encyclopedia-mqtt-client-framework) referred to in the README.
