### ISSUE TITLE
Internal not closed when disconnect fails

### ISSUE THREAD

**Issue by jcavar** [ckrey/MQTT-Client-Framework#389]
- Part: MQTTSession
 - Issue type: Bug report

### Short description

As you can see here:
https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSession.m#L541-L543

we check if disconnect succeeds before doing house keeping internally on MQTTSession.
I am not familiar enough with this code to make change, but shouldn't we call `closeInternal` regardless of `isSent`? With this logic, if there is let's say network error when trying to disconnect we will end up in endless disconnecting state?

@kirillyakimovich you can probably shed some light on this?

**Comment by ckrey** [comment]
@jcavar I think you can call `closeInternal` regardless of `isSent`

**Comment by kirillyakimovich** [comment]
With this check i was trying to make sure that client and server are on same page.
I think it's fine to call `closeInternal`

**Comment by jcavar** [comment]
Cool, updated https://github.com/ckrey/MQTT-Client-Framework/pull/388 with this.
