### ISSUE TITLE
crash at MQTTEncoder.m line 132 -[MQTTEncoder stream:handleEvent:]

### ISSUE THREAD

**Issue by Toanso** [ckrey/MQTT-Client-Framework#39]
always crash at line n = [self.stream write:ptr maxLength:length];

**Comment by ckrey** [comment]
@Toanso can you check for me if you keep a reference to the MQTTSession? If not, the callback might target an already free-ed MQTTSession, MQTTEncoder or Stream.

Or show me a code snipped of your session creation / publish
