### ISSUE TITLE
I can't connect using `.crt`or`.cer` certificate!

### ISSUE THREAD

**Issue by s2eker** [ckrey/MQTT-Client-Framework#390]
Hello!
I have used mqtt-client-framwork v0.8.7 for half a year, and it works fine.
Now I need join in ali's iOT which need a roo.crt when connect.
I have convert root.crt file to root.cer file by using command `openssl x509 -in ~/root.crt -out ~/root.cer -outformat der`.

Here is the code:
 

>    MQTTSSLSecurityPolicy *policy = [MQTTSSLSecurityPolicy policyWithPinningMode:MQTTSSLPinningModeCertificate];
>     policy.allowInvalidCertificates = YES;
>     policy.validatesCertificateChain = NO;
>     policy.validatesDomainName = NO;
>     policy.pinnedCertificates = @[[NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"mqtt_iot" ofType:@"cer"]]];
>     self.session.securityPolicy = policy;
>     self.session.clientId = @"uPiJWcXKRdP.camera|securemode=2,timestamp=2524608000000,signmethod=hmacsha1,gw=0|";
>     self.session.userName = @"camera&uPiJWcXKRdP";
>     self.session.password = @"019ebcdedbcb62cb56cc2adc16f3516f4bb609c";
>     [self.session connectToHost:@"uPiJWcXKRdP.iot-as-mqtt.cn-shanghai.aliyuncs.com" port:1883 usingSSL:YES connectHandler:^(NSError *error) {
>         NSLog(@"mqtt connect error! %@", error);
>     }];

Here is the log:
> 2017-11-01 17:23:37.349381+0800 Meari[525:61876] [MQTTSession] init
> 2017-11-01 17:23:37.351886+0800 Meari[525:61876] MQTTSessionLegacy connectToHost:uPiJWcXKRdP.iot-as-mqtt.cn-shanghai.aliyuncs.com port:1883 usingSSL:1 connectHandler:0x105a62b08
> 2017-11-01 17:23:37.351977+0800 Meari[525:61876] [MQTTSession] connectWithConnectHandler:0x105a62b08
> 2017-11-01 17:23:37.351987+0800 Meari[525:61876] [MQTTSession] connecting
> 2017-11-01 17:23:37.352358+0800 Meari[525:61876] [MQTTPersistence] Persistent store: /var/mobile/Containers/Data/Application/FF617757-0C07-40E3-AE0E-71B8F54089E6/Documents/MQTTClient
> 2017-11-01 17:23:37.353408+0800 Meari[525:61876] [MQTTSSLSecurityPolicyTransport] open
> 2017-11-01 17:23:37.357403+0800 Meari[525:61876] [MQTTCFSocketEncoder] setState 0/0
> 2017-11-01 17:23:37.502739+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventOpenCompleted
> 2017-11-01 17:23:37.503127+0800 Meari[525:61876] [MQTTCFSocketEncoder] NSStreamEventOpenCompleted
> 2017-11-01 17:23:37.517691+0800 Meari[525:61876] refreshPreferences: HangTracerEnabled: 0
> 2017-11-01 17:23:37.517725+0800 Meari[525:61876] refreshPreferences: HangTracerDuration: 500
> 2017-11-01 17:23:37.517778+0800 Meari[525:61876] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
> 2017-11-01 17:23:37.602030+0800 Meari[525:61945] Missing server connection for kCTConnectionInvalidatedNotification
> 2017-11-01 17:23:37.648856+0800 Meari[525:61876] [MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable
> 2017-11-01 17:23:37.652351+0800 Meari[525:61876] [MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable
> 2017-11-01 17:23:37.652439+0800 Meari[525:61876] [MQTTCFSocketEncoder] setState 0/1
> 2017-11-01 17:23:37.652512+0800 Meari[525:61876] [MQTTSession] mqttTransportDidOpen
> 2017-11-01 17:23:37.652569+0800 Meari[525:61876] [MQTTSession] sending CONNECT
> 2017-11-01 17:23:37.652763+0800 Meari[525:61876] [MQTTMessage] wireFormat(157)=<109a0100 044d5154 5404c200 3c005175 50694a57 63584b52 64502e63 616d6572 617c7365 63757265 6d6f6465 3d322c74 696d6573 74616d70 3d323532 34363038 30303030 30302c73 69676e6d 6574686f 643d686d 61637368 61312c67 773d307c 00126361 6d657261 26755069 4a576358 4b526450 00273031 39656263 64656462 63623632 63623536 63633261 64633136 66333531 36663462 62363039 63>...
> 2017-11-01 17:23:37.652927+0800 Meari[525:61876] [MQTTSession] mqttTransport send
> 2017-11-01 17:23:37.653079+0800 Meari[525:61876] [MQTTCFSocketEncoder] buffer to write (157)=<109a0100 044d5154 5404c200 3c005175 50694a57 63584b52 64502e63 616d6572 617c7365 63757265 6d6f6465 3d322c74 696d6573 74616d70 3d323532 34363038 30303030 30302c73 69676e6d 6574686f 643d686d 61637368 61312c67 773d307c 00126361 6d657261 26755069 4a576358 4b526450 00273031 39656263 64656462 63623632 63623536 63633261 64633136 66333531 36663462 62363039 63>...
> 2017-11-01 17:23:37.653199+0800 Meari[525:61876] [MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable
> 2017-11-01 17:23:37.653209+0800 Meari[525:61876] [MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable
> 2017-11-01 17:23:37.691631+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventHasBytesAvailable
> 2017-11-01 17:23:37.695048+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventHasBytesAvailable
> 2017-11-01 17:23:37.695134+0800 Meari[525:61876] [MQTTCFSocketDecoder] received (4)=<20020004>...
> 2017-11-01 17:23:37.695151+0800 Meari[525:61876] [MQTTSession] mqttTransport didReceiveMessage
> 2017-11-01 17:23:37.695254+0800 Meari[525:61876] [MQTTDecoder] #streams=1
> 2017-11-01 17:23:37.695296+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventHasBytesAvailable
> 2017-11-01 17:23:37.695305+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventHasBytesAvailable
> 2017-11-01 17:23:37.695402+0800 Meari[525:61876] [MQTTCFSocketDecoder] received (0)=<>...
> 2017-11-01 17:23:37.695415+0800 Meari[525:61876] [MQTTSession] mqttTransport didReceiveMessage
> 2017-11-01 17:23:37.695428+0800 Meari[525:61876] [MQTTDecoder] #streams=2
> 2017-11-01 17:23:37.695437+0800 Meari[525:61876] [MQTTCFSocketDecoder] NSStreamEventEndEncountered
> 2017-11-01 17:23:37.695445+0800 Meari[525:61876] [MQTTSession] mqttTransport mqttTransportDidClose
> 2017-11-01 17:23:37.695596+0800 Meari[525:61876] [MQTTSession] closeInternal
> 2017-11-01 17:23:37.695608+0800 Meari[525:61876] [MQTTCFSocketTransport] close
> 2017-11-01 17:23:37:0.6967:-[WYMQTT connectIOT]_block_invoke[0279]mqtt connect error! Error Domain=MQTT Code=-8 "Server has closed connection without connack." UserInfo={NSLocalizedDescription=Server has closed connection without connack.}

Now mqtt always connect failed while the param is correctly  right.How do I use `.crt` certificate

**Comment by ckrey** [comment]
You do not have an TLS problem, but your userName or Password are wrong. This is what the returned messages says:

> 2017-11-01 17:23:37.695134+0800 Meari[525:61876] [MQTTCFSocketDecoder] received (4)=<20020004>...
>  MQTTRefusedBadUserNameOrPassword = 4,

Unfortunately under some circumstances the CONNACK error message (in this case =4) is not reported to the caller, because the server closing the connection is faster than the processing of the resonse. This is why you see the error -8

**Comment by s2eker** [comment]
yeah!
You're right! 
The password is wrong due to the secure rule have changed.
Thank you!🙏
