### ISSUE TITLE
Start in a not main-thread question.

### ISSUE THREAD

**Issue by Toanso** [ckrey/MQTT-Client-Framework#40]
If mqtt run in mainThread when data push too frequently, it will feel lag when do ui interaction,
How to implement it within a not main-Thread?

Thanks.

**Comment by ckrey** [comment]
simple, just put your connection in a class derived from NSThread.
Examples:

* Tests as part of MQTTClient : https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/MultiThreadingTests.m
* Asynchronous: https://github.com/owntracks/ios/blob/master/OwnTracks/OwnTracks/Connection.m
* Synchronous: https://github.com/owntracks/OwnTracksCTRL/blob/master/OwnTracksCTRL/OwnTracksCTRL/StatelessThread.m
*
