### ISSUE TITLE
File persistence 

### ISSUE THREAD

**Issue by kirillivanov** [ckrey/MQTT-Client-Framework#41]
Hi, in our scenario we need to re-send messages after phone will be rebooted. 
All messages will sent to the offline(airplane mode).

Steps:
1. Send messages to offline
2. Reboot iphone
3. Establish connection with the same ClientID
4. Re send messages

 At the moment, all messages will be lost after reboot.

In the process of debugging i noticed that  "MQTTFlow" records didn't save in the SQLite db after publishing messages while connection lost. No records at all in the DB. The persistent flag set to YES. 

After saving a context ```[self.managedObjectContext save:&error]``` we should not see ```t``` simbol in the ```coredata://``` path. But...

MQTTFlow after context was saved. ```&error``` is nil.
```
<MQTTFlow: 0x7fe93bc1bdd0> (entity: MQTTFlow; id: 0x7fe93bca27a0 <x-coredata:///MQTTFlow/tC5BA5714-874A-40C6-AA10-60D3D1B1B03B2> ; data: {
    clientId = tested12;
    commandType = 3;
    data = <31323331 3233>;
    deadline = "2015-07-23 11:26:43 +0000";
    incomingFlag = 0;
    messageId = 3;
    qosLevel = 2;
    retainedFlag = 0;
    topic = "test-topic1";
})
```
Any thoughts? Thanks!

**Comment by ckrey** [comment]
Thanks for discovering this bug.
The problems is that the persistent store gets allocated in memory instead of on disk.
I will fix this immediately

**Comment by ckrey** [comment]
fixed!

**Comment by ckrey** [comment]
MQTTClient always uses NSManagedObjects.
The difference between persistent and non-persistent is if the NSManagedObjects are backed with SQLite on disk or just in-memory.

**Comment by mfeingold** [comment]
@ckrey wow. that was fast:)

**Comment by kirillivanov** [comment]
@ckrey thanks a lot, will try now!

**Comment by ckrey** [comment]
I'm afraid is was an obvious error :blush:

**Comment by ckrey** [comment]
Please note:
```
/** Control MQTT persistence by setting the properties of persistence before connecting to an MQTT broker.
    The settings are specific to a clientId.
 
    persistence.persistent = YES or NO (default) to establish file or in memory persistence. IMPORTANT: set immediately after creating the MQTTSession before calling any other method. Otherwise the default value (NO) will be used for this session.
```

**Comment by kirillivanov** [comment]
@ckrey  Could you recheck and confirm that you got any records in ZMQTTFLOW table when publish something to offline?

Persistent store: ```/Users/...../Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../Documents/MQTTClient```


 I still got nothing, even if i hardcode ```#define PERSISTENT YES``` inside the lib.



// also doesnt work
_mqttClient = [[MQTTSession alloc] initWithClientId: @"Client1"];
_mqttClient.persistence.persistent = YES;

but records still arrived (looks like lib still store them in memory)

**Comment by ckrey** [comment]
yes confirmed.
Works here now.
What you need to do is to init with
cleansession = no.
Otherwise the persistent store is cleared

**Comment by ckrey** [comment]
cleared on connect

**Comment by kirillivanov** [comment]
Ok, i found an issue, finally. You save only self. context, but doc says that if you got a parent context you should save them as well.


```
When i've started to save parent context, i saw a records in database.
@implementation NSManagedObjectContext ( recursive )

- (void)recursiveSave {
    [self performBlockAndWait:^{
        if (self.hasChanges) {
            NSError *error = nil;
            if (![self save: &error]) {
                if (DEBUGPERSIST) NSLog(@"sync %@", error);
            }
            
            if( nil != self.parentContext ){
                [self.parentContext recursiveSave];
            }
        }
    }];
}

@end
```

**Comment by ckrey** [comment]
mmh, I see the files even without because (see parent context is persistent store coordinator below).
I added some explicit tests for file persistence to the test cases and pushed them to github.

Anyway, I am happy you got it running

![bildschirmfoto 2015-07-23 um 20 00 30](https://cloud.githubusercontent.com/assets/4027289/8858052/883808e0-3175-11e5-99be-572be7665ef0.png)

```
If a context’s parent store is a persistent store coordinator, then changes are committed to the external store. If a context’s parent store is another managed object context, then save: only updates managed objects in that parent store. To commit changes to the external store, you must save changes in the chain of contexts up to and including the context whose parent is the persistent store coordinator.


```

**Comment by kirillivanov** [comment]
Haha i always got that files. However MQTTFlow table in the MQTTClient db file was always empty(after saving context).  But yep it works now. ;)
