### ISSUE TITLE
MQTT Client swallows the very first incomming message

### ISSUE THREAD

**Issue by behrad** [ckrey/MQTT-Client-Framework#42]
I've noticed that when I install my mqtt app on the device, only the first message is not being caught in my newMessage delegate.

After digging into your code I found that the gaurd 
`if (msgId != 0) {`
at https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSession.m#L1211 is false since msgId gets 0!

Can you explain this or guess what could cause this kind of issue @ckrey ?

After the second message, all messages are passing inside and everything works.
I've tried the latest client from your repo, and my broker is `Mosca 0.31.1`

**Comment by behrad** [comment]
it seems msgId is internal sequential message id, which starts from `0` however it may be have been started from `1` !?

**Comment by ckrey** [comment]
I will have to re-check with Mosca. The spec says in QoS 1 or 2, the message ID must be non-zero. This is what my code checks for.


> SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier [MQTT-2.3.1-1].

**Comment by ckrey** [comment]
Seems Mosca starts with zero

**Comment by behrad** [comment]
However Java and node.js clients aren't complaining about this @ckrey 
I haven't read the spec in detail, can't the client be less strict about this?

**Comment by ckrey** [comment]
Checking with mosca...

**Comment by ckrey** [comment]
I can't recreate the problem here.
What QoS do you use? You know mosca supports 0 and 1 only, not 2?
Are you using cleanSession = TRUE?

**Comment by ckrey** [comment]
Recreated with `mosquitto_sub`as a client:
```
mosquitto_sub  -v -q 1 -d -t 'abc' -c -i sub2
Client sub2 sending CONNECT
Client sub2 received CONNACK
Client sub2 sending SUBSCRIBE (Mid: 1, Topic: abc, QoS: 1)
Client sub2 received SUBACK
Subscribed (mid: 1): 1
Client sub2 received PUBLISH (d0, q1, r0, m0, 'abc', ... (3 bytes))
Client sub2 sending PUBACK (Mid: 0)
abc xyz```

**Comment by behrad** [comment]
> What QoS do you use? You know mosca supports 0 and 1 only, not 2?
> Are you using cleanSession = TRUE?

QOS=1
clean=false

**Comment by ckrey** [comment]
Checking if being less strict would cause side effects...

**Comment by behrad** [comment]
great and thundering fix @ckrey Thank you, and you are AWESOME :dancer:

**Comment by behrad** [comment]
download sources from https://github.com/ckrey/MQTT-Client-Framework/releases/tag/0.2.4 and tested,
something is wrong! but I don't know if it is mine or your release...
Haven't changed my code here...it is as it was before the patch.

**Comment by behrad** [comment]
my setup problem.... fixed :)

**Comment by ckrey** [comment]
good! you may consider to use the cocoapods version. I find this very handsome and reliable
