### ISSUE TITLE
After a period of time before switching to the back to the front when the collapse of 100% repetition

### ISSUE THREAD

**Issue by LiuSky** [ckrey/MQTT-Client-Framework#45]
<img width="989" alt="2015-09-06 4 51 33" src="https://cloud.githubusercontent.com/assets/3087745/9703524/33218766-54b9-11e5-879c-b59293e49859.png">
@ckrey

**Comment by ckrey** [comment]
@LiuSky do you keep a strong reference to your MQTTSession? Can you show me a bit of your code when going background and foreground?

**Comment by LiuSky** [comment]
Yes, I keep a strong reference.

**Comment by ogres** [comment]
@LiuSky Do you access MQTTSession from several threads ? is it single threaded ? are you trying to reconnect yourself after app becomes active ?

**Comment by wishsoul** [comment]
I have similar problem with him.
![2015-11-06 11 28 35](https://cloud.githubusercontent.com/assets/6064240/10988703/d03045c0-8479-11e5-9a9b-0489c9441dd8.png)

**Comment by ckrey** [comment]
I assume this is fixed with #61, please re-test

**Comment by LiuSky** [comment]
But I'll be right back when disconnected connection will appear，Can I use this solution, as shown in figure
<img width="708" alt="2016-01-18 10 35 42" src="https://cloud.githubusercontent.com/assets/3087745/12381977/4395d06e-bdcf-11e5-8d09-236d0e6b85ee.png">
