### ISSUE TITLE
connection closed by broker (5)

### ISSUE THREAD

**Issue by soindy** [ckrey/MQTT-Client-Framework#48]
What does this error mean ?

**Comment by ckrey** [comment]
this error code means the broker side has closed the connection.

This typically happens when you have the wrong port, try to access a TLS port in plain mode, etc.

Which broker are you using? How is it configured? Which parameters do you use in init/connect?

**Comment by johnathanz** [comment]
I have this problem with trying to connect to a python code based mosquitto broker.

commandline mosquitto subscribers responds accordingly.

I get nothing back relating to the error when logging on the broker.  The Objective-C Client gets these error codes back: 
`MQTTSession eventCode: connection closed (2) (null)`
`MQTTSession eventCode: connection closed by broker (5) (null)`

If there is consistency in the error code number with the Broker. The python broker documents on_connect error codes as:
`2: Connection refused - invalid client identifier`
`5: Connection refused - not authorised`

On the client, I initiate & subscribes with:

mqttClient is a MQTTSessionManager object

     if (!mqttClient) {
                NSMutableDictionary *tempDict = [@{kMQTT_TOPIC_STATUS : @""} mutableCopy];
                [mqttClient setSubscriptions:tempDict];

                [mqttClient connectTo:ipAddress
                                 port:kMQTT_MESSAGING_PORT
                                  tls:NO
                            keepalive:60
                                clean:YES
                                 auth:NO
                                 user:nil
                                 pass:nil
                                 will:NO
                            willTopic:nil
                              willMsg:nil
                              willQos:nil
                       willRetainFlag:NO
                         withClientId:nil];
            }
            else {
                [mqttClient connectToLast];
            }

What did I do wrong when using MQTT-Client-Framework?

**Comment by ckrey** [comment]
It seems to be the case that your broker does not like the clientId MQTTClient uses.
If you specify `withClientId:nil`, MQTTClient creates a clientId like `MQTTClient497739`.
Can you please check with your broker or set a specifice clientId in your code?

**Comment by ckrey** [comment]
... and the subscription QoS should be a number:
not:
> NSMutableDictionary *tempDict = [@{kMQTT_TOPIC_STATUS : @""} mutableCopy];
but
> NSMutableDictionary *tempDict = [@{kMQTT_TOPIC_STATUS : @(MQTTQosLevelAtMostOnce)} mutableCopy];

**Comment by johnathanz** [comment]
Thanks for answering @ckrey.

It's still not working. I'm currently not using `mosquitto_sub` with client id (i.e. `mosquitto_sub -t ... -h ... -p ...). All parameters used in `mosquitto_sub` from commandline matches what's set in Objective-C with MQTT-Client. 

I've tried setting both Qos level and Client ID (as per your exact suggestion), but still getting the same errors:
`MQTTSession eventCode: connection closed (2) (null)`
`MQTTSession eventCode: connection closed by broker (5) (null)`

What are some ways of getting a more exact error message from Client or Broker for better debugging?

Thanks
Johnathan

**Comment by johnathanz** [comment]
Thanks for answering @ckrey.

It's still not working. I'm currently not using `mosquitto_sub` with client id (i.e. `mosquitto_sub -t ... -h ... -p ...`). All parameters used in `mosquitto_sub` from commandline matches what's set in Objective-C with MQTT-Client. 

I've tried setting both Qos level and Client ID (as per your exact suggestion), but still getting the same errors:
`MQTTSession eventCode: connection closed (2) (null)`
`MQTTSession eventCode: connection closed by broker (5) (null)`

What are some ways of getting a more exact error message from Client or Broker for better debugging?

Thanks
Johnathan

**Comment by ckrey** [comment]
mmh, looking at your code (maybe incomplete):

```
if (!mqttClient) {
            NSMutableDictionary *tempDict = [@{kMQTT_TOPIC_STATUS : @""} mutableCopy];
```
If there is no mqttClient object, you should initialize it with e.g. `mqttClient = [[MQTTSessionManager alloc] init];`
before setting the subscriptions
```
            [mqttClient setSubscriptions:tempDict];

            [mqttClient connectTo:ipAddress
...
```

if you want, you may share a bigger chunk of code with me as a direct mail to krey.christoph@gmail.com

**Comment by johnathanz** [comment]
Thanks for the help @ckrey. I have a nasty habit of sanitising my code when posting on github, making it seem like the original had trivial mistakes like lack of initiatlisation.

After a couple of hours. Finally found the issue.  It was the version of the mosquitto being used on my broker. I was getting:

`1445157880: Invalid protocol "MQTT" in CONNECT from 192.168.1.2.`
`1445157880: Socket read error on client (null), disconnecting.`

Apparently the version of mosquitto I was using was only 3.1 compatible.

I used the instructions here to update apt-get repos and got the latest 3.1/3.11 version of mosquitto
http://mosquitto.org/2013/01/mosquitto-debian-repository/

**Comment by johnathanz** [comment]
consider the issue closed? :+1:

**Comment by ckrey** [comment]
Good to know. 
I usually build mosquitto from the eclipse sources http://mosquitto.org/download/

**Comment by ckrey** [comment]
Do you expect to get an answer when commenting on an issue closed 3 years ago?

Connection closed by broker (5) means you are not authorized on the broker. Check your user and password
