### ISSUE TITLE
SecurityPolicyTests fail for ADN examples

### ISSUE THREAD

**Issue by ckrey** [ckrey/MQTT-Client-Framework#52]
@bobwenx  would take a look why those tests fail (Xcode7.1 iOS9, El Capitan):

![bildschirmfoto 2015-10-02 um 13 10 25](https://cloud.githubusercontent.com/assets/4027289/10245353/f78de1f6-6906-11e5-8bfa-661f0a2adb21.png)

**Comment by bobwenx** [comment]
@ckrey i will check it soon.

**Comment by bobwenx** [comment]
download xcode 7 right now...

**Comment by ckrey** [comment]
refreshed expired certs
