### ISSUE TITLE
Is there a way to get notified of publish result(success/failure)?

### ISSUE THREAD

**Issue by CarlLee** [ckrey/MQTT-Client-Framework#57]
I know it's possible to get notified of successful publish by implementing `- (void)messageDelivered:(MQTTSession *)session msgID:(UInt16)msgID;` method, but I didn't see anything that notifies caller of failures.
`- (void)connectionError:(MQTTSession *)session error:(NSError *)error;` seems to only notify caller of connection failure, but not reporting on-going delivery failures.

Also, I'm using `MQTTSessionManager`, because i need the automatic connect/disconnect. It'll be nice if there's a delegate method called when delivery fails(mainly when network fails).

What I actually want to implement is:

- when publishing fails, show user a retry button.

- try to send again if user presses that button

**Comment by ckrey** [comment]
When you use `MQTTQosLevelAtLeastOnce` or `MQTTQosLevelExactlyOnce`, the library will re-attempt delivery after a timeout.
If the connection is terminated the re-delivery continues after the connection is re-established when you set `clean:NO` in `connectTo`.
This even works after application re-start if you set `persistence:TRUE` in  `initWithPersistence`.

As the MQTT protocol does not have any negative ACK responses, you can assume that all messages are lost if the above mentioned settings are not met or that the message will be delivered in the end.

Still, I think your suggestion for a `messageDelivered` is a valid request. I will include it in the next release

**Comment by ckrey** [comment]
you may use the block interface:

```
session publishData:[@"Sample Data" dataUsingEncoding:NSUTF8StringEncoding]
      topic:@"example/data"
      retain:YES
      qos:1
      publishHandler:^(NSError *error) {
            if (error) {
                  DDLogVerbose(@"error: %@ %@", error.localizedDescription, payload);
            } else {
                  DDLogVerbose(@"delivered:%@", payload);
                  delivered++;
            }
      }];

```
