### ISSUE TITLE
Add carthage support

### ISSUE THREAD

**Issue by ajsharp** [ckrey/MQTT-Client-Framework#58]
More info here: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework. Would be happy to do the PR.

**Comment by ckrey** [comment]
I wasn't aware of Carthage until you pointed me to it.
Sure, go ahead.

**Comment by netgfx** [comment]
Is this supported now? If yes please add it to the ReadMe with instructions (url etc).

**Comment by ckrey** [comment]
Yes it is (see screenshot of README below)

@eltonlivera contributed a pull request #128

![bildschirmfoto 2016-08-25 um 18 32 25](https://cloud.githubusercontent.com/assets/4027289/17977558/80334e9a-6af2-11e6-90c7-1a030321213f.png)

**Comment by netgfx** [comment]
oh great thanks!
