### ISSUE TITLE
Sending empty message enters in deadlock

### ISSUE THREAD

**Issue by TiagoVeloso** [ckrey/MQTT-Client-Framework#59]
I am trying to send an empty payload through `MQTTSessionManager`afterwards my UI enters a deadlock. It seems that the MQTTSessionManager is waiting for some Core Data operation to end.

Have you encountered such a problem before?

**Comment by ckrey** [comment]
No, I don't know the problem.
And I can send

>            [manager sendData:[[NSData alloc] init] topic:@"MQTTSessionManager" qos:MQTTQosLevelAtMostOnce retain:FALSE];

or

>            [manager sendData:nil topic:@"MQTTSessionManager" qos:MQTTQosLevelAtMostOnce retain:FALSE];

**Comment by TiagoVeloso** [comment]
I think my problem is related to issue #56

I think I am sending messages in a thread other than the main thread.

**Comment by ckrey** [comment]
I assume it is fixed with #61
