### ISSUE TITLE
Crashed with SIGABRT when I published the messages.

### ISSUE THREAD

**Issue by taehoon-jung** [ckrey/MQTT-Client-Framework#61]
Hello, 

I adopted MQTT-Client-Framework in my product. :)
But I met a issue when I published messages.

## Issue 
I tested the library using timer. I published few messages every 10s.
After few mins, I got crashed with SIGABRT.

I ran the MQTTSession on subthread with options. 

```
usePhysicalPersistent = NO;
maxSize = 64 * 1024 * 1024;
maxWindowSize = 16;
maxMessages = NSIntegerMax;
```

<img width="1181" alt="2015-11-06 7 55 15" src="https://cloud.githubusercontent.com/assets/11883253/10984371/4786e412-845c-11e5-86a3-a96271d21895.png">

Could you check the issue?

**Comment by ckrey** [comment]
would you share the code of WOSessionManager please (if you want via direct message to krey.christoph@gmail.com)?

**Comment by taehoon-jung** [comment]
I sent a mail now.
Please check your mail box.

**Comment by ckrey** [comment]
@taehoon-jung thanks. I can reproduce the problem. Doing the analysis now

**Comment by ckrey** [comment]
It was a re-entrant problem when calling MQTTSession from different other threads. Solved

**Comment by taehoon-jung** [comment]
@ckrey Thank you very much. :)
