### ISSUE TITLE
MQTTCFSocketEncoder send: causes a delay

### ISSUE THREAD

**Issue by RainLib** [ckrey/MQTT-Client-Framework#615]
After the application card is collected, it is found that MQTT causes application deadlock. The following screenshot shows the specific content
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/18674348/216869175-629c9698-1d39-4e19-888c-eabc49881cbf.png">

**Comment by SailorGa** [comment]
I'm also experiencing this issue，Is there a solution please？

**Comment by RainLib** [comment]
> I'm also experiencing this issue，Is there a solution please？

not yet

**Comment by codehacker2023** [comment]
I'm also experiencing this issue，Is there a solution please？

**Comment by 466102196** [comment]
Is there any progress on this issue? I have the same problem
