### ISSUE TITLE
Other crash issue when I publish lots of messages.

### ISSUE THREAD

**Issue by taehoon-jung** [ckrey/MQTT-Client-Framework#64]
Hello, I met other crash problem about CoreData.
It related about https://github.com/ckrey/MQTT-Client-Framework/issues/61

I ran with same scenario.

```
2015-11-09 14:35:56.245 WorksOne[556:301969] CoreData: error: NULL _cd_rawData but the object is not being turned into a fault
(lldb) po fetchRequest
<NSFetchRequest: 0x13fb64360> (entity: MQTTFlow; predicate: (clientId == "C0568B82-3446-47C2-B578-BEB3F029A2A8" AND incomingFlag == 0); sortDescriptors: ((
    "(deadline, ascending, compare:)"
)); type: NSManagedObjectResultType; )
```

<img width="1254" alt="2015-11-09 2 37 46" src="https://cloud.githubusercontent.com/assets/11883253/11026603/e021123e-86ef-11e5-828e-80ee6d8a3a62.png">

Could you check this issue?
Thank you in advance.

**Comment by ckrey** [comment]
Thanks for testing!
I found the problem, but I will have to do some tests to make sure the change does not have side effects

**Comment by ckrey** [comment]
The problem was caused by using the `managedObjectContext` by multiple threads.
The fix creates a `managedObjectContext`per thread.

This allows now to
- run multiple sessions in one thread
- run multiple sessions in different threads
- run different threads using one session

**Comment by taehoon-jung** [comment]
Thank you so much. :)
I will recommend this library to my coworkers. :+1:
