### ISSUE TITLE
how cloud I get the fail feedback when re-subscribe after reconnect to broker?

### ISSUE THREAD

**Issue by funkyLover** [ckrey/MQTT-Client-Framework#65]
i use MQTTSessionManager to manage the MQTT connection, i find that it will re-subscribe the topic automatically after reconnecting to broker,. how it work when get a fail state with the re-subscribe action? it will re-subscribe all the time? or can I get the feedback with that?

**Comment by ckrey** [comment]
Subscription might fail because
a) a connection error: re-subscription will happen after next connect
b) invalid subscription topic (e.g. "abc/#/def"): subscription is rejected by broker, broker disconnects, client will re-attempt after next connect.
c) subscription not authorized: subscription will either be silently SUBACKed but ignored by broker or SUBACK return code will be 0x80. In both  cases subscription will have no effect.

Which kind of feedback would you like to see?

**Comment by funkyLover** [comment]
I want to get the feedback with the b and c situation

**Comment by ckrey** [comment]
In case of b) you get feedback by observing MQTTSessionManager's state. The MQTT protocol does not specify a feedback in case of protocol errors (as attempting to subscribe to illegal topic filters), but just closes the connection on broker side. So the feedback is not specific.

In case of c) it depends on the broker implementation: If the broker silently accepts the subscription the client has no chance to find out.

Depending on your needs, you may use MQTTSession to implement the feedback yourself (MQTTSessionManager uses MQTTSession) or extend MQTTSessionManager by implementing the (us)subackreceived methods and keep track of the subscriptions as acknowledged by the broker.

If you do so, I would be happy to accept a PR from you.

**Comment by ckrey** [comment]
see docs for new observable property `effectiveSubscriptions`

**Comment by funkyLover** [comment]
I could not find that property `effectiveSubscriptions` from docs and code
btw,
```
// from MQTTSessionDelegate <NSObject>
 - (void)subAckReceived:(MQTTSession *)session msgID:(UInt16)msgID grantedQoss:(NSArray *)qoss;

//from MQTTSession
- (BOOL)subscribeAndWaitToTopics:(NSDictionary *)topics;

```
I think it will be reasonable to get the feedback by using that two method
it that right?

**Comment by ckrey** [comment]
please wait a little while. I haven't released it to github/cocoapods yet, need to run a few regression tests first.

**Comment by ckrey** [comment]
I will set the issue to closed when released
