### ISSUE TITLE
Consider contributing MQTT-Client-Framework (back) to eclipse

### ISSUE THREAD

**Issue by ckrey** [ckrey/MQTT-Client-Framework#75]
I am considering to contribute the code to the Eclipse foundation. This will widen the visibility
of the Framework.

The reason for this is the code it originally forked off is now part of eclipse paho.
http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.objc.git/
Due to the lack of maintenance that code is out of date.

I filed a bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=482381 to initiate the process.

If the process goes ahead, all contributors would have to sign the following agreement:
https://www.eclipse.org/legal/CLA.html

I see that especially you @bobwenx did contribute a whole lot regarding pinned certificates
and custom SSL security policies. 

The other contributors are:
@mycoboco 
@ogres 
@kirang89 
@CarlLee 

Would all of you agree signing the CLA? If you see any problem, please contact me directly.

**Comment by kirang89** [comment]
I agree.

**Comment by mycoboco** [comment]
I agree, too.

**Comment by CarlLee** [comment]
I agree. I only fixed one bug though.

**Comment by ckrey** [comment]
@CarlLee thanks, I know but eclipse seems to be quite strict on this

**Comment by ckrey** [comment]
eclipse contrtibution is too complicated because of IP (contributors) and Apple restrictions
