### ISSUE TITLE
Very slow when receiving offline messages on Qos = 2

### ISSUE THREAD

**Issue by xmkevin** [ckrey/MQTT-Client-Framework#82]
I found that it's very slow when receiving offline messages on Qos = 2. The server is mosquitto 1.4.5. It seems the persistence cannot handle multiple offline messages at the same time. I will checkout this issue tomorrow. Can you check this issue too ?

**Comment by ckrey** [comment]
Well it is mot slow, but it limits the number of inflight messages. Thus it will not respond to more than maxWindowSize messages with PUBREC before PUBREL is received. This works in conjunction with maxinflight Messages setting in Mosquitto.

**Comment by ckrey** [comment]
Without limiting the maxWindowSize (default is 16), zhe receiving side gets easily overrun by messages. You can simply increase the window size and ensure your message processing is fast or queued to a separate thread

**Comment by xmkevin** [comment]
Thanks. I think it's not that issue. I  enabled the debug mode I found that when receving 3 messages at the same time, 2 of them will be discarded when persisting. Since the Qos is 2, the broker will publish the left 2 messages again, and then one of them missing.  I will give more details tomorrow, since I don't have the environment home. Thanks.

**Comment by xmkevin** [comment]
I found the problem, I init the SessionManager with the default init function, but it doesn't init the default persistent's maxSize, maxMessages properties.  Thanks.
