### ISSUE TITLE
MQTTDecoder runLoop no longer configurable

### ISSUE THREAD

**Issue by zgthompson** [ckrey/MQTT-Client-Framework#87]
First off, thank you for all the work you've done on this framework.

Previous to the transport layer addition, the runLoop set for the MQTTSession would be passed to MQTTDecoder for its stream. Now, the MQTTDecoder uses the currentRunLoop upon initialization regardless of the runLoop set for the MQTTSession. Since MQTTDecoder is initialized during connect, the runLoop is determined based on whichever thread connect happens to be called on. It seems to me that the MQTTSession runLoop should continue to be passed onto the MQTTDecoder, since the stated intent of the runLoop in MQTTSession.h is for scheduling the streams.

Is this an intended change?

**Comment by ckrey** [comment]
No, this was not intended.
I added the leftout bits and bytes...
0.6.2 is coming

Same was true for the actual CFSocket and CFSSLSecurity implementation streams

**Comment by zgthompson** [comment]
Awesome, thanks!
