### ISSUE TITLE
connect to server didn't get response

### ISSUE THREAD

**Issue by xxi511** [ckrey/MQTT-Client-Framework#88]
Hi, I tried to connect to RabbitMQ recently .
Before, I used version 0.5, and it showed "connection close by broker...." at console
But after I updated to version 0.6.2, the console showed nothing, and still connect failed

here is my code
https://gist.github.com/xxi511/2faca3bbf5bebcbbc974

thank you

**Comment by ckrey** [comment]
Thanks for testing:

a) you cannot modify manager.subscriptions, just set it to a new NSDictionary.

Please change
```
        self.manager.subscriptions = [[NSMutableDictionary alloc] init];
        [self.manager.subscriptions setValue:@(MQTTQosLevelAtLeastOnce) forKey:@"mySubscription"];
```
to
```
        NSMutableDictionary mySubscriptions = [[NSMutableDictionary alloc] init];
        [mySubscriptions setValue:@(MQTTQosLevelAtLeastOnce) forKey:@"mySubscription"];
        self.manager.subscriptions = mySubscriptions;
```

**Comment by ckrey** [comment]
b) console debugging output is controlled by DEBUG settings using either CocoaLumberjack or NSLog

I cannot check why there is no output without seeing the complete project, sorry.

There are a number of reasons why your code may to connect:
- IP/hostname wrong
- port not listening
- no route to host
- wrong user/password
- topic for will not writeable (ACL)

```
        [self.manager connectTo:@"myHostIP"
                           port:8883
                            tls:true
                      keepalive:60
                          clean:false
                           auth:true
                           user:@"myUserID"
                           pass:@"myPassword"
                      willTopic:@"amq.topic"
                           will:[@"offline" dataUsingEncoding:NSUTF8StringEncoding]
                        willQos:MQTTQosLevelAtLeastOnce
                 willRetainFlag:FALSE
                   withClientId:@"DeviceID"];
```

Can you do me a favor and try to connect from the same machine using mosquitto_pub ?
`mosquitto-pub -i DeviceID -h myHostIP -p 8883 --cafile <broker-ca-file> -c -u myUserId -P -myPassword -t amq.topic -m offline -q 1 -d`

**Comment by xxi511** [comment]
Thanks for answer, I connect successful.

https://gist.github.com/xxi511/2faca3bbf5bebcbbc974

I use [self connectBySession] and it work perfectly.

And then I use other function from MQTTSessionManager,  [self connectByManager_new], and it work too, only if I just subscribe one topic, if I subscribe two topic, it connect successful then close immediately.The state is  connecting=>connected=>closed=>starting=>error=>starting=>connecting...Loop

**Comment by ckrey** [comment]
Which topic are you connecting to with which Qos and which kind of broker?

**Comment by xxi511** [comment]
The  willTopic of sessionManager?   nil, I didn't set the value about will, willTopic and willMsg
or the topic of subscriptions? @"user.userID"  and @"user.chatRoom"

Qos is MQTTQosLevelAtLeastOnce

And about broker, i'm not sure....do you mean [RabbitMQ](https://www.rabbitmq.com/) 

I hope this can answer your question :)

I found that I have two [self connectByManager_old] in my gist, the [self connectByManager_new] is meaning the second one

**Comment by ckrey** [comment]
you have the same problem as #91. If you say will:NO, you have to say willQos:MQTTQosLevelAtMostOnce!

**Comment by xxi511** [comment]
like this one? not work :(

        self.manager = [[MQTTSessionManager alloc] init];
        self.manager.delegate = self;
       
        
        self.manager.subscriptions = [[NSMutableDictionary alloc] init];
        NSMutableDictionary *mySuscript = [[NSMutableDictionary alloc]init];
        [mySuscript setValue:@(MQTTQosLevelAtLeastOnce) forKey:@"user.userID"];
        [mySuscript setValue:@(MQTTQosLevelAtLeastOnce) forKey:@"user.chatRoom"];
        self.manager.subscriptions = mySuscript;
        
        [self.manager connectTo:MQUrl
                           port:8883
                            tls:true
                      keepalive:300
                          clean:false
                           auth:true
                           user:@"userID"
                           pass:@"pass"
                           will:NO
                      willTopic:nil
                        willMsg:nil
                        willQos:MQTTQosLevelAtMostOnce
                 willRetainFlag:false
                   withClientId:[_dataManager getDeviceID]];

**Comment by xxi511** [comment]
Hi, after I updated to version 0.65
the session manager can subscribe two channels at same time
and if the connect closed, it can reconnect  well
thank you very much

**Comment by ckrey** [comment]
Good to hear
