### ISSUE TITLE
protocoll error

### ISSUE THREAD

**Issue by xiaoer371** [ckrey/MQTT-Client-Framework#89]
hello , i using this open source . very good.
i don’t know that  how and when will appear the problem。 
now In order to solve this problem, I must  set MQTT cleansession  yes and reconnect。
How to prevent this kind of problem?

MQTTSession eventCode: connection closed (2) (null)
MQTTSession eventCode: connection error (3) (null)
MQTTSession eventCode: connection closed (2) (null)
MQTTSession eventCode: protocoll error (4) Error Domain=MQTT Code=-4 "Encoder error" UserInfo={NSLocalizedDescription=Encoder error}

**Comment by xiaoer371** [comment]
sometimes  abnormal，
happen  
MQTTSessionEventConnectionClosed:
MQTTSessionEventConnectionClosedByBroker:
your library don‘t reconnect。
important  if i reconnect my broker，that  will connect the broker。

your code ：
- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error
{
#ifdef DEBUG
    const NSDictionary *events = @{
                                   @(MQTTSessionEventConnected): @"connected",
                                   @(MQTTSessionEventConnectionRefused): @"connection refused",
                                   @(MQTTSessionEventConnectionClosed): @"connection closed",
                                   @(MQTTSessionEventConnectionError): @"connection error",
                                   @(MQTTSessionEventProtocolError): @"protocoll error",
                                   @(MQTTSessionEventConnectionClosedByBroker): @"connection closed by broker"
                                   };
    NSLog(@"MQTTSession eventCode: %@ (%ld) %@", events[@(eventCode)], (long)eventCode, error);
#endif
    [self.reconnectTimer invalidate];
    switch (eventCode) {
        case MQTTSessionEventConnected:
        {
            self.lastErrorCode = nil;
            self.state = MQTTSessionManagerStateConnected;
            break;
        }
        case MQTTSessionEventConnectionClosed:
        case MQTTSessionEventConnectionClosedByBroker:
            self.state = MQTTSessionManagerStateClosed;
#if TARGET_OS_IPHONE == 1
            if (self.backgroundTask) {
                [[UIApplication sharedApplication] endBackgroundTask:self.backgroundTask];
                self.backgroundTask = UIBackgroundTaskInvalid;
            }
#endif
            self.state = MQTTSessionManagerStateStarting;
            break;
        case MQTTSessionEventProtocolError:
        case MQTTSessionEventConnectionRefused:
        case MQTTSessionEventConnectionError:
        {
            self.reconnectTimer = [NSTimer timerWithTimeInterval:self.reconnectTime
                                                          target:self
                                                        selector:@selector(reconnect)
                                                        userInfo:Nil repeats:FALSE];
            NSRunLoop *runLoop = [NSRunLoop currentRunLoop];
            [runLoop addTimer:self.reconnectTimer
                      forMode:NSDefaultRunLoopMode];
            
            self.state = MQTTSessionManagerStateError;
            self.lastErrorCode = error;
            break;
        }
        default:
            break;
    }
}
wy  
 case MQTTSessionEventConnectionClosed:
 case MQTTSessionEventConnectionClosedByBroker:
Don't need a reconnection？？？

**Comment by ckrey** [comment]
Are you asking a theoretic question or are you referring to an actual situation?

The latter cases usually (and I haven't seen others) occur when the connection is intentionally
closed by the client or the broker as part of the disconnect protocol.

**Comment by ckrey** [comment]
Some brokers do not support CleanSession=NO (e.g. AWS IoT).

Any progress on your side?

**Comment by xiaoer371** [comment]
I will continue to study, may my broker have some problems.If there is progress, I will tell you the first time.
