### ISSUE TITLE
Turn of verbose logging

### ISSUE THREAD

**Issue by brandonroth** [ckrey/MQTT-Client-Framework#97]
Is it possible to turn off the cocoalumberjack logging features of the library?  In an existing application with cocoalumberjack setup the mqtt logs completely overwhelm everything else.

**Comment by mignick** [comment]
+1 
It's better to have a lib's specific logging macro instead of general DEBUG macro.
Thanks!

**Comment by 0x5e** [comment]
+1
now we have to filter mqtt log by comparing prefix @"[MQTT"
hope to have another solution, thanks!
