### ISSUE TITLE
Cocoa pod missing files

### ISSUE THREAD

**Issue by liltimtim** [ckrey/MQTT-Client-Framework#98]
Hello,

I saw the new version 0.6.5 and did a pod update.  The version matches the newest release tag however some files are still missing such as the web socket portions.   

Attached is a screenshot of what the pod installed. 
![screen shot 2016-01-21 at 10 07 19 am](https://cloud.githubusercontent.com/assets/4106065/12484147/dc3d8f7e-c026-11e5-84b6-ebe118fe9f2d.png)

**Comment by liltimtim** [comment]
Also, thank you for the really fast replies! I greatly appreciate that

**Comment by ckrey** [comment]
for web sockets you need to specify an additional sub pod as written in README.md:
The reason for this is to avoid including SocketRocket and libucio if not necessary:

![bildschirmfoto 2016-01-21 um 16 25 46](https://cloud.githubusercontent.com/assets/4027289/12484695/c2b0dba8-c05b-11e5-891f-5788c714086a.png)

**Comment by liltimtim** [comment]
Ah I see now. Sorry about that. Thank you for the reply

**Comment by liltimtim** [comment]
After following the additional instructions for including web socket library IT WORKS!!! woohoo.  Thanks again for helping! Keep up the fantastic work!
