### ISSUE TITLE
Syntax error during build

### ISSUE THREAD

**Issue by kiran-geon** [ckrey/MQTT-Client-Framework#99]
I apologize in advance if this is not the place to post this issue. Please just point me to the right forum.

We are trying to build this project. But we are getting syntax errors during build. Error  like :
Error : Expected ; after id
Error: Expected >
Error : property has previous declaration

I feel that this is because a minor project misconfiguration. Or maybe some dependency is missing. Can you please let me know if there is any extra configuration to be done?

**Comment by AymanRadid** [comment]
Update Xcode it should fix the problem, the client uses some new syntax features introduced in Xcode 7 to enhance compatibility with swift.

**Comment by ckrey** [comment]
Thanks @AymanRadid
